import { QueryRecommendation } from '../api/types';
import { UseGetQueryRecommendationsParams } from '../use-get-query-recommendations';

export const MOCK_QUERY_REC_PARAMS: UseGetQueryRecommendationsParams = {
  contextTitle: 'My Data Source',
  count: 2,
};

export const MOCK_QUERY_REC_RESPONSE: QueryRecommendation[] = [
  {
    nlqPrompt: 'What is the total revenue generated by each brand?',
    jaql: {
      datasource: {
        title: 'My Data Source',
        type: 'elasticube',
      },
      metadata: [
        {
          jaql: {
            dim: '[Brand.Brand]',
            table: 'Brand',
            column: 'Brand',
            datatype: 'text',
            title: 'Brand',
          },
          panel: 'rows',
        },
        {
          jaql: {
            type: 'measure',
            context: {
              ['d6fb']: {
                dim: '[Commerce.Revenue]',
                table: 'Commerce',
                column: 'Revenue',
              },
            },
            formula: "sum(['d6fb'])",
            title: 'total of Revenue',
          },
          panel: 'measures',
        },
      ],
    },
    chartRecommendations: {
      chartFamily: 'cartesian',
      chartType: 'bar',
      axesMapping: {
        category: [
          {
            name: 'Brand',
            type: 'string',
          },
        ],
        value: [
          {
            name: 'total of Revenue',
            type: 'number',
          },
        ],
      },
    },
    userMsg: '',
    clarification: '',
    queryTitle: 'total of Revenue by Brand',
    detailedDescription: 'total of [Commerce.Revenue] by [Brand.Brand]',
  },
  {
    nlqPrompt: 'What is the total revenue generated by each category?',
    jaql: {
      datasource: {
        title: 'My Data Source',
        type: 'elasticube',
      },
      metadata: [
        {
          jaql: {
            dim: '[Category.Category]',
            table: 'Category',
            column: 'Category',
            datatype: 'text',
            title: 'Category',
          },
          panel: 'rows',
        },
        {
          jaql: {
            type: 'measure',
            context: {
              ['d6fb']: {
                dim: '[Commerce.Revenue]',
                table: 'Commerce',
                column: 'Revenue',
              },
            },
            formula: "sum(['d6fb'])",
            title: 'total of Revenue',
          },
          panel: 'measures',
        },
      ],
    },
    chartRecommendations: {
      chartFamily: 'table',
      chartType: 'table',
      axesMapping: {
        columns: [
          {
            name: 'Category',
            type: 'string',
          },
          {
            name: 'total of Revenue',
            type: 'number',
          },
        ],
      },
    },
    userMsg: '',
    clarification: '',
    queryTitle: 'total of Revenue by Category',
    detailedDescription: 'total of [Commerce.Revenue] by [Category.Category]',
  },
];
