import { Filter, measures, filters, NumericFilter, TextFilter } from '@sisense/sdk-data';
import { ChartWidget } from '../../widgets/chart-widget.js';
import * as DM from '../sample-ecommerce-autogenerated.js';
import { useMemo, useState } from 'react';
import { CriteriaFilterTile } from '../../filters/components/criteria-filter-tile/criteria-filter-tile.js';

export const CriteriaFilterDemo = () => {
  const dataOptions = {
    category: [DM.Category.Category],
    value: [measures.sum(DM.Commerce.Revenue, 'Revenue')],
    breakBy: [],
  };
  const styleOptions = {};
  const drilldownOptions = {
    drilldownDimensions: [
      DM.Commerce.Quantity,
      DM.Commerce.AgeRange,
      DM.Commerce.Condition,
      DM.Country.Country,
    ],
  };

  const initialRevenueFilter = filters.greaterThanOrEqual(DM.Commerce.Revenue, 10000);
  const [revenueFilter, setRevenueFilter] = useState<Filter | null>(initialRevenueFilter);

  const initialCostFilter = filters.between(DM.Commerce.Cost, 0, 10000);
  const [costFilter, setCostFilter] = useState<Filter | null>(initialCostFilter);

  const initialCategoryFilter = filters.doesntContain(DM.Category.Category, 'Cameras');
  const [categoryFilter, setCategoryFilter] = useState<Filter | null>(initialCategoryFilter);

  const initialCountryFilter = filters.doesntStartWith(DM.Country.Country, 'United');
  const [countryFilter, setCountryFilter] = useState<Filter | null>(initialCountryFilter);

  const appliedFilters = useMemo(() => {
    const filterList = [];
    filterList.push(revenueFilter);
    filterList.push(costFilter);
    filterList.push(categoryFilter);
    filterList.push(countryFilter);
    return filterList;
  }, [categoryFilter, costFilter, countryFilter, revenueFilter]);
  return (
    <>
      <div className={'csdk-flex'}>
        <CriteriaFilterTile
          title={'Numeric Criteria: Revenue'}
          filter={appliedFilters?.[0] as NumericFilter}
          onUpdate={setRevenueFilter}
        />
        <CriteriaFilterTile
          title={'Numeric Criteria: Cost'}
          filter={appliedFilters?.[1] as NumericFilter}
          onUpdate={setCostFilter}
        />
        <CriteriaFilterTile
          title={'Text Criteria: Category'}
          filter={appliedFilters?.[2] as TextFilter}
          onUpdate={setCategoryFilter}
        />
        <CriteriaFilterTile
          title={'Text Criteria: Country'}
          filter={appliedFilters?.[3] as TextFilter}
          onUpdate={setCountryFilter}
        />
      </div>
      <ChartWidget
        dataSource={DM.DataSource}
        chartType={'column'}
        dataOptions={dataOptions}
        filters={appliedFilters.filter((f) => f !== null) as Filter[]}
        drilldownOptions={drilldownOptions}
        styleOptions={styleOptions}
      />
    </>
  );
};
