import { Filter, measureFactory, filterFactory, RelativeDateFilter } from '@sisense/sdk-data';
import { ChartWidget } from '../../widgets/chart-widget.js';
import * as DM from '../sample-ecommerce-autogenerated.js';
import { useState } from 'react';
import { RelativeDateFilterTile } from '../../filters/index.js';

export const RelativeDateFilterDemo = () => {
  const measureSumRevenue = measureFactory.sum(DM.Commerce.Revenue, 'sum Revenue');
  const styleOptions = {};

  const initialFilter = filterFactory.dateRelativeTo(DM.Commerce.Date.Months, 0, 150);
  const [filter, setFilter] = useState<Filter | null>(initialFilter);

  return (
    <>
      <div className={'csdk-flex'}>
        <RelativeDateFilterTile
          title={'Relative Date Filter'}
          filter={filter as RelativeDateFilter}
          arrangement={'vertical'}
          onUpdate={(newFilter) => setFilter(newFilter)}
        />
      </div>
      <ChartWidget
        dataSource={DM.DataSource}
        chartType={'line'}
        dataOptions={{
          category: [DM.Commerce.Date.Months],
          value: [measureSumRevenue],
          breakBy: [],
        }}
        filters={filter ? [filter] : undefined}
        styleOptions={styleOptions}
      />
    </>
  );
};
