import { Filter, measures as measureFactory } from '@sisense/sdk-data';
import { ChartWidget } from '../../widgets/ChartWidget';
import * as DM from '../sample-ecommerce-autogenerated';

const dataOptions = {
  category: [DM.Category.Category],
  value: [measureFactory.sum(DM.Commerce.Revenue)],
  breakBy: [],
};
const styleOptions = {};

const filters: Filter[] = [];

const drilldownOptions = {
  drilldownCategories: [DM.Commerce.AgeRange, DM.Commerce.Gender, DM.Commerce.Condition],
};

export const WidgetDemo = () => (
  <div className="h-fit">
    With Drilldown
    <ChartWidget
      dataSource={DM.DataSource}
      chartType="bar"
      filters={filters}
      dataOptions={dataOptions}
      styleOptions={styleOptions}
      drilldownOptions={drilldownOptions}
    />
    No Drilldown
    <ChartWidget
      dataSource={DM.DataSource}
      chartType="bar"
      filters={filters}
      dataOptions={dataOptions}
      styleOptions={styleOptions}
    />
  </div>
);
