export const MOCK_DATA_SOURCE_FIELDS = [
  {
    id: '[Brand.Brand]',
    type: 'dimension',
    dimtype: 'text',
    title: 'Brand',
    table: 'Brand',
    column: 'Brand',
    merged: false,
    indexed: true,
  },
  {
    id: '[Brand.Brand ID]',
    type: 'dimension',
    dimtype: 'numeric',
    title: 'Brand ID',
    table: 'Brand',
    column: 'Brand ID',
    merged: true,
    indexed: false,
  },
  {
    id: '[Category.Category]',
    type: 'dimension',
    dimtype: 'text',
    title: 'Category',
    table: 'Category',
    column: 'Category',
    merged: false,
    indexed: true,
  },
  {
    id: '[Category.Category ID]',
    type: 'dimension',
    dimtype: 'numeric',
    title: 'Category ID',
    table: 'Category',
    column: 'Category ID',
    merged: true,
    indexed: false,
  },
  {
    id: '[Commerce.Age Range]',
    type: 'dimension',
    dimtype: 'text',
    title: 'Age Range',
    table: 'Commerce',
    column: 'Age Range',
    merged: false,
    indexed: true,
  },
  {
    id: '[Commerce.Brand ID]',
    type: 'dimension',
    dimtype: 'numeric',
    title: 'Brand ID',
    table: 'Commerce',
    column: 'Brand ID',
    merged: true,
    indexed: false,
  },
  {
    id: '[Commerce.Category ID]',
    type: 'dimension',
    dimtype: 'numeric',
    title: 'Category ID',
    table: 'Commerce',
    column: 'Category ID',
    merged: true,
    indexed: false,
  },
  {
    id: '[Commerce.Condition]',
    type: 'dimension',
    dimtype: 'text',
    title: 'Condition',
    table: 'Commerce',
    column: 'Condition',
    merged: false,
    indexed: true,
  },
  {
    id: '[Commerce.Cost]',
    type: 'dimension',
    dimtype: 'numeric',
    title: 'Cost',
    table: 'Commerce',
    column: 'Cost',
    merged: false,
    indexed: false,
  },
  {
    id: '[Commerce.Country ID]',
    type: 'dimension',
    dimtype: 'numeric',
    title: 'Country ID',
    table: 'Commerce',
    column: 'Country ID',
    merged: true,
    indexed: false,
  },
  {
    id: '[Commerce.Date (Calendar)]',
    type: 'dimension',
    dimtype: 'datetime',
    title: 'Date',
    table: 'Commerce',
    column: 'Date',
    merged: false,
    indexed: true,
  },
  {
    id: '[Commerce.Gender]',
    type: 'dimension',
    dimtype: 'text',
    title: 'Gender',
    table: 'Commerce',
    column: 'Gender',
    merged: false,
    indexed: true,
  },
  {
    id: '[Commerce.Quantity]',
    type: 'dimension',
    dimtype: 'numeric',
    title: 'Quantity',
    table: 'Commerce',
    column: 'Quantity',
    merged: false,
    indexed: false,
  },
  {
    id: '[Commerce.Revenue]',
    type: 'dimension',
    dimtype: 'numeric',
    title: 'Revenue',
    table: 'Commerce',
    column: 'Revenue',
    merged: false,
    indexed: false,
  },
  {
    id: '[Commerce.Visit ID]',
    type: 'dimension',
    dimtype: 'numeric',
    title: 'Visit ID',
    table: 'Commerce',
    column: 'Visit ID',
    merged: false,
    indexed: false,
  },
  {
    id: '[Country.Country]',
    type: 'dimension',
    dimtype: 'text',
    title: 'Country',
    table: 'Country',
    column: 'Country',
    merged: true,
    indexed: true,
  },
  {
    id: '[Country.Country ID]',
    type: 'dimension',
    dimtype: 'numeric',
    title: 'Country ID',
    table: 'Country',
    column: 'Country ID',
    merged: true,
    indexed: false,
  },
  {
    id: '[CountryPopulation.Continent]',
    type: 'dimension',
    dimtype: 'text',
    title: 'Continent',
    table: 'CountryPopulation',
    column: 'Continent',
    merged: false,
    indexed: true,
  },
  {
    id: '[CountryPopulation.Country Code]',
    type: 'dimension',
    dimtype: 'text',
    title: 'Country Code',
    table: 'CountryPopulation',
    column: 'Country Code',
    merged: false,
    indexed: true,
  },
  {
    id: '[CountryPopulation.Country Name]',
    type: 'dimension',
    dimtype: 'text',
    title: 'Country Name',
    table: 'CountryPopulation',
    column: 'Country Name',
    merged: true,
    indexed: true,
  },
  {
    id: '[CountryPopulation.Population]',
    type: 'dimension',
    dimtype: 'numeric',
    title: 'Population',
    table: 'CountryPopulation',
    column: 'Population',
    merged: false,
    indexed: false,
  },
];
