export const fieldsOrdersDB = {
  name: 'OrdersDB',
  dataSource: 'OrdersDB',
  metadata: [
    {
      id: '[BenchmarkCustomer.Cohort Name]',
      type: 'dimension',
      dimtype: 'text',
      title: 'Cohort Name',
      table: 'BenchmarkCustomer',
      column: 'Cohort Name',
      merged: false,
      indexed: true,
    },
    {
      id: '[BenchmarkCustomer.Company]',
      type: 'dimension',
      dimtype: 'text',
      title: 'Company',
      table: 'BenchmarkCustomer',
      column: 'Company',
      merged: false,
      indexed: true,
    },
    {
      id: '[BenchmarkCustomer.Member Type]',
      type: 'dimension',
      dimtype: 'text',
      title: 'Member Type',
      table: 'BenchmarkCustomer',
      column: 'Member Type',
      merged: false,
      indexed: true,
    },
    {
      id: '[BenchmarkCustomer.Peer CompanyID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'Peer CompanyID',
      table: 'BenchmarkCustomer',
      column: 'Peer CompanyID',
      merged: true,
      indexed: false,
    },
    {
      id: '[CATEGORIES1.Category Name Ordered]',
      type: 'dimension',
      dimtype: 'text',
      title: 'Category Name Ordered',
      table: 'CATEGORIES1',
      column: 'Category Name Ordered',
      merged: false,
      indexed: true,
    },
    {
      id: '[CATEGORIES1.CATEGORY_ID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'CATEGORY_ID',
      table: 'CATEGORIES1',
      column: 'CATEGORY_ID',
      merged: true,
      indexed: false,
    },
    {
      id: '[CATEGORIES1.CATEGORY_NAME]',
      type: 'dimension',
      dimtype: 'text',
      title: 'CATEGORY_NAME',
      table: 'CATEGORIES1',
      column: 'CATEGORY_NAME',
      merged: false,
      indexed: true,
    },
    {
      id: '[CUSTOMERS1.ADDRESS]',
      type: 'dimension',
      dimtype: 'text',
      title: 'ADDRESS',
      table: 'CUSTOMERS1',
      column: 'ADDRESS',
      merged: false,
      indexed: true,
    },
    {
      id: '[CUSTOMERS1.CITY]',
      type: 'dimension',
      dimtype: 'text',
      title: 'CITY',
      table: 'CUSTOMERS1',
      column: 'CITY',
      merged: false,
      indexed: true,
    },
    {
      id: '[CUSTOMERS1.COMPANY_NAME]',
      type: 'dimension',
      dimtype: 'text',
      title: 'COMPANY_NAME',
      table: 'CUSTOMERS1',
      column: 'COMPANY_NAME',
      merged: false,
      indexed: true,
    },
    {
      id: '[CUSTOMERS1.CUSTOMER_ID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'CUSTOMER_ID',
      table: 'CUSTOMERS1',
      column: 'CUSTOMER_ID',
      merged: true,
      indexed: false,
    },
    {
      id: '[CUSTOMERS1.Industry]',
      type: 'dimension',
      dimtype: 'text',
      title: 'Industry',
      table: 'CUSTOMERS1',
      column: 'Industry',
      merged: false,
      indexed: true,
    },
    {
      id: '[CUSTOMERS1.INDUSTRY0]',
      type: 'dimension',
      dimtype: 'text',
      title: 'INDUSTRY0',
      table: 'CUSTOMERS1',
      column: 'INDUSTRY0',
      merged: false,
      indexed: true,
    },
    {
      id: '[CUSTOMERS1.Region]',
      type: 'dimension',
      dimtype: 'text',
      title: 'Region',
      table: 'CUSTOMERS1',
      column: 'Region',
      merged: false,
      indexed: true,
    },
    {
      id: '[CUSTOMERS1.REGION_ID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'REGION_ID',
      table: 'CUSTOMERS1',
      column: 'REGION_ID',
      merged: false,
      indexed: false,
    },
    {
      id: '[CUSTOMERS1.RESELLER]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'RESELLER',
      table: 'CUSTOMERS1',
      column: 'RESELLER',
      merged: false,
      indexed: false,
    },
    {
      id: '[CUSTOMERS1.STATE]',
      type: 'dimension',
      dimtype: 'text',
      title: 'STATE',
      table: 'CUSTOMERS1',
      column: 'STATE',
      merged: false,
      indexed: true,
    },
    {
      id: '[CUSTOMERS1.ZIP]',
      type: 'dimension',
      dimtype: 'text',
      title: 'ZIP',
      table: 'CUSTOMERS1',
      column: 'ZIP',
      merged: true,
      indexed: true,
    },
    {
      id: '[Employee Benchmark.Color Flag]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'Color Flag',
      table: 'Employee Benchmark',
      column: 'Color Flag',
      merged: false,
      indexed: false,
    },
    {
      id: '[Employee Benchmark.EmpID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'EmpID',
      table: 'Employee Benchmark',
      column: 'EmpID',
      merged: false,
      indexed: false,
    },
    {
      id: '[Employee Benchmark.EmpIDPeer]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'EmpIDPeer',
      table: 'Employee Benchmark',
      column: 'EmpIDPeer',
      merged: true,
      indexed: false,
    },
    {
      id: '[Employee Benchmark.Employee Display]',
      type: 'dimension',
      dimtype: 'text',
      title: 'Employee Display',
      table: 'Employee Benchmark',
      column: 'Employee Display',
      merged: false,
      indexed: true,
    },
    {
      id: '[Employee Benchmark.Employee Mask]',
      type: 'dimension',
      dimtype: 'text',
      title: 'Employee Mask',
      table: 'Employee Benchmark',
      column: 'Employee Mask',
      merged: false,
      indexed: true,
    },
    {
      id: '[Employee Benchmark.Employee Name]',
      type: 'dimension',
      dimtype: 'text',
      title: 'Employee Name',
      table: 'Employee Benchmark',
      column: 'Employee Name',
      merged: false,
      indexed: true,
    },
    {
      id: '[Employee Benchmark.Level]',
      type: 'dimension',
      dimtype: 'text',
      title: 'Level',
      table: 'Employee Benchmark',
      column: 'Level',
      merged: false,
      indexed: true,
    },
    {
      id: '[First OrderDate.CID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'CID',
      table: 'First OrderDate',
      column: 'CID',
      merged: true,
      indexed: false,
    },
    {
      id: '[First OrderDate.First Flag]',
      type: 'dimension',
      dimtype: 'text',
      title: 'First Flag',
      table: 'First OrderDate',
      column: 'First Flag',
      merged: false,
      indexed: true,
    },
    {
      id: '[First OrderDate.ODate (Calendar)]',
      type: 'dimension',
      dimtype: 'datetime',
      title: 'ODate',
      table: 'First OrderDate',
      column: 'ODate',
      merged: false,
      indexed: true,
    },
    {
      id: '[ORDER_DETAILS1.Amount]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'Amount',
      table: 'ORDER_DETAILS1',
      column: 'Amount',
      merged: false,
      indexed: false,
    },
    {
      id: '[ORDER_DETAILS1.ORDER_ID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'ORDER_ID',
      table: 'ORDER_DETAILS1',
      column: 'ORDER_ID',
      merged: true,
      indexed: false,
    },
    {
      id: '[ORDER_DETAILS1.PRODUCT_ID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'PRODUCT_ID',
      table: 'ORDER_DETAILS1',
      column: 'PRODUCT_ID',
      merged: true,
      indexed: false,
    },
    {
      id: '[ORDER_DETAILS1.QUANTITY]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'QUANTITY',
      table: 'ORDER_DETAILS1',
      column: 'QUANTITY',
      merged: false,
      indexed: false,
    },
    {
      id: '[OrderRollup.Amount2]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'Amount2',
      table: 'OrderRollup',
      column: 'Amount2',
      merged: false,
      indexed: false,
    },
    {
      id: '[OrderRollup.ORDER_ID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'ORDER_ID',
      table: 'OrderRollup',
      column: 'ORDER_ID',
      merged: true,
      indexed: false,
    },
    {
      id: '[ORDERS1.Current Month]',
      type: 'dimension',
      dimtype: 'text',
      title: 'Current Month',
      table: 'ORDERS1',
      column: 'Current Month',
      merged: false,
      indexed: true,
    },
    {
      id: '[ORDERS1.Current QTR]',
      type: 'dimension',
      dimtype: 'text',
      title: 'Current QTR',
      table: 'ORDERS1',
      column: 'Current QTR',
      merged: false,
      indexed: true,
    },
    {
      id: '[ORDERS1.CUSTOMER_ID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'CUSTOMER_ID',
      table: 'ORDERS1',
      column: 'CUSTOMER_ID',
      merged: true,
      indexed: false,
    },
    {
      id: '[ORDERS1.CustomerRank]',
      type: 'dimension',
      dimtype: 'text',
      title: 'CustomerRank',
      table: 'ORDERS1',
      column: 'CustomerRank',
      merged: false,
      indexed: true,
    },
    {
      id: '[ORDERS1.CustomerRankPrev]',
      type: 'dimension',
      dimtype: 'text',
      title: 'CustomerRankPrev',
      table: 'ORDERS1',
      column: 'CustomerRankPrev',
      merged: false,
      indexed: true,
    },
    {
      id: '[ORDERS1.DateInt]',
      type: 'dimension',
      dimtype: 'text',
      title: 'DateInt',
      table: 'ORDERS1',
      column: 'DateInt',
      merged: false,
      indexed: true,
    },
    {
      id: '[ORDERS1.DateRank]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'DateRank',
      table: 'ORDERS1',
      column: 'DateRank',
      merged: false,
      indexed: false,
    },
    {
      id: '[ORDERS1.DateRankPrev]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'DateRankPrev',
      table: 'ORDERS1',
      column: 'DateRankPrev',
      merged: false,
      indexed: false,
    },
    {
      id: '[ORDERS1.Day Of Week (Calendar)]',
      type: 'dimension',
      dimtype: 'datetime',
      title: 'Day Of Week',
      table: 'ORDERS1',
      column: 'Day Of Week',
      merged: false,
      indexed: true,
    },
    {
      id: '[ORDERS1.Description]',
      type: 'dimension',
      dimtype: 'text',
      title: 'Description',
      table: 'ORDERS1',
      column: 'Description',
      merged: false,
      indexed: true,
    },
    {
      id: '[ORDERS1.DISCOUNT]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'DISCOUNT',
      table: 'ORDERS1',
      column: 'DISCOUNT',
      merged: false,
      indexed: false,
    },
    {
      id: '[ORDERS1.EMPLOYEE_ID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'EMPLOYEE_ID',
      table: 'ORDERS1',
      column: 'EMPLOYEE_ID',
      merged: true,
      indexed: false,
    },
    {
      id: '[ORDERS1.EMPQTR]',
      type: 'dimension',
      dimtype: 'text',
      title: 'EMPQTR',
      table: 'ORDERS1',
      column: 'EMPQTR',
      merged: true,
      indexed: true,
    },
    {
      id: '[ORDERS1.HOD EST]',
      type: 'dimension',
      dimtype: 'text',
      title: 'HOD EST',
      table: 'ORDERS1',
      column: 'HOD EST',
      merged: false,
      indexed: true,
    },
    {
      id: '[ORDERS1.HOD PST]',
      type: 'dimension',
      dimtype: 'text',
      title: 'HOD PST',
      table: 'ORDERS1',
      column: 'HOD PST',
      merged: false,
      indexed: true,
    },
    {
      id: '[ORDERS1.ModTS]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'ModTS',
      table: 'ORDERS1',
      column: 'ModTS',
      merged: false,
      indexed: false,
    },
    {
      id: '[ORDERS1.MontOfYear (Calendar)]',
      type: 'dimension',
      dimtype: 'datetime',
      title: 'MontOfYear',
      table: 'ORDERS1',
      column: 'MontOfYear',
      merged: false,
      indexed: true,
    },
    {
      id: '[ORDERS1.Order Date (Calendar)]',
      type: 'dimension',
      dimtype: 'datetime',
      title: 'Order Date',
      table: 'ORDERS1',
      column: 'Order Date',
      merged: false,
      indexed: true,
    },
    {
      id: '[ORDERS1.Order Date String]',
      type: 'dimension',
      dimtype: 'text',
      title: 'Order Date String',
      table: 'ORDERS1',
      column: 'Order Date String',
      merged: false,
      indexed: true,
    },
    {
      id: '[ORDERS1.Order Flag]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'Order Flag',
      table: 'ORDERS1',
      column: 'Order Flag',
      merged: false,
      indexed: false,
    },
    {
      id: '[ORDERS1.Order Time Hrs]',
      type: 'dimension',
      dimtype: 'text',
      title: 'Order Time Hrs',
      table: 'ORDERS1',
      column: 'Order Time Hrs',
      merged: false,
      indexed: true,
    },
    {
      id: '[ORDERS1.Order Timestamp (Calendar)]',
      type: 'dimension',
      dimtype: 'datetime',
      title: 'Order Timestamp',
      table: 'ORDERS1',
      column: 'Order Timestamp',
      merged: false,
      indexed: true,
    },
    {
      id: '[ORDERS1.ORDER_ID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'ORDER_ID',
      table: 'ORDERS1',
      column: 'ORDER_ID',
      merged: true,
      indexed: false,
    },
    {
      id: '[ORDERS1.OrderDayDiff]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'OrderDayDiff',
      table: 'ORDERS1',
      column: 'OrderDayDiff',
      merged: false,
      indexed: false,
    },
    {
      id: '[ORDERS1.PAID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'PAID',
      table: 'ORDERS1',
      column: 'PAID',
      merged: false,
      indexed: false,
    },
    {
      id: '[ORDERS1.QTR]',
      type: 'dimension',
      dimtype: 'text',
      title: 'QTR',
      table: 'ORDERS1',
      column: 'QTR',
      merged: false,
      indexed: true,
    },
    {
      id: '[ORDERS1.QTRNum]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'QTRNum',
      table: 'ORDERS1',
      column: 'QTRNum',
      merged: false,
      indexed: false,
    },
    {
      id: '[ORDERS1.Rank]',
      type: 'dimension',
      dimtype: 'text',
      title: 'Rank',
      table: 'ORDERS1',
      column: 'Rank',
      merged: false,
      indexed: true,
    },
    {
      id: '[ORDERS1.Shipping Fee]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'Shipping Fee',
      table: 'ORDERS1',
      column: 'Shipping Fee',
      merged: false,
      indexed: false,
    },
    {
      id: '[ORDERS1.Status]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'Status',
      table: 'ORDERS1',
      column: 'Status',
      merged: false,
      indexed: false,
    },
    {
      id: '[ORDERS1.Title]',
      type: 'dimension',
      dimtype: 'text',
      title: 'Title',
      table: 'ORDERS1',
      column: 'Title',
      merged: false,
      indexed: true,
    },
    {
      id: '[ORDERS1.Type]',
      type: 'dimension',
      dimtype: 'text',
      title: 'Type',
      table: 'ORDERS1',
      column: 'Type',
      merged: false,
      indexed: true,
    },
    {
      id: '[ORDERS1.UTS]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'UTS',
      table: 'ORDERS1',
      column: 'UTS',
      merged: false,
      indexed: false,
    },
    {
      id: '[ORDERS1.UTS Days]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'UTS Days',
      table: 'ORDERS1',
      column: 'UTS Days',
      merged: false,
      indexed: false,
    },
    {
      id: '[ORDERS1.YTDFlag]',
      type: 'dimension',
      dimtype: 'text',
      title: 'YTDFlag',
      table: 'ORDERS1',
      column: 'YTDFlag',
      merged: false,
      indexed: true,
    },
    {
      id: '[Parameters.DiscountParam]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'DiscountParam',
      table: 'Parameters',
      column: 'DiscountParam',
      merged: false,
      indexed: false,
    },
    {
      id: '[Parameters.PriceParam]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'PriceParam',
      table: 'Parameters',
      column: 'PriceParam',
      merged: false,
      indexed: false,
    },
    {
      id: '[PRODUCTS1.CATEGORY_ID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'CATEGORY_ID',
      table: 'PRODUCTS1',
      column: 'CATEGORY_ID',
      merged: true,
      indexed: false,
    },
    {
      id: '[PRODUCTS1.DESCRIPTION]',
      type: 'dimension',
      dimtype: 'text',
      title: 'DESCRIPTION',
      table: 'PRODUCTS1',
      column: 'DESCRIPTION',
      merged: false,
      indexed: true,
    },
    {
      id: '[PRODUCTS1.NUMBER_INSTOCK]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'NUMBER_INSTOCK',
      table: 'PRODUCTS1',
      column: 'NUMBER_INSTOCK',
      merged: false,
      indexed: false,
    },
    {
      id: '[PRODUCTS1.PRICE]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'PRICE',
      table: 'PRODUCTS1',
      column: 'PRICE',
      merged: false,
      indexed: false,
    },
    {
      id: '[PRODUCTS1.PRODUCT_ID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'PRODUCT_ID',
      table: 'PRODUCTS1',
      column: 'PRODUCT_ID',
      merged: true,
      indexed: false,
    },
    {
      id: '[PRODUCTS1.PRODUCT_NAME]',
      type: 'dimension',
      dimtype: 'text',
      title: 'PRODUCT_NAME',
      table: 'PRODUCTS1',
      column: 'PRODUCT_NAME',
      merged: false,
      indexed: true,
    },
    {
      id: '[PRODUCTS1.REORDER_LEVEL]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'REORDER_LEVEL',
      table: 'PRODUCTS1',
      column: 'REORDER_LEVEL',
      merged: false,
      indexed: false,
    },
    {
      id: '[PRODUCTS1.SUPPLIER_ID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'SUPPLIER_ID',
      table: 'PRODUCTS1',
      column: 'SUPPLIER_ID',
      merged: false,
      indexed: false,
    },
    {
      id: '[QTRSales.Amount]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'Amount',
      table: 'QTRSales',
      column: 'Amount',
      merged: false,
      indexed: false,
    },
    {
      id: '[QTRSales.EMPLOYEE_ID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'EMPLOYEE_ID',
      table: 'QTRSales',
      column: 'EMPLOYEE_ID',
      merged: false,
      indexed: false,
    },
    {
      id: '[QTRSales.QTRNum]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'QTRNum',
      table: 'QTRSales',
      column: 'QTRNum',
      merged: false,
      indexed: false,
    },
    {
      id: '[SALES_EMPLOYEES1.EMP_LEVEL]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'EMP_LEVEL',
      table: 'SALES_EMPLOYEES1',
      column: 'EMP_LEVEL',
      merged: false,
      indexed: false,
    },
    {
      id: '[SALES_EMPLOYEES1.Employee Mask]',
      type: 'dimension',
      dimtype: 'text',
      title: 'Employee Mask',
      table: 'SALES_EMPLOYEES1',
      column: 'Employee Mask',
      merged: false,
      indexed: true,
    },
    {
      id: '[SALES_EMPLOYEES1.Employee Name]',
      type: 'dimension',
      dimtype: 'text',
      title: 'Employee Name',
      table: 'SALES_EMPLOYEES1',
      column: 'Employee Name',
      merged: false,
      indexed: true,
    },
    {
      id: '[SALES_EMPLOYEES1.Employee Type]',
      type: 'dimension',
      dimtype: 'text',
      title: 'Employee Type',
      table: 'SALES_EMPLOYEES1',
      column: 'Employee Type',
      merged: false,
      indexed: true,
    },
    {
      id: '[SALES_EMPLOYEES1.EMPLOYEE_ID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'EMPLOYEE_ID',
      table: 'SALES_EMPLOYEES1',
      column: 'EMPLOYEE_ID',
      merged: true,
      indexed: false,
    },
    {
      id: '[SALES_EMPLOYEES1.FIRST_NAME]',
      type: 'dimension',
      dimtype: 'text',
      title: 'FIRST_NAME',
      table: 'SALES_EMPLOYEES1',
      column: 'FIRST_NAME',
      merged: false,
      indexed: true,
    },
    {
      id: '[SALES_EMPLOYEES1.LAST_NAME]',
      type: 'dimension',
      dimtype: 'text',
      title: 'LAST_NAME',
      table: 'SALES_EMPLOYEES1',
      column: 'LAST_NAME',
      merged: false,
      indexed: true,
    },
    {
      id: '[SALES_EMPLOYEES1.MANAGER_ID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'MANAGER_ID',
      table: 'SALES_EMPLOYEES1',
      column: 'MANAGER_ID',
      merged: false,
      indexed: false,
    },
    {
      id: '[SALES_EMPLOYEES1.QUOTA]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'QUOTA',
      table: 'SALES_EMPLOYEES1',
      column: 'QUOTA',
      merged: false,
      indexed: false,
    },
    {
      id: '[SALES_EMPLOYEES1.REGION_ID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'REGION_ID',
      table: 'SALES_EMPLOYEES1',
      column: 'REGION_ID',
      merged: false,
      indexed: false,
    },
    {
      id: '[SalesTarget.EmpID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'EmpID',
      table: 'SalesTarget',
      column: 'EmpID',
      merged: false,
      indexed: false,
    },
    {
      id: '[SalesTarget.EmpQTR]',
      type: 'dimension',
      dimtype: 'text',
      title: 'EmpQTR',
      table: 'SalesTarget',
      column: 'EmpQTR',
      merged: true,
      indexed: true,
    },
    {
      id: '[SalesTarget.QTRNum]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'QTRNum',
      table: 'SalesTarget',
      column: 'QTRNum',
      merged: false,
      indexed: false,
    },
    {
      id: '[SalesTarget.Quota]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'Quota',
      table: 'SalesTarget',
      column: 'Quota',
      merged: false,
      indexed: false,
    },
    {
      id: '[SalesTarget.Seed]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'Seed',
      table: 'SalesTarget',
      column: 'Seed',
      merged: false,
      indexed: false,
    },
    {
      id: '[SalesTarget.Target]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'Target',
      table: 'SalesTarget',
      column: 'Target',
      merged: false,
      indexed: false,
    },
    {
      id: '[us_zipcodes.latitude]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'latitude',
      table: 'us_zipcodes',
      column: 'latitude',
      merged: false,
      indexed: false,
    },
    {
      id: '[us_zipcodes.longitude]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'longitude',
      table: 'us_zipcodes',
      column: 'longitude',
      merged: false,
      indexed: false,
    },
    {
      id: '[us_zipcodes.primary_city]',
      type: 'dimension',
      dimtype: 'text',
      title: 'primary_city',
      table: 'us_zipcodes',
      column: 'primary_city',
      merged: false,
      indexed: true,
    },
    {
      id: '[us_zipcodes.state]',
      type: 'dimension',
      dimtype: 'text',
      title: 'state',
      table: 'us_zipcodes',
      column: 'state',
      merged: false,
      indexed: true,
    },
    {
      id: '[us_zipcodes.zip]',
      type: 'dimension',
      dimtype: 'text',
      title: 'zip',
      table: 'us_zipcodes',
      column: 'zip',
      merged: true,
      indexed: true,
    },
  ],
};

export const dimensionalModelOrdersDB = {
  name: 'OrdersDB',
  dataSource: 'OrdersDB',
  metadata: [
    {
      attributes: [
        {
          expression: '[BenchmarkCustomer.Cohort Name]',
          name: 'Cohort Name',
          type: 'text-attribute',
        },
        {
          expression: '[BenchmarkCustomer.Company]',
          name: 'Company',
          type: 'text-attribute',
        },
        {
          expression: '[BenchmarkCustomer.Member Type]',
          name: 'Member Type',
          type: 'text-attribute',
        },
        {
          expression: '[BenchmarkCustomer.Peer CompanyID]',
          name: 'Peer CompanyID',
          type: 'numeric-attribute',
        },
      ],
      dimensions: [],
      name: 'BenchmarkCustomer',
      type: 'dimension',
    },
    {
      attributes: [
        {
          expression: '[CATEGORIES1.Category Name Ordered]',
          name: 'Category Name Ordered',
          type: 'text-attribute',
        },
        {
          expression: '[CATEGORIES1.CATEGORY_ID]',
          name: 'CATEGORY_ID',
          type: 'numeric-attribute',
        },
        {
          expression: '[CATEGORIES1.CATEGORY_NAME]',
          name: 'CATEGORY_NAME',
          type: 'text-attribute',
        },
      ],
      dimensions: [],
      name: 'CATEGORIES1',
      type: 'dimension',
    },
    {
      attributes: [
        {
          expression: '[CUSTOMERS1.ADDRESS]',
          name: 'ADDRESS',
          type: 'text-attribute',
        },
        {
          expression: '[CUSTOMERS1.CITY]',
          name: 'CITY',
          type: 'text-attribute',
        },
        {
          expression: '[CUSTOMERS1.COMPANY_NAME]',
          name: 'COMPANY_NAME',
          type: 'text-attribute',
        },
        {
          expression: '[CUSTOMERS1.CUSTOMER_ID]',
          name: 'CUSTOMER_ID',
          type: 'numeric-attribute',
        },
        {
          expression: '[CUSTOMERS1.Industry]',
          name: 'Industry',
          type: 'text-attribute',
        },
        {
          expression: '[CUSTOMERS1.INDUSTRY0]',
          name: 'INDUSTRY0',
          type: 'text-attribute',
        },
        {
          expression: '[CUSTOMERS1.Region]',
          name: 'Region',
          type: 'text-attribute',
        },
        {
          expression: '[CUSTOMERS1.REGION_ID]',
          name: 'REGION_ID',
          type: 'numeric-attribute',
        },
        {
          expression: '[CUSTOMERS1.RESELLER]',
          name: 'RESELLER',
          type: 'numeric-attribute',
        },
        {
          expression: '[CUSTOMERS1.STATE]',
          name: 'STATE',
          type: 'text-attribute',
        },
        {
          expression: '[CUSTOMERS1.ZIP]',
          name: 'ZIP',
          type: 'text-attribute',
        },
      ],
      dimensions: [],
      name: 'CUSTOMERS1',
      type: 'dimension',
    },
    {
      attributes: [
        {
          expression: '[Employee Benchmark.Color Flag]',
          name: 'Color Flag',
          type: 'numeric-attribute',
        },
        {
          expression: '[Employee Benchmark.EmpID]',
          name: 'EmpID',
          type: 'numeric-attribute',
        },
        {
          expression: '[Employee Benchmark.EmpIDPeer]',
          name: 'EmpIDPeer',
          type: 'numeric-attribute',
        },
        {
          expression: '[Employee Benchmark.Employee Display]',
          name: 'Employee Display',
          type: 'text-attribute',
        },
        {
          expression: '[Employee Benchmark.Employee Mask]',
          name: 'Employee Mask',
          type: 'text-attribute',
        },
        {
          expression: '[Employee Benchmark.Employee Name]',
          name: 'Employee Name',
          type: 'text-attribute',
        },
        {
          expression: '[Employee Benchmark.Level]',
          name: 'Level',
          type: 'text-attribute',
        },
      ],
      dimensions: [],
      name: 'Employee Benchmark',
      type: 'dimension',
    },
    {
      attributes: [
        {
          expression: '[First OrderDate.CID]',
          name: 'CID',
          type: 'numeric-attribute',
        },
        {
          expression: '[First OrderDate.First Flag]',
          name: 'First Flag',
          type: 'text-attribute',
        },
      ],
      dimensions: [
        {
          expression: '[First OrderDate.ODate (Calendar)]',
          name: 'ODate',
          type: 'datedimension',
        },
      ],
      name: 'First OrderDate',
      type: 'dimension',
    },
    {
      attributes: [
        {
          expression: '[ORDER_DETAILS1.Amount]',
          name: 'Amount',
          type: 'numeric-attribute',
        },
        {
          expression: '[ORDER_DETAILS1.ORDER_ID]',
          name: 'ORDER_ID',
          type: 'numeric-attribute',
        },
        {
          expression: '[ORDER_DETAILS1.PRODUCT_ID]',
          name: 'PRODUCT_ID',
          type: 'numeric-attribute',
        },
        {
          expression: '[ORDER_DETAILS1.QUANTITY]',
          name: 'QUANTITY',
          type: 'numeric-attribute',
        },
      ],
      dimensions: [],
      name: 'ORDER_DETAILS1',
      type: 'dimension',
    },
    {
      attributes: [
        {
          expression: '[OrderRollup.Amount2]',
          name: 'Amount2',
          type: 'numeric-attribute',
        },
        {
          expression: '[OrderRollup.ORDER_ID]',
          name: 'ORDER_ID',
          type: 'numeric-attribute',
        },
      ],
      dimensions: [],
      name: 'OrderRollup',
      type: 'dimension',
    },
    {
      attributes: [
        {
          expression: '[ORDERS1.Current Month]',
          name: 'Current Month',
          type: 'text-attribute',
        },
        {
          expression: '[ORDERS1.Current QTR]',
          name: 'Current QTR',
          type: 'text-attribute',
        },
        {
          expression: '[ORDERS1.CUSTOMER_ID]',
          name: 'CUSTOMER_ID',
          type: 'numeric-attribute',
        },
        {
          expression: '[ORDERS1.CustomerRank]',
          name: 'CustomerRank',
          type: 'text-attribute',
        },
        {
          expression: '[ORDERS1.CustomerRankPrev]',
          name: 'CustomerRankPrev',
          type: 'text-attribute',
        },
        {
          expression: '[ORDERS1.DateInt]',
          name: 'DateInt',
          type: 'text-attribute',
        },
        {
          expression: '[ORDERS1.DateRank]',
          name: 'DateRank',
          type: 'numeric-attribute',
        },
        {
          expression: '[ORDERS1.DateRankPrev]',
          name: 'DateRankPrev',
          type: 'numeric-attribute',
        },
        {
          expression: '[ORDERS1.Description]',
          name: 'Description',
          type: 'text-attribute',
        },
        {
          expression: '[ORDERS1.DISCOUNT]',
          name: 'DISCOUNT',
          type: 'numeric-attribute',
        },
        {
          expression: '[ORDERS1.EMPLOYEE_ID]',
          name: 'EMPLOYEE_ID',
          type: 'numeric-attribute',
        },
        {
          expression: '[ORDERS1.EMPQTR]',
          name: 'EMPQTR',
          type: 'text-attribute',
        },
        {
          expression: '[ORDERS1.HOD EST]',
          name: 'HOD EST',
          type: 'text-attribute',
        },
        {
          expression: '[ORDERS1.HOD PST]',
          name: 'HOD PST',
          type: 'text-attribute',
        },
        {
          expression: '[ORDERS1.ModTS]',
          name: 'ModTS',
          type: 'numeric-attribute',
        },
        {
          expression: '[ORDERS1.Order Date String]',
          name: 'Order Date String',
          type: 'text-attribute',
        },
        {
          expression: '[ORDERS1.Order Flag]',
          name: 'Order Flag',
          type: 'numeric-attribute',
        },
        {
          expression: '[ORDERS1.Order Time Hrs]',
          name: 'Order Time Hrs',
          type: 'text-attribute',
        },
        {
          expression: '[ORDERS1.ORDER_ID]',
          name: 'ORDER_ID',
          type: 'numeric-attribute',
        },
        {
          expression: '[ORDERS1.OrderDayDiff]',
          name: 'OrderDayDiff',
          type: 'numeric-attribute',
        },
        {
          expression: '[ORDERS1.PAID]',
          name: 'PAID',
          type: 'numeric-attribute',
        },
        {
          expression: '[ORDERS1.QTR]',
          name: 'QTR',
          type: 'text-attribute',
        },
        {
          expression: '[ORDERS1.QTRNum]',
          name: 'QTRNum',
          type: 'numeric-attribute',
        },
        {
          expression: '[ORDERS1.Rank]',
          name: 'Rank',
          type: 'text-attribute',
        },
        {
          expression: '[ORDERS1.Shipping Fee]',
          name: 'Shipping Fee',
          type: 'numeric-attribute',
        },
        {
          expression: '[ORDERS1.Status]',
          name: 'Status',
          type: 'numeric-attribute',
        },
        {
          expression: '[ORDERS1.Title]',
          name: 'Title',
          type: 'text-attribute',
        },
        {
          expression: '[ORDERS1.Type]',
          name: 'Type',
          type: 'text-attribute',
        },
        {
          expression: '[ORDERS1.UTS]',
          name: 'UTS',
          type: 'numeric-attribute',
        },
        {
          expression: '[ORDERS1.UTS Days]',
          name: 'UTS Days',
          type: 'numeric-attribute',
        },
        {
          expression: '[ORDERS1.YTDFlag]',
          name: 'YTDFlag',
          type: 'text-attribute',
        },
      ],
      dimensions: [
        {
          expression: '[ORDERS1.Day Of Week (Calendar)]',
          name: 'Day Of Week',
          type: 'datedimension',
        },
        {
          expression: '[ORDERS1.MontOfYear (Calendar)]',
          name: 'MontOfYear',
          type: 'datedimension',
        },
        {
          expression: '[ORDERS1.Order Date (Calendar)]',
          name: 'Order Date',
          type: 'datedimension',
        },
        {
          expression: '[ORDERS1.Order Timestamp (Calendar)]',
          name: 'Order Timestamp',
          type: 'datedimension',
        },
      ],
      name: 'ORDERS1',
      type: 'dimension',
    },
    {
      attributes: [
        {
          expression: '[Parameters.DiscountParam]',
          name: 'DiscountParam',
          type: 'numeric-attribute',
        },
        {
          expression: '[Parameters.PriceParam]',
          name: 'PriceParam',
          type: 'numeric-attribute',
        },
      ],
      dimensions: [],
      name: 'Parameters',
      type: 'dimension',
    },
    {
      attributes: [
        {
          expression: '[PRODUCTS1.CATEGORY_ID]',
          name: 'CATEGORY_ID',
          type: 'numeric-attribute',
        },
        {
          expression: '[PRODUCTS1.DESCRIPTION]',
          name: 'DESCRIPTION',
          type: 'text-attribute',
        },
        {
          expression: '[PRODUCTS1.NUMBER_INSTOCK]',
          name: 'NUMBER_INSTOCK',
          type: 'numeric-attribute',
        },
        {
          expression: '[PRODUCTS1.PRICE]',
          name: 'PRICE',
          type: 'numeric-attribute',
        },
        {
          expression: '[PRODUCTS1.PRODUCT_ID]',
          name: 'PRODUCT_ID',
          type: 'numeric-attribute',
        },
        {
          expression: '[PRODUCTS1.PRODUCT_NAME]',
          name: 'PRODUCT_NAME',
          type: 'text-attribute',
        },
        {
          expression: '[PRODUCTS1.REORDER_LEVEL]',
          name: 'REORDER_LEVEL',
          type: 'numeric-attribute',
        },
        {
          expression: '[PRODUCTS1.SUPPLIER_ID]',
          name: 'SUPPLIER_ID',
          type: 'numeric-attribute',
        },
      ],
      dimensions: [],
      name: 'PRODUCTS1',
      type: 'dimension',
    },
    {
      attributes: [
        {
          expression: '[QTRSales.Amount]',
          name: 'Amount',
          type: 'numeric-attribute',
        },
        {
          expression: '[QTRSales.EMPLOYEE_ID]',
          name: 'EMPLOYEE_ID',
          type: 'numeric-attribute',
        },
        {
          expression: '[QTRSales.QTRNum]',
          name: 'QTRNum',
          type: 'numeric-attribute',
        },
      ],
      dimensions: [],
      name: 'QTRSales',
      type: 'dimension',
    },
    {
      attributes: [
        {
          expression: '[SALES_EMPLOYEES1.EMP_LEVEL]',
          name: 'EMP_LEVEL',
          type: 'numeric-attribute',
        },
        {
          expression: '[SALES_EMPLOYEES1.Employee Mask]',
          name: 'Employee Mask',
          type: 'text-attribute',
        },
        {
          expression: '[SALES_EMPLOYEES1.Employee Name]',
          name: 'Employee Name',
          type: 'text-attribute',
        },
        {
          expression: '[SALES_EMPLOYEES1.Employee Type]',
          name: 'Employee Type',
          type: 'text-attribute',
        },
        {
          expression: '[SALES_EMPLOYEES1.EMPLOYEE_ID]',
          name: 'EMPLOYEE_ID',
          type: 'numeric-attribute',
        },
        {
          expression: '[SALES_EMPLOYEES1.FIRST_NAME]',
          name: 'FIRST_NAME',
          type: 'text-attribute',
        },
        {
          expression: '[SALES_EMPLOYEES1.LAST_NAME]',
          name: 'LAST_NAME',
          type: 'text-attribute',
        },
        {
          expression: '[SALES_EMPLOYEES1.MANAGER_ID]',
          name: 'MANAGER_ID',
          type: 'numeric-attribute',
        },
        {
          expression: '[SALES_EMPLOYEES1.QUOTA]',
          name: 'QUOTA',
          type: 'numeric-attribute',
        },
        {
          expression: '[SALES_EMPLOYEES1.REGION_ID]',
          name: 'REGION_ID',
          type: 'numeric-attribute',
        },
      ],
      dimensions: [],
      name: 'SALES_EMPLOYEES1',
      type: 'dimension',
    },
    {
      attributes: [
        {
          expression: '[SalesTarget.EmpID]',
          name: 'EmpID',
          type: 'numeric-attribute',
        },
        {
          expression: '[SalesTarget.EmpQTR]',
          name: 'EmpQTR',
          type: 'text-attribute',
        },
        {
          expression: '[SalesTarget.QTRNum]',
          name: 'QTRNum',
          type: 'numeric-attribute',
        },
        {
          expression: '[SalesTarget.Quota]',
          name: 'Quota',
          type: 'numeric-attribute',
        },
        {
          expression: '[SalesTarget.Seed]',
          name: 'Seed',
          type: 'numeric-attribute',
        },
        {
          expression: '[SalesTarget.Target]',
          name: 'Target',
          type: 'numeric-attribute',
        },
      ],
      dimensions: [],
      name: 'SalesTarget',
      type: 'dimension',
    },
    {
      attributes: [
        {
          expression: '[us_zipcodes.latitude]',
          name: 'latitude',
          type: 'numeric-attribute',
        },
        {
          expression: '[us_zipcodes.longitude]',
          name: 'longitude',
          type: 'numeric-attribute',
        },
        {
          expression: '[us_zipcodes.primary_city]',
          name: 'primary_city',
          type: 'text-attribute',
        },
        {
          expression: '[us_zipcodes.state]',
          name: 'state',
          type: 'text-attribute',
        },
        {
          expression: '[us_zipcodes.zip]',
          name: 'zip',
          type: 'text-attribute',
        },
      ],
      dimensions: [],
      name: 'us_zipcodes',
      type: 'dimension',
    },
  ],
};
