export const fieldsECommerce = {
  name: 'Sample ECommerce',
  dataSource: 'Sample ECommerce',
  metadata: [
    {
      id: '[Brand.Brand]',
      type: 'dimension',
      dimtype: 'text',
      title: 'Brand',
      table: 'Brand',
      column: 'Brand',
      merged: false,
      indexed: true,
    },
    {
      id: '[Brand.Brand ID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'Brand ID',
      table: 'Brand',
      column: 'Brand ID',
      merged: true,
      indexed: false,
    },
    {
      id: '[Category.Category]',
      type: 'dimension',
      dimtype: 'text',
      title: 'Category',
      table: 'Category',
      column: 'Category',
      merged: false,
      indexed: true,
    },
    {
      id: '[Category.Category ID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'Category ID',
      table: 'Category',
      column: 'Category ID',
      merged: true,
      indexed: false,
    },
    {
      id: '[Commerce.Age Range]',
      type: 'dimension',
      dimtype: 'text',
      title: 'Age Range',
      table: 'Commerce',
      column: 'Age Range',
      merged: false,
      indexed: true,
    },
    {
      id: '[Commerce.Brand ID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'Brand ID',
      table: 'Commerce',
      column: 'Brand ID',
      merged: true,
      indexed: false,
    },
    {
      id: '[Commerce.Category ID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'Category ID',
      table: 'Commerce',
      column: 'Category ID',
      merged: true,
      indexed: false,
    },
    {
      id: '[Commerce.Condition]',
      type: 'dimension',
      dimtype: 'text',
      title: 'Condition',
      table: 'Commerce',
      column: 'Condition',
      merged: false,
      indexed: true,
    },
    {
      id: '[Commerce.Cost]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'Cost',
      table: 'Commerce',
      column: 'Cost',
      merged: false,
      indexed: false,
    },
    {
      id: '[Commerce.Country ID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'Country ID',
      table: 'Commerce',
      column: 'Country ID',
      merged: true,
      indexed: false,
    },
    {
      id: '[Commerce.Date (Calendar)]',
      type: 'dimension',
      dimtype: 'datetime',
      title: 'Date',
      table: 'Commerce',
      column: 'Date',
      merged: false,
      indexed: true,
    },
    {
      id: '[Commerce.Date (Month)]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'Date (Month)',
      table: 'Commerce',
      column: 'Date (Month)',
      merged: false,
      indexed: false,
    },
    {
      id: '[Commerce.Gender]',
      type: 'dimension',
      dimtype: 'text',
      title: 'Gender',
      table: 'Commerce',
      column: 'Gender',
      merged: false,
      indexed: true,
    },
    {
      id: '[Commerce.Quantity]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'Quantity',
      table: 'Commerce',
      column: 'Quantity',
      merged: false,
      indexed: false,
    },
    {
      id: '[Commerce.Revenue]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'Revenue',
      table: 'Commerce',
      column: 'Revenue',
      merged: false,
      indexed: false,
    },
    {
      id: '[Commerce.Visit ID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'Visit ID',
      table: 'Commerce',
      column: 'Visit ID',
      merged: false,
      indexed: false,
    },
    {
      id: '[Country.Country]',
      type: 'dimension',
      dimtype: 'text',
      title: 'Country',
      table: 'Country',
      column: 'Country',
      merged: false,
      indexed: true,
    },
    {
      id: '[Country.Country ID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'Country ID',
      table: 'Country',
      column: 'Country ID',
      merged: true,
      indexed: false,
    },
  ],
};

export const dimensionalModelECommerce = {
  name: 'Sample ECommerce',
  dataSource: 'Sample ECommerce',
  metadata: [
    {
      attributes: [
        {
          expression: '[Brand.Brand]',
          name: 'Brand',
          type: 'text-attribute',
        },
        {
          expression: '[Brand.Brand ID]',
          name: 'Brand ID',
          type: 'numeric-attribute',
        },
      ],
      dimensions: [],
      name: 'Brand',
      type: 'dimension',
    },
    {
      attributes: [
        {
          expression: '[Category.Category]',
          name: 'Category',
          type: 'text-attribute',
        },
        {
          expression: '[Category.Category ID]',
          name: 'Category ID',
          type: 'numeric-attribute',
        },
      ],
      dimensions: [],
      name: 'Category',
      type: 'dimension',
    },
    {
      attributes: [
        {
          expression: '[Commerce.Age Range]',
          name: 'Age Range',
          type: 'text-attribute',
        },
        {
          expression: '[Commerce.Brand ID]',
          name: 'Brand ID',
          type: 'numeric-attribute',
        },
        {
          expression: '[Commerce.Category ID]',
          name: 'Category ID',
          type: 'numeric-attribute',
        },
        {
          expression: '[Commerce.Condition]',
          name: 'Condition',
          type: 'text-attribute',
        },
        {
          expression: '[Commerce.Cost]',
          name: 'Cost',
          type: 'numeric-attribute',
        },
        {
          expression: '[Commerce.Country ID]',
          name: 'Country ID',
          type: 'numeric-attribute',
        },
        {
          expression: '[Commerce.Date (Month)]',
          name: 'Date (Month)',
          type: 'numeric-attribute',
        },
        {
          expression: '[Commerce.Gender]',
          name: 'Gender',
          type: 'text-attribute',
        },
        {
          expression: '[Commerce.Quantity]',
          name: 'Quantity',
          type: 'numeric-attribute',
        },
        {
          expression: '[Commerce.Revenue]',
          name: 'Revenue',
          type: 'numeric-attribute',
        },
        {
          expression: '[Commerce.Visit ID]',
          name: 'Visit ID',
          type: 'numeric-attribute',
        },
      ],
      dimensions: [
        {
          expression: '[Commerce.Date (Calendar)]',
          name: 'Date',
          type: 'datedimension',
        },
      ],
      name: 'Commerce',
      type: 'dimension',
    },
    {
      attributes: [
        {
          expression: '[Country.Country]',
          name: 'Country',
          type: 'text-attribute',
        },
        {
          expression: '[Country.Country ID]',
          name: 'Country ID',
          type: 'numeric-attribute',
        },
      ],
      dimensions: [],
      name: 'Country',
      type: 'dimension',
    },
  ],
};

export const dimensionalModelECommerceWithFieldDescriptions = {
  name: 'Sample ECommerce',
  dataSource: { title: 'Sample ECommerce', type: 'elasticube' },
  metadata: [
    {
      name: 'Brand',
      type: 'dimension',
      dimensions: [],
      attributes: [
        { name: 'Brand', expression: '[Brand.Brand]', type: 'text-attribute', description: '' },
        {
          name: 'Brand ID',
          expression: '[Brand.Brand ID]',
          type: 'numeric-attribute',
          description: '',
        },
      ],
    },
    {
      name: 'Category',
      type: 'dimension',
      dimensions: [],
      attributes: [
        {
          name: 'Category',
          expression: '[Category.Category]',
          type: 'text-attribute',
          description: '',
        },
        {
          name: 'Category ID',
          expression: '[Category.Category ID]',
          type: 'numeric-attribute',
          description: '',
        },
      ],
    },
    {
      name: 'Commerce',
      type: 'dimension',
      dimensions: [
        {
          name: 'Date',
          expression: '[Commerce.Date (Calendar)]',
          type: 'datedimension',
          description: '',
        },
      ],
      attributes: [
        {
          name: 'Age Range',
          expression: '[Commerce.Age Range]',
          type: 'text-attribute',
          description: '',
        },
        {
          name: 'Brand ID',
          expression: '[Commerce.Brand ID]',
          type: 'numeric-attribute',
          description: '',
        },
        {
          name: 'Category ID',
          expression: '[Commerce.Category ID]',
          type: 'numeric-attribute',
          description: '',
        },
        {
          name: 'Condition',
          expression: '[Commerce.Condition]',
          type: 'text-attribute',
          description: '',
        },
        {
          name: 'Cost',
          expression: '[Commerce.Cost]',
          type: 'numeric-attribute',
          description: 'Cost Long `Description` !@#$%^*&*())_ \'\' "" ``',
        },
        {
          name: 'Country ID',
          expression: '[Commerce.Country ID]',
          type: 'numeric-attribute',
          description: '',
        },
        {
          name: 'Date (Month)',
          expression: '[Commerce.Date (Month)]',
          type: 'numeric-attribute',
          description: '',
        },
        {
          name: 'Gender',
          expression: '[Commerce.Gender]',
          type: 'text-attribute',
          description: '',
        },
        {
          name: 'Quantity',
          expression: '[Commerce.Quantity]',
          type: 'numeric-attribute',
          description: '',
        },
        {
          name: 'Revenue',
          expression: '[Commerce.Revenue]',
          type: 'numeric-attribute',
          description: 'Some More description',
        },
        {
          name: 'Visit ID',
          expression: '[Commerce.Visit ID]',
          type: 'numeric-attribute',
          description: '',
        },
      ],
    },
    {
      name: 'Country',
      type: 'dimension',
      dimensions: [],
      attributes: [
        {
          name: 'Country',
          expression: '[Country.Country]',
          type: 'text-attribute',
          description: '',
        },
        {
          name: 'Country ID',
          expression: '[Country.Country ID]',
          type: 'numeric-attribute',
          description: '',
        },
      ],
    },
  ],
};

export const dataSourceSchemaECommerce = {
  oid: 'f509a461-c16e-42ab-b584-cd24c042b7f0',
  title: 'Sample ECommerce',
  server: 'LocalHost',
  serverId: '7c3f73dd-0b38-48dc-9347-c78811bd80c4',
  shares: [
    {
      partyId: '634983b9b8597a54968e8479',
      type: 'group',
      permission: 'w',
    },
    {
      partyId: '634983b9b13b3c001a160ff6',
      type: 'user',
      permission: 'w',
    },
  ],
  revision: null,
  lastBuildTime: '2023-10-08T05:30:53.228Z',
  lastSuccessfulBuildTime: null,
  lastBuildTimeFromNextECM: null,
  lastPublishTime: null,
  lastUpdated: '2024-04-28T16:51:02.340Z',
  datasets: [
    {
      oid: '3fe5b357-6615-47e9-ac85-8f2c95fe52da',
      type: 'extract',
      connection: {
        id: '634984e6d5fca4002e9119b7',
        oid: 'c77f96ee-88a1-4d5f-ab0f-99206c62d24b',
        provider: 'CSV',
        parameters: {
          culture: 'en-US',
          Database: 'null',
          delimiter: ',',
          files: ['/opt/sisense/storage/samples/Sample ECommerce/Commerce/Commerce.csv'],
          folder: '',
          hasHeader: 'true',
          ignoreFirstRows: '0',
          ignoreLastRows: '0',
          IsUsingDirectConnection: 'false',
          Password: '',
          Port: '-1',
          Schema: 'null',
          Server: '/opt/sisense/storage/samples/Sample ECommerce/Commerce/Commerce.csv',
          stringQuote: '"',
          UserName: 'null',
        },
        schema: 'null',
        owner: '634983b9b13b3c001a160ff6',
        fileName: null,
        protectedParameters: [],
        uiParams: null,
        globalTableConfigOptions: null,
        enabled: null,
        created: null,
        lastModified: null,
        supportedModelTypes: null,
        ownerId: null,
        createdByUser: null,
        name: null,
        description: null,
        connectionPermissions: null,
      },
      lastUpdated: '2024-04-29T19:15:41.996Z',
      database: 'null',
      schemaName: 'null',
      name: '4e51d050-093b-4214-8ad2-d48516c5f29f',
      fullname: 'CSV:4e51d050-093b-4214-8ad2-d48516c5f29f',
      modelingTransformations: [],
      schema: {
        tables: [
          {
            oid: '759f0f0a-c84a-4ffa-9732-5d7f83b8110e',
            id: 'Commerce.csv',
            name: 'Commerce',
            type: 'base',
            expression: null,
            columns: [
              {
                id: 'Age Range',
                name: 'Age Range',
                oid: '9945b7ab-b0da-4205-a2e4-b8a9c1e4d731',
                type: 18,
                size: 50,
                precision: 0,
                scale: 0,
                hidden: false,
                indexed: true,
                isUpsertBy: false,
                lastUpdated: '2022-10-14T15:48:55.922Z',
                description: null,
                expression: null,
                import: null,
                isCustom: null,
              },
              {
                id: 'Cost',
                name: 'Cost',
                oid: 'df6f2971-4e4e-4ecc-ad03-322ee37b8647',
                type: 5,
                size: 50,
                precision: 16,
                scale: 16,
                hidden: false,
                indexed: false,
                isUpsertBy: false,
                lastUpdated: '2024-04-25T20:21:10.490Z',
                description: 'Cost Long `Description` !@#$%^*&*())_ \'\' "" ``',
                expression: null,
                import: null,
                isCustom: null,
              },
              {
                id: 'Brand ID',
                name: 'Brand ID',
                oid: '0f77a36e-0c98-4b24-8c50-7b060fed579c',
                type: 8,
                size: 50,
                precision: 0,
                scale: 0,
                hidden: false,
                indexed: false,
                isUpsertBy: false,
                lastUpdated: '2022-10-14T15:48:55.922Z',
                description: null,
                expression: null,
                import: null,
                isCustom: null,
              },
              {
                id: 'Category ID',
                name: 'Category ID',
                oid: 'eb95e785-369b-4355-a58f-8dee65bd3004',
                type: 8,
                size: 50,
                precision: 0,
                scale: 0,
                hidden: false,
                indexed: false,
                isUpsertBy: false,
                lastUpdated: '2022-10-14T15:48:55.922Z',
                description: null,
                expression: null,
                import: null,
                isCustom: null,
              },
              {
                id: 'Condition',
                name: 'Condition',
                oid: '6267d3c8-640f-408d-b103-50b92d70d880',
                type: 18,
                size: 50,
                precision: 0,
                scale: 0,
                hidden: false,
                indexed: true,
                isUpsertBy: false,
                lastUpdated: '2022-10-14T15:48:55.922Z',
                description: null,
                expression: null,
                import: null,
                isCustom: null,
              },
              {
                id: 'Country ID',
                name: 'Country ID',
                oid: '04a8b476-dacc-45ca-a05c-3166622de15e',
                type: 8,
                size: 50,
                precision: 0,
                scale: 0,
                hidden: false,
                indexed: false,
                isUpsertBy: false,
                lastUpdated: '2022-10-14T15:48:55.922Z',
                description: null,
                expression: null,
                import: null,
                isCustom: null,
              },
              {
                id: 'Date',
                name: 'Date',
                oid: '7789c838-cd4b-40d1-b646-2a2b76aab9a7',
                type: 4,
                size: 8,
                precision: 0,
                scale: 0,
                hidden: false,
                indexed: false,
                isUpsertBy: false,
                lastUpdated: '2022-10-14T15:48:55.922Z',
                description: null,
                expression: null,
                import: null,
                isCustom: null,
              },
              {
                id: 'Gender',
                name: 'Gender',
                oid: '525c0841-f2c6-45f9-a7c1-d9204114b836',
                type: 18,
                size: 50,
                precision: 0,
                scale: 0,
                hidden: false,
                indexed: true,
                isUpsertBy: false,
                lastUpdated: '2022-10-14T15:48:55.922Z',
                description: null,
                expression: null,
                import: null,
                isCustom: null,
              },
              {
                id: 'Quantity',
                name: 'Quantity',
                oid: '00f0cd75-8427-4f79-acd5-190720fe6cb7',
                type: 8,
                size: 50,
                precision: 0,
                scale: 0,
                hidden: false,
                indexed: false,
                isUpsertBy: false,
                lastUpdated: '2022-10-14T15:48:55.922Z',
                description: null,
                expression: null,
                import: null,
                isCustom: null,
              },
              {
                id: 'Revenue',
                name: 'Revenue',
                oid: 'd28ed9b7-094a-4449-a40f-664a6baa29db',
                type: 5,
                size: 50,
                precision: 16,
                scale: 16,
                hidden: false,
                indexed: false,
                isUpsertBy: false,
                lastUpdated: '2024-04-28T16:51:02.340Z',
                description: 'Some More description',
                expression: null,
                import: null,
                isCustom: null,
              },
              {
                id: 'Visit ID',
                name: 'Visit ID',
                oid: '258ea04d-0595-4198-8e59-195c04528fed',
                type: 8,
                size: 50,
                precision: 0,
                scale: 0,
                hidden: false,
                indexed: false,
                isUpsertBy: false,
                lastUpdated: '2022-10-14T15:48:55.922Z',
                description: null,
                expression: null,
                import: null,
                isCustom: null,
              },
            ],
            buildBehavior: {
              type: 'sync',
              accumulativeConfig: null,
            },
            lastUpdated: '2024-04-28T16:51:02.340Z',
            hidden: false,
            vTag: '2ff09e9d-95fc-4183-885d-d82844b308b1',
            configOptions: {
              Table: 'Commerce.csv',
            },
            createdAt: '2022-10-14T15:48:56.000Z',
            description: null,
            tags: null,
            isMaterialized: false,
          },
        ],
      },
      schedule: {
        type: null,
        lastExecution: null,
        day: null,
        days: null,
        hour: null,
        minute: null,
        second: null,
      },
      shares: [],
      liveQuerySettings: null,
    },
    {
      oid: '5f54feee-1076-4d65-a5e7-01dbe65a1482',
      type: 'extract',
      connection: {
        id: '65223e56771f29002de62768',
        oid: 'd2cc9323-ba75-496e-af2b-fe21115aef9e',
        provider: 'CSV',
        parameters: {
          ApiVersion: '2',
          files: [
            '/opt/sisense/storage/tenants/634983b9b13b3c001a161003/storage/c4/c41cbfd4-85bf-45ab-b05d-aa56e19eb48a.csv',
          ],
        },
        schema:
          '/opt/sisense/storage/tenants/634983b9b13b3c001a161003/storage/c4/c41cbfd4-85bf-45ab-b05d-aa56e19eb48a.csv',
        owner: '6452bac4ccf41d0030c5e784',
        fileName: 'CountryPopulation.csv',
        protectedParameters: [],
        uiParams: {},
        globalTableConfigOptions: null,
        enabled: null,
        created: null,
        lastModified: null,
        supportedModelTypes: null,
        ownerId: null,
        createdByUser: true,
        name: null,
        description: null,
        connectionPermissions: null,
      },
      lastUpdated: '2024-04-29T19:15:41.996Z',
      database: '',
      schemaName:
        '/opt/sisense/storage/tenants/634983b9b13b3c001a161003/storage/c4/c41cbfd4-85bf-45ab-b05d-aa56e19eb48a.csv',
      name: 'b1cef9cd-6a74-42b2-9ec4-c8b4a5d0622f',
      fullname: 'CSV:b1cef9cd-6a74-42b2-9ec4-c8b4a5d0622f',
      modelingTransformations: [],
      schema: {
        tables: [
          {
            oid: 'fd5d433b-cb9d-433f-a550-f2a515c28f75',
            id: 'c41cbfd4-85bf-45ab-b05d-aa56e19eb48a.csv',
            name: 'CountryPopulation',
            type: 'base',
            expression: null,
            columns: [
              {
                id: 'Continent',
                name: 'Continent',
                oid: '88b6cf99-b7e8-491c-9c6e-94aff02eb78f',
                type: 18,
                size: 0,
                precision: 0,
                scale: 0,
                hidden: false,
                indexed: true,
                isUpsertBy: false,
                lastUpdated: '2023-10-08T05:29:57.950Z',
                description: null,
                expression: null,
                import: null,
                isCustom: null,
              },
              {
                id: 'Country Code',
                name: 'Country Code',
                oid: '014b8f62-c083-4e9e-9e94-7c3abe071d7e',
                type: 18,
                size: 0,
                precision: 0,
                scale: 0,
                hidden: false,
                indexed: true,
                isUpsertBy: false,
                lastUpdated: '2023-10-08T05:29:57.950Z',
                description: null,
                expression: null,
                import: null,
                isCustom: null,
              },
              {
                id: 'Country Name',
                name: 'Country Name',
                oid: '48fb1cc1-6144-44ec-96b2-e4e52584b016',
                type: 18,
                size: 0,
                precision: 0,
                scale: 0,
                hidden: false,
                indexed: true,
                isUpsertBy: false,
                lastUpdated: '2023-10-08T05:29:57.950Z',
                description: null,
                expression: null,
                import: null,
                isCustom: null,
              },
              {
                id: 'Population',
                name: 'Population',
                oid: '1e5c2230-a020-41df-a4bb-b6ae29bb1eb8',
                type: 8,
                size: 0,
                precision: 0,
                scale: 0,
                hidden: false,
                indexed: true,
                isUpsertBy: false,
                lastUpdated: '2023-10-08T05:29:57.950Z',
                description: null,
                expression: null,
                import: null,
                isCustom: null,
              },
            ],
            buildBehavior: {
              type: 'sync',
              accumulativeConfig: null,
            },
            lastUpdated: '2023-10-08T05:30:09.345Z',
            hidden: false,
            vTag: 'a70e6266-5df6-4aa2-9802-8607b8919d69',
            configOptions: {
              delimiter: ',',
              hasHeader: true,
              ignoreMissingColumns: false,
              excludeIfBegins: '',
              excludeIfContains: '',
              stringQuote: '"',
              ignoreFirstRows: '',
              culture: 'en-US',
              columnsDateTimePatterns: '{}',
            },
            createdAt: '2023-10-08T05:29:58.000Z',
            description: null,
            tags: null,
            isMaterialized: false,
          },
        ],
      },
      schedule: {
        type: null,
        lastExecution: null,
        day: null,
        days: null,
        hour: null,
        minute: null,
        second: null,
      },
      shares: [],
      liveQuerySettings: null,
    },
    {
      oid: '62d1c93b-9076-45b7-a722-069921b9a062',
      type: 'extract',
      connection: {
        id: '634984e6d5fca4002e9119b8',
        oid: '88e0ee8a-5430-44ff-801b-e83a73ee2173',
        provider: 'CSV',
        parameters: {
          culture: 'en-US',
          Database: 'null',
          delimiter: ',',
          files: ['/opt/sisense/storage/samples/Sample ECommerce/Category/Category.csv'],
          folder: '',
          hasHeader: 'true',
          ignoreFirstRows: '0',
          ignoreLastRows: '0',
          IsUsingDirectConnection: 'false',
          Password: '',
          Port: '-1',
          Schema: 'null',
          Server: '/opt/sisense/storage/samples/Sample ECommerce/Category/Category.csv',
          stringQuote: '"',
          UserName: 'null',
        },
        schema: 'null',
        owner: '634983b9b13b3c001a160ff6',
        fileName: null,
        protectedParameters: [],
        uiParams: null,
        globalTableConfigOptions: null,
        enabled: null,
        created: null,
        lastModified: null,
        supportedModelTypes: null,
        ownerId: null,
        createdByUser: null,
        name: null,
        description: null,
        connectionPermissions: null,
      },
      lastUpdated: '2024-04-29T19:15:41.996Z',
      database: 'null',
      schemaName: 'null',
      name: '7471db1d-03dd-48c6-86d4-29cf296d1a5c',
      fullname: 'CSV:7471db1d-03dd-48c6-86d4-29cf296d1a5c',
      modelingTransformations: [],
      schema: {
        tables: [
          {
            oid: '6a4d2261-0aa9-45ae-8c16-b6b1ff385803',
            id: 'Category.csv',
            name: 'Category',
            type: 'base',
            expression: null,
            columns: [
              {
                id: 'Category',
                name: 'Category',
                oid: '5c7e1735-7640-4064-81eb-ddf8f0d78a11',
                type: 18,
                size: 50,
                precision: 0,
                scale: 0,
                hidden: false,
                indexed: true,
                isUpsertBy: false,
                lastUpdated: '2022-10-14T15:48:55.922Z',
                description: null,
                expression: null,
                import: null,
                isCustom: null,
              },
              {
                id: 'Category ID',
                name: 'Category ID',
                oid: 'b8fcd716-ad34-4eaa-b9d8-953ddaa661cd',
                type: 8,
                size: 50,
                precision: 0,
                scale: 0,
                hidden: false,
                indexed: false,
                isUpsertBy: false,
                lastUpdated: '2022-10-14T15:48:55.922Z',
                description: null,
                expression: null,
                import: null,
                isCustom: null,
              },
            ],
            buildBehavior: {
              type: 'sync',
              accumulativeConfig: null,
            },
            lastUpdated: '2022-10-14T15:48:47.658Z',
            hidden: false,
            vTag: '2367bc3f-04a3-478d-a845-334bc525ec98',
            configOptions: {
              Table: 'Category.csv',
            },
            createdAt: '2022-10-14T15:48:55.000Z',
            description: null,
            tags: null,
            isMaterialized: false,
          },
        ],
      },
      schedule: {
        type: null,
        lastExecution: null,
        day: null,
        days: null,
        hour: null,
        minute: null,
        second: null,
      },
      shares: [],
      liveQuerySettings: null,
    },
    {
      oid: 'b53e0d98-8060-40d7-98a6-cd809a8f756d',
      type: 'extract',
      connection: {
        id: '634984e6d5fca4002e9119b5',
        oid: 'bdaf874d-9354-470c-8286-dae93667866d',
        provider: 'CSV',
        parameters: {
          culture: 'en-US',
          Database: 'null',
          delimiter: ',',
          files: ['/opt/sisense/storage/samples/Sample ECommerce/Country/Country.csv'],
          folder: '',
          hasHeader: 'true',
          ignoreFirstRows: '0',
          ignoreLastRows: '0',
          IsUsingDirectConnection: 'false',
          Password: '',
          Port: '-1',
          Schema: 'null',
          Server: '/opt/sisense/storage/samples/Sample ECommerce/Country/Country.csv',
          stringQuote: '"',
          UserName: 'null',
        },
        schema: 'null',
        owner: '634983b9b13b3c001a160ff6',
        fileName: null,
        protectedParameters: [],
        uiParams: null,
        globalTableConfigOptions: null,
        enabled: null,
        created: null,
        lastModified: null,
        supportedModelTypes: null,
        ownerId: null,
        createdByUser: null,
        name: null,
        description: null,
        connectionPermissions: null,
      },
      lastUpdated: '2024-04-29T19:15:41.996Z',
      database: 'null',
      schemaName: 'null',
      name: '03911b19-a707-4046-b23d-c5606a2a3ab8',
      fullname: 'CSV:03911b19-a707-4046-b23d-c5606a2a3ab8',
      modelingTransformations: [],
      schema: {
        tables: [
          {
            oid: 'dd7617d9-d7d5-48a5-acff-f427ae5b2d08',
            id: 'Country.csv',
            name: 'Country',
            type: 'base',
            expression: null,
            columns: [
              {
                id: 'Country',
                name: 'Country',
                oid: 'a0b5d09d-a410-4f8e-aae2-36d8e9a5a3b3',
                type: 18,
                size: 50,
                precision: 0,
                scale: 0,
                hidden: false,
                indexed: true,
                isUpsertBy: false,
                lastUpdated: '2022-10-14T15:48:55.922Z',
                description: null,
                expression: null,
                import: null,
                isCustom: null,
              },
              {
                id: 'Country ID',
                name: 'Country ID',
                oid: '262a0527-1287-4e98-96f6-a0361fbe195f',
                type: 8,
                size: 50,
                precision: 0,
                scale: 0,
                hidden: false,
                indexed: false,
                isUpsertBy: false,
                lastUpdated: '2022-10-14T15:48:55.922Z',
                description: null,
                expression: null,
                import: null,
                isCustom: null,
              },
            ],
            buildBehavior: {
              type: 'sync',
              accumulativeConfig: null,
            },
            lastUpdated: '2022-10-14T15:48:47.657Z',
            hidden: false,
            vTag: '394d883b-8ce6-4011-96f7-70f8de60cdcf',
            configOptions: {
              Table: 'Country.csv',
            },
            createdAt: '2022-10-14T15:48:55.000Z',
            description: null,
            tags: null,
            isMaterialized: false,
          },
        ],
      },
      schedule: {
        type: null,
        lastExecution: null,
        day: null,
        days: null,
        hour: null,
        minute: null,
        second: null,
      },
      shares: [],
      liveQuerySettings: null,
    },
    {
      oid: 'df858a6b-64de-4ead-a671-83d3edf3473c',
      type: 'extract',
      connection: {
        id: '634984e6d5fca4002e9119b6',
        oid: 'a3591e94-b589-4ba7-ae1c-47d8ba5d1776',
        provider: 'CSV',
        parameters: {
          culture: 'en-US',
          Database: 'null',
          delimiter: ',',
          files: ['/opt/sisense/storage/samples/Sample ECommerce/Brand/Brand.csv'],
          folder: '',
          hasHeader: 'true',
          ignoreFirstRows: '0',
          ignoreLastRows: '0',
          IsUsingDirectConnection: 'false',
          Password: '',
          Port: '-1',
          Schema: 'null',
          Server: '/opt/sisense/storage/samples/Sample ECommerce/Brand/Brand.csv',
          stringQuote: '"',
          UserName: 'null',
        },
        schema: 'null',
        owner: '634983b9b13b3c001a160ff6',
        fileName: null,
        protectedParameters: [],
        uiParams: null,
        globalTableConfigOptions: null,
        enabled: null,
        created: null,
        lastModified: null,
        supportedModelTypes: null,
        ownerId: null,
        createdByUser: null,
        name: null,
        description: null,
        connectionPermissions: null,
      },
      lastUpdated: '2024-04-29T19:15:41.996Z',
      database: 'null',
      schemaName: 'null',
      name: 'c40c53cc-9d6c-40f2-8366-b723c8bce11c',
      fullname: 'CSV:c40c53cc-9d6c-40f2-8366-b723c8bce11c',
      modelingTransformations: [],
      schema: {
        tables: [
          {
            oid: '229ae01c-5b89-4af7-a2b2-861842a18119',
            id: 'Brand.csv',
            name: 'Brand',
            type: 'base',
            expression: null,
            columns: [
              {
                id: 'Brand',
                name: 'Brand',
                oid: '5356924a-f294-417b-a927-feb36f27b70b',
                type: 18,
                size: 50,
                precision: 0,
                scale: 0,
                hidden: false,
                indexed: true,
                isUpsertBy: false,
                lastUpdated: '2022-10-14T15:48:55.922Z',
                description: null,
                expression: null,
                import: null,
                isCustom: null,
              },
              {
                id: 'Brand ID',
                name: 'Brand ID',
                oid: 'a222422f-17f7-45e3-8875-6b97bb2c1083',
                type: 8,
                size: 50,
                precision: 0,
                scale: 0,
                hidden: false,
                indexed: false,
                isUpsertBy: false,
                lastUpdated: '2022-10-14T15:48:55.922Z',
                description: null,
                expression: null,
                import: null,
                isCustom: null,
              },
            ],
            buildBehavior: {
              type: 'sync',
              accumulativeConfig: null,
            },
            lastUpdated: '2022-10-14T15:48:47.658Z',
            hidden: false,
            vTag: 'fe07ff30-f587-4c3b-80a4-2a630eb00b8c',
            configOptions: {
              Table: 'Brand.csv',
            },
            createdAt: '2022-10-14T15:48:55.000Z',
            description: null,
            tags: null,
            isMaterialized: false,
          },
        ],
      },
      schedule: {
        type: null,
        lastExecution: null,
        day: null,
        days: null,
        hour: null,
        minute: null,
        second: null,
      },
      shares: [],
      liveQuerySettings: null,
    },
  ],
  modelingTransformations: [],
  relations: [
    {
      oid: 'c0d208e3-26fe-4d7e-adb1-958c5eb79b0c',
      columns: [
        {
          dataset: '62d1c93b-9076-45b7-a722-069921b9a062',
          table: '6a4d2261-0aa9-45ae-8c16-b6b1ff385803',
          column: 'b8fcd716-ad34-4eaa-b9d8-953ddaa661cd',
          isDropped: null,
        },
        {
          dataset: '3fe5b357-6615-47e9-ac85-8f2c95fe52da',
          table: '759f0f0a-c84a-4ffa-9732-5d7f83b8110e',
          column: 'eb95e785-369b-4355-a58f-8dee65bd3004',
          isDropped: null,
        },
      ],
      type: null,
    },
    {
      oid: 'b93ca9a3-c220-49cf-b700-afb0353743d5',
      columns: [
        {
          dataset: 'b53e0d98-8060-40d7-98a6-cd809a8f756d',
          table: 'dd7617d9-d7d5-48a5-acff-f427ae5b2d08',
          column: '262a0527-1287-4e98-96f6-a0361fbe195f',
          isDropped: null,
        },
        {
          dataset: '3fe5b357-6615-47e9-ac85-8f2c95fe52da',
          table: '759f0f0a-c84a-4ffa-9732-5d7f83b8110e',
          column: '04a8b476-dacc-45ca-a05c-3166622de15e',
          isDropped: null,
        },
      ],
      type: null,
    },
    {
      oid: 'bc16ffcd-fdab-4906-b501-aeed47384b1c',
      columns: [
        {
          dataset: 'df858a6b-64de-4ead-a671-83d3edf3473c',
          table: '229ae01c-5b89-4af7-a2b2-861842a18119',
          column: 'a222422f-17f7-45e3-8875-6b97bb2c1083',
          isDropped: null,
        },
        {
          dataset: '3fe5b357-6615-47e9-ac85-8f2c95fe52da',
          table: '759f0f0a-c84a-4ffa-9732-5d7f83b8110e',
          column: '0f77a36e-0c98-4b24-8c50-7b060fed579c',
          isDropped: null,
        },
      ],
      type: null,
    },
    {
      oid: '7fc628aa-750b-4a4a-b5a0-319290b5448d',
      columns: [
        {
          dataset: '5f54feee-1076-4d65-a5e7-01dbe65a1482',
          table: 'fd5d433b-cb9d-433f-a550-f2a515c28f75',
          column: '48fb1cc1-6144-44ec-96b2-e4e52584b016',
          isDropped: null,
        },
        {
          dataset: 'b53e0d98-8060-40d7-98a6-cd809a8f756d',
          table: 'dd7617d9-d7d5-48a5-acff-f427ae5b2d08',
          column: 'a0b5d09d-a410-4f8e-aae2-36d8e9a5a3b3',
          isDropped: null,
        },
      ],
      type: null,
    },
  ],
  schedule: null,
  creator: {
    id: '634983b9b13b3c001a160ff6',
    userName: 'rnd-trial-project@sisense.com',
    active: true,
    created: '2022-10-14T15:43:53.431Z',
    email: 'rnd-trial-project@sisense.com',
    encryptionSHA: null,
    firstName: 'Trial System Admin',
    lastName: 'Sisense',
    lastLogin: '2024-04-03T10:13:43.121Z',
    lastUpdated: '2024-04-03T10:13:43.121Z',
    prefrences: null,
    roleId: '634983b9b8597a54968e8442',
  },
  type: 'extract',
  relationType: 'regular',
  tenant: {
    _id: '634983b9b13b3c001a161003',
    name: 'system',
    default: true,
    systemManagement: true,
  },
};
