export const dataSources = [
  {
    fullname: 'localhost/Master CRM Data',
    id: 'localhost_aMasterIAAaCRMIAAaData',
    address: 'LocalHost',
    database: 'aMasterIAAaCRMIAAaData',
    live: false,
    title: 'Master CRM Data',
  },
  {
    fullname: 'localhost/[DEMO] Master CRM Data',
    id: 'localhost_aWwAaDEMOXQAaIAAaMasterIAAaCRMIAAaData',
    address: 'LocalHost',
    database: 'aWwAaDEMOXQAaIAAaMasterIAAaCRMIAAaData',
    live: false,
    title: '[DEMO] Master CRM Data',
  },
  {
    fullname: 'localhost/Sample Retail',
    id: 'localhost_aSampleIAAaRetail',
    address: 'LocalHost',
    database: 'aSampleIAAaRetail',
    live: false,
    title: 'Sample Retail',
  },
  {
    fullname: 'localhost/Sample Lead Generation',
    id: 'localhost_aSampleIAAaLeadIAAaGeneration',
    address: 'LocalHost',
    database: 'aSampleIAAaLeadIAAaGeneration',
    live: false,
    title: 'Sample Lead Generation',
  },
  {
    fullname: 'localhost/Sample ECommerce',
    id: 'localhost_aSampleIAAaECommerce',
    address: 'LocalHost',
    database: 'aSampleIAAaECommerce',
    live: false,
    title: 'Sample ECommerce',
  },
  {
    fullname: 'localhost/Sample Healthcare',
    id: 'localhost_aSampleIAAaHealthcare',
    address: 'LocalHost',
    database: 'aSampleIAAaHealthcare',
    live: false,
    title: 'Sample Healthcare',
  },
];
