export const fieldsECommerce = {
  name: 'Sample ECommerce',
  dataSource: 'Sample ECommerce',
  metadata: [
    {
      id: '[Brand.Brand]',
      type: 'dimension',
      dimtype: 'text',
      title: 'Brand',
      table: 'Brand',
      column: 'Brand',
      merged: false,
      indexed: true,
    },
    {
      id: '[Brand.Brand ID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'Brand ID',
      table: 'Brand',
      column: 'Brand ID',
      merged: true,
      indexed: false,
    },
    {
      id: '[Category.Category]',
      type: 'dimension',
      dimtype: 'text',
      title: 'Category',
      table: 'Category',
      column: 'Category',
      merged: false,
      indexed: true,
    },
    {
      id: '[Category.Category ID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'Category ID',
      table: 'Category',
      column: 'Category ID',
      merged: true,
      indexed: false,
    },
    {
      id: '[Commerce.Age Range]',
      type: 'dimension',
      dimtype: 'text',
      title: 'Age Range',
      table: 'Commerce',
      column: 'Age Range',
      merged: false,
      indexed: true,
    },
    {
      id: '[Commerce.Brand ID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'Brand ID',
      table: 'Commerce',
      column: 'Brand ID',
      merged: true,
      indexed: false,
    },
    {
      id: '[Commerce.Category ID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'Category ID',
      table: 'Commerce',
      column: 'Category ID',
      merged: true,
      indexed: false,
    },
    {
      id: '[Commerce.Condition]',
      type: 'dimension',
      dimtype: 'text',
      title: 'Condition',
      table: 'Commerce',
      column: 'Condition',
      merged: false,
      indexed: true,
    },
    {
      id: '[Commerce.Cost]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'Cost',
      table: 'Commerce',
      column: 'Cost',
      merged: false,
      indexed: false,
    },
    {
      id: '[Commerce.Country ID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'Country ID',
      table: 'Commerce',
      column: 'Country ID',
      merged: true,
      indexed: false,
    },
    {
      id: '[Commerce.Date (Calendar)]',
      type: 'dimension',
      dimtype: 'datetime',
      title: 'Date',
      table: 'Commerce',
      column: 'Date',
      merged: false,
      indexed: true,
    },
    {
      id: '[Commerce.Date (Month)]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'Date (Month)',
      table: 'Commerce',
      column: 'Date (Month)',
      merged: false,
      indexed: false,
    },
    {
      id: '[Commerce.Gender]',
      type: 'dimension',
      dimtype: 'text',
      title: 'Gender',
      table: 'Commerce',
      column: 'Gender',
      merged: false,
      indexed: true,
    },
    {
      id: '[Commerce.Quantity]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'Quantity',
      table: 'Commerce',
      column: 'Quantity',
      merged: false,
      indexed: false,
    },
    {
      id: '[Commerce.Revenue]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'Revenue',
      table: 'Commerce',
      column: 'Revenue',
      merged: false,
      indexed: false,
    },
    {
      id: '[Commerce.Visit ID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'Visit ID',
      table: 'Commerce',
      column: 'Visit ID',
      merged: false,
      indexed: false,
    },
    {
      id: '[Country.Country]',
      type: 'dimension',
      dimtype: 'text',
      title: 'Country',
      table: 'Country',
      column: 'Country',
      merged: false,
      indexed: true,
    },
    {
      id: '[Country.Country ID]',
      type: 'dimension',
      dimtype: 'numeric',
      title: 'Country ID',
      table: 'Country',
      column: 'Country ID',
      merged: true,
      indexed: false,
    },
  ],
};

export const dimensionalModelECommerce = {
  name: 'Sample ECommerce',
  dataSource: 'Sample ECommerce',
  metadata: [
    {
      attributes: [
        {
          expression: '[Brand.Brand]',
          name: 'Brand',
          type: 'text-attribute',
        },
        {
          expression: '[Brand.Brand ID]',
          name: 'Brand ID',
          type: 'numeric-attribute',
        },
      ],
      dimensions: [],
      name: 'Brand',
      type: 'dimension',
    },
    {
      attributes: [
        {
          expression: '[Category.Category]',
          name: 'Category',
          type: 'text-attribute',
        },
        {
          expression: '[Category.Category ID]',
          name: 'Category ID',
          type: 'numeric-attribute',
        },
      ],
      dimensions: [],
      name: 'Category',
      type: 'dimension',
    },
    {
      attributes: [
        {
          expression: '[Commerce.Age Range]',
          name: 'Age Range',
          type: 'text-attribute',
        },
        {
          expression: '[Commerce.Brand ID]',
          name: 'Brand ID',
          type: 'numeric-attribute',
        },
        {
          expression: '[Commerce.Category ID]',
          name: 'Category ID',
          type: 'numeric-attribute',
        },
        {
          expression: '[Commerce.Condition]',
          name: 'Condition',
          type: 'text-attribute',
        },
        {
          expression: '[Commerce.Cost]',
          name: 'Cost',
          type: 'numeric-attribute',
        },
        {
          expression: '[Commerce.Country ID]',
          name: 'Country ID',
          type: 'numeric-attribute',
        },
        {
          expression: '[Commerce.Date (Month)]',
          name: 'Date (Month)',
          type: 'numeric-attribute',
        },
        {
          expression: '[Commerce.Gender]',
          name: 'Gender',
          type: 'text-attribute',
        },
        {
          expression: '[Commerce.Quantity]',
          name: 'Quantity',
          type: 'numeric-attribute',
        },
        {
          expression: '[Commerce.Revenue]',
          name: 'Revenue',
          type: 'numeric-attribute',
        },
        {
          expression: '[Commerce.Visit ID]',
          name: 'Visit ID',
          type: 'numeric-attribute',
        },
      ],
      dimensions: [
        {
          expression: '[Commerce.Date (Calendar)]',
          name: 'Date',
          type: 'datedimension',
        },
      ],
      name: 'Commerce',
      type: 'dimension',
    },
    {
      attributes: [
        {
          expression: '[Country.Country]',
          name: 'Country',
          type: 'text-attribute',
        },
        {
          expression: '[Country.Country ID]',
          name: 'Country ID',
          type: 'numeric-attribute',
        },
      ],
      dimensions: [],
      name: 'Country',
      type: 'dimension',
    },
  ],
};
