import {
  Attribute,
  convertDataSource,
  convertSortDirectionToSort,
  Filter,
  FilterRelations,
  isSortDirection,
  Measure,
  measureFactory,
} from '@sisense/sdk-data';

import { BaseQueryParams } from '@/domains/query-execution/index.js';

import { NlqTranslationError, NlqTranslationResult } from '../../types.js';
import { QueryInput } from '../../types.js';
import { translateDimensionsFromJSON } from '../constructs/dimensions/translate-dimensions-from-json.js';
import {
  translateFiltersFromJSON,
  translateHighlightsFromJSON,
} from '../constructs/filters/translate-filters-from-json.js';
import { translateMeasuresFromJSON } from '../constructs/measures/translate-measures-from-json.js';
import { createSchemaIndex } from '../shared/utils/schema-index.js';
import { collectTranslationErrors } from '../shared/utils/translation-helpers.js';
import type { DimensionTranslationItem, MeasureTranslationItem } from '../types.js';
import { FORECAST_PREFIX, TREND_PREFIX } from './constants.js';

function adaptDimensionsForQuery(items: DimensionTranslationItem[]): Attribute[] {
  return items.map(({ attribute, style }) => {
    const sortType = style?.sortType;
    if (!sortType) return attribute;
    const direction = typeof sortType === 'object' ? sortType.direction : sortType;
    if (!isSortDirection(direction)) return attribute;
    return attribute.sort(convertSortDirectionToSort(direction));
  });
}

function isTrendMeasure(measure: Measure): boolean {
  return measure.composeCode?.includes('measureFactory.trend') ?? false;
}

function isForecastMeasure(measure: Measure): boolean {
  return measure.composeCode?.includes('measureFactory.forecast') ?? false;
}

function adaptMeasuresForQuery(items: MeasureTranslationItem[]): Measure[] {
  const result: Measure[] = [];
  for (const { measure, style } of items) {
    const sortType = style?.sortType;
    const baseMeasure =
      sortType && isSortDirection(sortType)
        ? measure.sort(convertSortDirectionToSort(sortType))
        : measure;
    result.push(baseMeasure);

    if (style?.trend && !isTrendMeasure(measure)) {
      result.push(
        measureFactory.trend(measure, `${TREND_PREFIX}_${measure.name ?? 'Measure'}`, style.trend),
      );
    }
    if (style?.forecast && !isForecastMeasure(measure)) {
      result.push(
        measureFactory.forecast(
          measure,
          `${FORECAST_PREFIX}_${measure.name ?? 'Measure'}`,
          style.forecast,
        ),
      );
    }
  }
  return result;
}

/**
 * Translates NLQ JSON format to CSDK BaseQueryParams object.
 * Direction: JSON → CSDK
 *
 * Translate Query JSON generated by the new NLQ API to BaseQueryParams object.
 *
 * @example
 * {
     dimensions: ['DM.Category.Category', 'DM.Brand.Brand'],
     measures: [
       {
         function: 'measureFactory.sum',
         args: ['DM.Commerce.Revenue', 'Total Revenue'],
       },
       {
         function: 'measureFactory.sum',
         args: ['DM.Commerce.Cost', 'Total Cost'],
       },
     ],
     filters: [
       {
         function: 'filterFactory.members',
         args: ['DM.Commerce.Date.Years', ['2024-01-01T00:00:00']],
       },
       {
         function: 'filterFactory.topRanking',
         args: [
           'DM.Brand.Brand',
           {
             function: 'measureFactory.sum',
             args: ['DM.Commerce.Revenue', 'Total Revenue'],
           },
           5,
         ],
       },
     ],
   }
 *
 * is translated to the following Query object:
 * {success: true, data: {
  "dataSource": {
    "address": "LocalHost",
    "id": "localhost_aSampleIAAaECommerce",
    "title": "Sample ECommerce",
    "type": "elasticube",
  },
  "dimensions": [
    {
      "__serializable": "DimensionalAttribute",
      "composeCode": "DM.Category.Category",
      "dataSource": {
        "address": "LocalHost",
        "id": "localhost_aSampleIAAaECommerce",
        "live": false,
        "title": "Sample ECommerce",
      },
      "description": "",
      "expression": "[Category.Category]",
      "name": "Category",
      "type": "text-attribute",
    },
    {
      "__serializable": "DimensionalAttribute",
      "composeCode": "DM.Brand.Brand",
      "dataSource": {
        "address": "LocalHost",
        "id": "localhost_aSampleIAAaECommerce",
        "live": false,
        "title": "Sample ECommerce",
      },
      "description": "",
      "expression": "[Brand.Brand]",
      "name": "Brand",
      "type": "text-attribute",
    },
  ],
  "filters": [
    {
      "__serializable": "RankingFilter",
      "_name": "filter",
      "attribute": {
        "__serializable": "DimensionalAttribute",
        "composeCode": "DM.Brand.Brand",
        "dataSource": {
          "address": "LocalHost",
          "id": "localhost_aSampleIAAaECommerce",
          "live": false,
          "title": "Sample ECommerce",
        },
        "description": "",
        "expression": "[Brand.Brand]",
        "name": "Brand",
        "type": "text-attribute",
      },
      "composeCode": "filterFactory.topRanking(DM.Brand.Brand, measureFactory.sum(DM.Commerce.Revenue, 'Total Revenue'), 5)",
      "config": {
        "disabled": false,
        "locked": false,
      },
      "count": 5,
      "description": "",
      "filterType": "ranking",
      "isScope": true,
      "measure": {
        "__serializable": "DimensionalBaseMeasure",
        "aggregation": "sum",
        "attribute": {
          "__serializable": "DimensionalAttribute",
          "composeCode": "DM.Commerce.Revenue",
          "dataSource": {
            "address": "LocalHost",
            "id": "localhost_aSampleIAAaECommerce",
            "live": false,
            "title": "Sample ECommerce",
          },
          "description": "",
          "expression": "[Commerce.Revenue]",
          "name": "Revenue",
          "type": "numeric-attribute",
        },
        "composeCode": "measureFactory.sum(DM.Commerce.Revenue, 'Total Revenue')",
        "dataSource": undefined,
        "description": "",
        "name": "Total Revenue",
        "sort": 0,
        "type": "basemeasure",
      },
      "operator": "top",
      "type": "filter",
    },
    {
      "__serializable": "MembersFilter",
      "_name": "filter",
      "attribute": {
        "__serializable": "DimensionalLevelAttribute",
        "composeCode": "DM.Commerce.Date.Years",
        "dataSource": {
          "address": "LocalHost",
          "id": "localhost_aSampleIAAaECommerce",
          "live": false,
          "title": "Sample ECommerce",
        },
        "description": "",
        "expression": "[Commerce.Date]",
        "format": "yyyy",
        "granularity": "Years",
        "name": "Date",
        "type": "datelevel",
      },
      "composeCode": "filterFactory.members(DM.Commerce.Date.Years, ['2024-01-01T00:00:00'], { disabled: false, locked: false, excludeMembers: false, enableMultiSelection: true, deactivatedMembers: [] })",
      "config": {
        "deactivatedMembers": [],
        "disabled": false,
        "enableMultiSelection": true,
        "excludeMembers": false,
        "locked": false,
      },
      "description": "",
      "filterType": "members",
      "isScope": true,
      "members": [
        "2024-01-01T00:00:00",
      ],
      "type": "filter",
    },
  ],
  "measures": [
    {
      "__serializable": "DimensionalBaseMeasure",
      "aggregation": "sum",
      "attribute": {
        "__serializable": "DimensionalAttribute",
        "composeCode": "DM.Commerce.Revenue",
        "dataSource": {
          "address": "LocalHost",
          "id": "localhost_aSampleIAAaECommerce",
          "live": false,
          "title": "Sample ECommerce",
        },
        "description": "",
        "expression": "[Commerce.Revenue]",
        "name": "Revenue",
        "type": "numeric-attribute",
      },
      "composeCode": "measureFactory.sum(DM.Commerce.Revenue, 'Total Revenue')",
      "dataSource": undefined,
      "description": "",
      "name": "Total Revenue",
      "sort": 0,
      "type": "basemeasure",
    },
    {
      "__serializable": "DimensionalBaseMeasure",
      "aggregation": "sum",
      "attribute": {
        "__serializable": "DimensionalAttribute",
        "composeCode": "DM.Commerce.Cost",
        "dataSource": {
          "address": "LocalHost",
          "id": "localhost_aSampleIAAaECommerce",
          "live": false,
          "title": "Sample ECommerce",
        },
        "description": "",
        "expression": "[Commerce.Cost]",
        "name": "Cost",
        "type": "numeric-attribute",
      },
      "composeCode": "measureFactory.sum(DM.Commerce.Cost, 'Total Cost')",
      "dataSource": undefined,
      "description": "",
      "name": "Total Cost",
      "sort": 0,
      "type": "basemeasure",
    },
  ],
}}
 * @param input - QueryInput object
 * @returns NlqTranslationResult<BaseQueryParams>
 * @internal
 */
export const translateQueryFromJSON = (
  input: QueryInput,
): NlqTranslationResult<BaseQueryParams> => {
  const { data: queryJSON } = input;
  const { dataSource, tables } = input.context;

  // Create schema index once from tables for efficient lookups
  const schemaIndex = createSchemaIndex(tables);

  const translationErrors: NlqTranslationError[] = [];

  // Process each translation category
  const dimensionsResult = collectTranslationErrors<DimensionTranslationItem[]>(
    () =>
      translateDimensionsFromJSON({
        data: queryJSON.dimensions || [],
        context: { dataSource, schemaIndex },
      }),
    translationErrors,
  );

  const measuresResult = collectTranslationErrors<MeasureTranslationItem[]>(
    () =>
      translateMeasuresFromJSON({
        data: queryJSON.measures || [],
        context: { dataSource, schemaIndex },
      }),
    translationErrors,
  );

  const filters = collectTranslationErrors<Filter[] | FilterRelations>(
    () =>
      translateFiltersFromJSON({
        data: queryJSON.filters || [],
        context: { dataSource, schemaIndex },
      }),
    translationErrors,
  );

  let highlights = null;
  if (queryJSON.highlights) {
    highlights = collectTranslationErrors<Filter[]>(
      () =>
        translateHighlightsFromJSON({
          data: queryJSON.highlights || [],
          context: { dataSource, schemaIndex },
        }),
      translationErrors,
    );
  }

  // If any errors were collected, return structured error response
  if (translationErrors.length > 0) {
    return {
      success: false,
      errors: translationErrors,
    };
  }

  // Return successful result
  const result = {
    dataSource: convertDataSource(dataSource),
    dimensions: dimensionsResult ? adaptDimensionsForQuery(dimensionsResult) : [],
    measures: measuresResult ? adaptMeasuresForQuery(measuresResult) : [],
    filters: filters || [],
    ...(highlights && { highlights: highlights }),
  };

  return {
    success: true,
    data: result,
  };
};
