import { DashboardDto } from '@/api/types/dashboard-dto';

/**
 * Dashboard DTO with complex filtering config.
 */
export const complexDashboardDto = {
  _id: '665118e4feabf3002ae94bc3',
  title: 'Complex Dashboard',
  desc: '',
  source: null,
  type: 'dashboard',
  shares: [
    {
      shareId: '66298de3c09e52001c804146',
      type: 'user',
    },
  ],
  style: {
    palette: {
      _id: '66298de3c09e52001c804147',
      colors: ['#00cee6', '#9b9bd7', '#6EDA55', '#fc7570', '#fbb755', '#218A8C'],
      name: 'Vivid',
      isDefault: true,
      sortOrder: 10,
      isSystem: true,
      systemDefault: true,
    },
  },
  owner: '66298de3c09e52001c804146',
  userId: '66298de3c09e52001c804146',
  created: '2024-05-24T22:47:00.070Z',
  lastUpdated: '2024-05-24T22:47:17.855Z',
  lastUsed: '2024-05-24T22:47:11.325Z',
  usageCount: 1,
  layout: {
    type: 'columnar',
    columns: [
      {
        width: 21.096023564064804,
        cells: [
          {
            subcells: [
              {
                elements: [
                  {
                    minHeight: 48,
                    maxHeight: 1028,
                    minWidth: 48,
                    maxWidth: 1028,
                    defaultWidth: 512,
                    widgetid: '665118e4feabf3002ae94bb4',
                    height: '184px',
                  },
                ],
                width: 100,
                stretchable: false,
                pxlWidth: 229.078,
                index: 0,
              },
            ],
          },
          {
            subcells: [
              {
                elements: [
                  {
                    minHeight: 48,
                    maxHeight: 1028,
                    height: '172px',
                    minWidth: 48,
                    maxWidth: 1028,
                    defaultWidth: 512,
                    widgetid: '665118e4feabf3002ae94bb0',
                  },
                ],
                width: 100,
                stretchable: false,
                pxlWidth: 229.078,
                index: 0,
              },
            ],
          },
          {
            subcells: [
              {
                elements: [
                  {
                    minHeight: 48,
                    maxHeight: 1028,
                    height: '172px',
                    minWidth: 48,
                    maxWidth: 1028,
                    defaultWidth: 512,
                    widgetid: '665118e4feabf3002ae94bb2',
                  },
                ],
                width: 100,
                stretchable: false,
                pxlWidth: 229.078,
                index: 0,
              },
            ],
          },
          {
            subcells: [
              {
                elements: [
                  {
                    minHeight: 48,
                    maxHeight: 1028,
                    minWidth: 48,
                    maxWidth: 1028,
                    defaultWidth: 512,
                    widgetid: '665118e4feabf3002ae94baf',
                    height: '184px',
                  },
                ],
                width: 100,
                stretchable: false,
                pxlWidth: 229.078,
                index: 0,
              },
            ],
          },
        ],
        pxlWidth: 286.477,
        index: 0,
      },
      {
        width: 39.76532173231975,
        pxlWidth: 540.008,
        index: 1,
        cells: [
          {
            subcells: [
              {
                elements: [
                  {
                    minHeight: 96,
                    maxHeight: 2048,
                    minWidth: 128,
                    maxWidth: 2048,
                    height: '392px',
                    defaultWidth: 512,
                    widgetid: '665118e4feabf3002ae94bb6',
                  },
                ],
                width: 100,
                stretchable: false,
                pxlWidth: 597.406,
                index: 0,
              },
            ],
          },
          {
            subcells: [
              {
                elements: [
                  {
                    minHeight: 96,
                    maxHeight: 2048,
                    minWidth: 128,
                    maxWidth: 2048,
                    defaultWidth: 512,
                    widgetid: '665118e4feabf3002ae94bb3',
                    height: '384px',
                  },
                ],
                width: 50.25466893039049,
                stretchable: false,
                pxlWidth: 300.219,
                index: 0,
              },
              {
                elements: [
                  {
                    minHeight: 96,
                    maxHeight: 2048,
                    minWidth: 128,
                    maxWidth: 2048,
                    defaultWidth: 512,
                    widgetid: '665118e4feabf3002ae94bb1',
                    height: '384px',
                  },
                ],
                width: 49.745331069609506,
                stretchable: false,
                pxlWidth: 297.18,
                index: 1,
              },
            ],
          },
        ],
      },
      {
        width: 39.13865470361545,
        pxlWidth: 531.5,
        index: 2,
        cells: [
          {
            subcells: [
              {
                elements: [
                  {
                    minHeight: 96,
                    maxHeight: 2048,
                    minWidth: 128,
                    maxWidth: 2048,
                    height: '392px',
                    defaultWidth: 512,
                    widgetid: '665118e4feabf3002ae94bb5',
                  },
                ],
                width: 100,
                stretchable: false,
                pxlWidth: 531.5,
                index: 0,
              },
            ],
          },
          {
            subcells: [
              {
                elements: [
                  {
                    minHeight: 96,
                    maxHeight: 2048,
                    minWidth: 128,
                    maxWidth: 2048,
                    height: '384px',
                    defaultWidth: 512,
                    widgetid: '665118e4feabf3002ae94bb7',
                  },
                ],
                width: 100,
                stretchable: false,
                pxlWidth: 531.5,
                index: 0,
              },
            ],
          },
        ],
      },
    ],
    instanceid: '48BD5-068B-65',
    container: {
      sizzle1715569328956: {
        undefined: {
          parentNode: [1022.358638856522, 29, true],
        },
      },
    },
  },
  instanceType: 'owner',
  original: null,
  previewLayout: [],
  datasource: {
    address: 'LocalHost',
    title: 'Sample ECommerce',
    id: 'localhost_aSampleIAAaECommerce',
    database: 'aSampleIAAaECommerce',
  },
  editing: true,
  filters: [
    {
      jaql: {
        datasource: {
          title: 'Sample ECommerce',
          fullname: 'LocalHost/Sample ECommerce',
          id: 'localhost_aSampleIAAaECommerce',
          address: 'LocalHost',
          database: 'aSampleIAAaECommerce',
        },
        column: 'Date',
        dim: '[Commerce.Date (Calendar)]',
        datatype: 'datetime',
        level: 'years',
        title: 'YEARS',
        collapsed: true,
        isDashboardFilter: true,
        filter: {
          explicit: true,
          multiSelection: true,
          members: ['2013-01-01T00:00:00'],
        },
      },
      isCascading: false,
      disabled: false,
      instanceid: 'E8C9F-E07C-3B',
      locked: true,
    },
    {
      jaql: {
        datasource: {
          title: 'Sample ECommerce',
          fullname: 'LocalHost/Sample ECommerce',
          id: 'localhost_aSampleIAAaECommerce',
          address: 'LocalHost',
          database: 'aSampleIAAaECommerce',
        },
        column: 'Revenue',
        dim: '[Commerce.Revenue]',
        datatype: 'numeric',
        title: 'SALES REVENUE RANGE',
        collapsed: false,
        isDashboardFilter: true,
        filter: {
          fromNotEqual: 0,
        },
      },
      isCascading: false,
      instanceid: '4372A-1ED5-30',
      disabled: true,
    },
    {
      instanceid: '84A13-99E5-68',
      isCascading: true,
      levels: [
        {
          table: 'Category',
          column: 'Category',
          dim: '[Category.Category]',
          datatype: 'text',
          merged: true,
          datasource: {
            address: 'LocalHost',
            title: 'Sample ECommerce',
            id: 'localhost_aSampleIAAaECommerce',
            database: 'aSampleIAAaECommerce',
          },
          firstday: 'mon',
          locale: 'en-us',
          title: 'Category',
          collapsed: true,
          isDashboardFilter: true,
          panel: 'scope',
          instanceid: '84A13-99E5-68',
          filter: {
            explicit: true,
            multiSelection: true,
            members: ['Apple Mac Desktops', 'Apple Mac Laptops'],
          },
        },
        {
          table: 'Brand',
          column: 'Brand',
          dim: '[Brand.Brand]',
          datatype: 'text',
          merged: true,
          datasource: {
            address: 'LocalHost',
            title: 'Sample ECommerce',
            id: 'localhost_aSampleIAAaECommerce',
            database: 'aSampleIAAaECommerce',
          },
          firstday: 'mon',
          locale: 'en-us',
          title: 'Brand',
          collapsed: true,
          instanceid: '5F236-CBCB-2F',
          isDashboardFilter: true,
          panel: 'scope',
          filter: {
            explicit: true,
            multiSelection: true,
            members: ['ABC', 'APPLES', 'LONY'],
          },
        },
        {
          table: 'Commerce',
          column: 'Condition',
          dim: '[Commerce.Condition]',
          datatype: 'text',
          merged: true,
          datasource: {
            address: 'LocalHost',
            title: 'Sample ECommerce',
            id: 'localhost_aSampleIAAaECommerce',
            database: 'aSampleIAAaECommerce',
          },
          firstday: 'mon',
          locale: 'en-us',
          title: 'Condition',
          collapsed: true,
          instanceid: '4B317-BF27-2E',
          isDashboardFilter: true,
          filter: {
            explicit: true,
            multiSelection: true,
            members: ['Refurbished', 'Unspecified'],
          },
        },
      ],
      model: {
        instanceid: '6059B-D241-1B',
        __store: ['[Category.Category]', '[Brand.Brand]', '[Commerce.Condition]'],
      },
      disabled: false,
      locked: false,
    },
    {
      jaql: {
        table: 'Commerce',
        column: 'Age Range',
        dim: '[Commerce.Age Range]',
        datatype: 'text',
        merged: true,
        datasource: {
          address: 'LocalHost',
          title: 'Sample ECommerce',
          id: 'localhost_aSampleIAAaECommerce',
          database: 'aSampleIAAaECommerce',
        },
        firstday: 'mon',
        locale: 'en-us',
        title: 'Age Range',
        collapsed: true,
        isDashboardFilter: true,
        filter: {
          explicit: true,
          multiSelection: true,
          members: ['35-44', '65+', '19-24'],
          filter: {
            explicit: true,
            multiSelection: true,
            members: ['19-24', '35-44', '55-64', '65+'],
          },
        },
      },
      instanceid: 'F58BC-C4A7-B2',
      isCascading: false,
      disabled: false,
    },
  ],
  isPublic: null,
  oid: '665118e4feabf3002ae94bae',
  options: {
    manual: false,
  },
  parentFolder: null,
  lastOpened: '2024-05-24T22:47:00.556Z',
  settings: {
    autoUpdateOnFiltersChange: true,
    useAcceleration: false,
  },
  autoUpdateOnFiltersChange: true,
  useAcceleration: false,
  filterRelations: [
    {
      datasource: 'Sample ECommerce',
      filterRelations: {
        type: 'LogicalExpression',
        operator: 'AND',
        left: {
          type: 'LogicalExpression',
          operator: 'AND',
          left: {
            type: 'ParenthesizedLogicalExpression',
            value: {
              type: 'LogicalExpression',
              operator: 'OR',
              left: {
                type: 'Identifier',
                instanceId: 'E8C9F-E07C-3B',
              },
              right: {
                type: 'Identifier',
                instanceId: '4372A-1ED5-30',
              },
            },
          },
          right: {
            type: 'CascadingIdentifier',
            levels: [
              {
                type: 'Identifier',
                instanceId: '84A13-99E5-68',
              },
              {
                type: 'Identifier',
                instanceId: '5F236-CBCB-2F',
              },
              {
                type: 'Identifier',
                instanceId: '4B317-BF27-2E',
              },
            ],
          },
        },
        right: {
          type: 'Identifier',
          instanceId: 'F58BC-C4A7-B2',
        },
      },
    },
  ],
  filterToDatasourceMapping: {},
  tenantId: '66298de3c09e52001c804153',
  widgets: [
    {
      _id: '665118e4feabf3002ae94bc4',
      title: 'TOTAL BRANDS',
      type: 'indicator',
      subtype: 'indicator/gauge',
      oid: '665118e4feabf3002ae94baf',
      desc: null,
      source: null,
      owner: '66298de3c09e52001c804146',
      userId: '66298de3c09e52001c804146',
      created: '2024-05-24T22:47:00.070Z',
      lastUpdated: '2024-05-24T22:47:00.070Z',
      instanceType: 'owner',
      datasource: {
        address: 'LocalHost',
        title: 'Sample ECommerce',
        id: 'localhost_aSampleIAAaECommerce',
        database: 'aSampleIAAaECommerce',
      },
      selection: null,
      metadata: {
        ignore: {
          dimensions: [],
          ids: [],
          all: false,
        },
        panels: [
          {
            name: 'value',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Brand ID',
                  dim: '[Commerce.Brand ID]',
                  datatype: 'numeric',
                  merged: true,
                  agg: 'count',
                  title: '# of unique Brand ID',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: false,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                  color: {
                    type: 'color',
                  },
                },
              },
            ],
          },
          {
            name: 'secondary',
            items: [],
          },
          {
            name: 'min',
            items: [
              {
                jaql: {
                  formula: '0',
                  title: '0 (default)',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: false,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                },
              },
            ],
          },
          {
            name: 'max',
            items: [
              {
                jaql: {
                  type: 'measure',
                  formula: '2500',
                  context: {},
                  title: '2500',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: false,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                },
              },
            ],
          },
          {
            name: 'filters',
            items: [],
          },
        ],
      },
      dashboardid: '665118e4feabf3002ae94bae',
      options: {
        title: false,
        dashboardFiltersMode: 'filter',
        selector: false,
        allowSelector: false,
        disallowSelector: true,
        triggersDomready: true,
        noTitle: false,
      },
      size: 'big',
      style: {
        'indicator/pictogram': {},
        subtype: 'round',
        'indicator/numeric': {
          subtype: 'simple',
          skin: '1',
          components: {
            title: {
              inactive: false,
              enabled: true,
            },
            icon: {
              inactive: false,
              enabled: true,
            },
            secondaryTitle: {
              inactive: true,
              enabled: true,
            },
          },
        },
        skin: '1',
        'indicator/gauge': {
          subtype: 'round',
          skin: '1',
          components: {
            ticks: {
              inactive: false,
              enabled: true,
            },
            labels: {
              inactive: false,
              enabled: true,
            },
            title: {
              inactive: false,
              enabled: true,
            },
            secondaryTitle: {
              inactive: true,
              enabled: true,
            },
          },
        },
        components: {
          ticks: {
            inactive: false,
            enabled: true,
          },
          labels: {
            inactive: false,
            enabled: true,
          },
          title: {
            inactive: false,
            enabled: false,
          },
          secondaryTitle: {
            inactive: true,
            enabled: true,
          },
        },
      },
      lastOpened: null,
      _dataSourcePermission: 'owner',
      userAuth: {
        dashboards: {
          create: true,
          delete: true,
          move: true,
          rename: true,
          duplicate: true,
          change_owner: true,
          toggle_edit_mode: true,
          edit_layout: true,
          edit_script: true,
          export_dash: true,
          export_jpeg: true,
          export_image: true,
          export_pdf: true,
          share: true,
          restore: true,
          copy_to_server: true,
          import: true,
          select_palette: true,
          replace_datasource: true,
          undo_import_dash: true,
          toggleDataExploration: true,
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            reorder: true,
            modify_type: true,
            toggle_auto_update: true,
            set_defaults: true,
            advanced: true,
            use_starred: true,
            modify_filter_relationship: true,
          },
        },
        widgets: {
          create: true,
          delete: true,
          rename: true,
          duplicate: true,
          copy_to_dashboard: true,
          edit: true,
          edit_script: true,
          change_type: true,
          export_csv: true,
          export_png: true,
          export_svg: true,
          export_pdf: true,
          modify_selection_attrs: true,
          modify_selection_mode: true,
          drill_to_anywhere: true,
          add_to_pulse: true,
          items: {
            create: true,
            delete: true,
            rename: true,
            modify: true,
            reorder: true,
            modify_type: true,
            modify_format: true,
            on_off: true,
            select_hierarchies: true,
          },
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            modify_layout: true,
            modify_type: true,
            modify_dashboard_filters: true,
            use_starred: true,
          },
          widgetViewOnly: false,
        },
        base: {
          isConsumer: false,
          isContributor: false,
          isAdmin: false,
          isSuper: true,
        },
      },
      _toDisableOptionsList: {
        widgets: {
          duplicate: false,
        },
      },
    },
    {
      _id: '665118e4feabf3002ae94bc5',
      title: 'TOTAL UNITS SOLD',
      type: 'indicator',
      subtype: 'indicator/gauge',
      oid: '665118e4feabf3002ae94bb0',
      desc: null,
      source: null,
      owner: '66298de3c09e52001c804146',
      userId: '66298de3c09e52001c804146',
      created: '2024-05-24T22:47:00.070Z',
      lastUpdated: '2024-05-24T22:47:00.070Z',
      instanceType: 'owner',
      datasource: {
        address: 'LocalHost',
        title: 'Sample ECommerce',
        id: 'localhost_aSampleIAAaECommerce',
        database: 'aSampleIAAaECommerce',
      },
      selection: null,
      metadata: {
        ignore: {
          dimensions: [],
          ids: [],
          all: false,
        },
        panels: [
          {
            name: 'value',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Quantity',
                  dim: '[Commerce.Quantity]',
                  datatype: 'numeric',
                  agg: 'sum',
                  title: 'Total Quantity',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: false,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                  color: {
                    type: 'color',
                  },
                },
              },
            ],
          },
          {
            name: 'secondary',
            items: [],
          },
          {
            name: 'min',
            items: [
              {
                jaql: {
                  formula: '0',
                  title: '0 (default)',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: false,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                },
              },
            ],
          },
          {
            name: 'max',
            items: [
              {
                jaql: {
                  type: 'measure',
                  formula: '250000',
                  context: {},
                  title: '250000',
                },
                format: {
                  mask: {
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: true,
                    },
                    decimals: 'auto',
                    number: {
                      separated: true,
                    },
                    currency: null,
                    percent: null,
                    type: null,
                  },
                },
              },
            ],
          },
          {
            name: 'filters',
            items: [],
          },
        ],
      },
      dashboardid: '665118e4feabf3002ae94bae',
      options: {
        title: false,
        dashboardFiltersMode: 'filter',
        selector: false,
        allowSelector: false,
        disallowSelector: true,
        triggersDomready: true,
        noTitle: false,
      },
      size: 'big',
      style: {
        'indicator/pictogram': {},
        subtype: 'round',
        'indicator/numeric': {
          subtype: 'simple',
          skin: '1',
          components: {
            title: {
              inactive: false,
              enabled: true,
            },
            icon: {
              inactive: false,
              enabled: true,
            },
            secondaryTitle: {
              inactive: true,
              enabled: true,
            },
          },
        },
        skin: '1',
        'indicator/gauge': {
          subtype: 'round',
          skin: '1',
          components: {
            ticks: {
              inactive: false,
              enabled: true,
            },
            labels: {
              inactive: false,
              enabled: true,
            },
            title: {
              inactive: false,
              enabled: true,
            },
            secondaryTitle: {
              inactive: true,
              enabled: true,
            },
          },
        },
        components: {
          ticks: {
            inactive: false,
            enabled: true,
          },
          labels: {
            inactive: false,
            enabled: true,
          },
          title: {
            inactive: false,
            enabled: false,
          },
          secondaryTitle: {
            inactive: true,
            enabled: true,
          },
        },
      },
      lastOpened: null,
      _dataSourcePermission: 'owner',
      userAuth: {
        dashboards: {
          create: true,
          delete: true,
          move: true,
          rename: true,
          duplicate: true,
          change_owner: true,
          toggle_edit_mode: true,
          edit_layout: true,
          edit_script: true,
          export_dash: true,
          export_jpeg: true,
          export_image: true,
          export_pdf: true,
          share: true,
          restore: true,
          copy_to_server: true,
          import: true,
          select_palette: true,
          replace_datasource: true,
          undo_import_dash: true,
          toggleDataExploration: true,
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            reorder: true,
            modify_type: true,
            toggle_auto_update: true,
            set_defaults: true,
            advanced: true,
            use_starred: true,
            modify_filter_relationship: true,
          },
        },
        widgets: {
          create: true,
          delete: true,
          rename: true,
          duplicate: true,
          copy_to_dashboard: true,
          edit: true,
          edit_script: true,
          change_type: true,
          export_csv: true,
          export_png: true,
          export_svg: true,
          export_pdf: true,
          modify_selection_attrs: true,
          modify_selection_mode: true,
          drill_to_anywhere: true,
          add_to_pulse: true,
          items: {
            create: true,
            delete: true,
            rename: true,
            modify: true,
            reorder: true,
            modify_type: true,
            modify_format: true,
            on_off: true,
            select_hierarchies: true,
          },
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            modify_layout: true,
            modify_type: true,
            modify_dashboard_filters: true,
            use_starred: true,
          },
          widgetViewOnly: false,
        },
        base: {
          isConsumer: false,
          isContributor: false,
          isAdmin: false,
          isSuper: true,
        },
      },
      _toDisableOptionsList: {
        widgets: {
          duplicate: false,
        },
      },
    },
    {
      _id: '665118e4feabf3002ae94bc6',
      title: 'AGE RANGE BREAKDOWN',
      type: 'chart/pie',
      subtype: 'pie/classic',
      oid: '665118e4feabf3002ae94bb1',
      desc: null,
      source: null,
      owner: '66298de3c09e52001c804146',
      userId: '66298de3c09e52001c804146',
      created: '2024-05-24T22:47:00.070Z',
      lastUpdated: '2024-05-24T22:47:00.070Z',
      instanceType: 'owner',
      datasource: {
        address: 'LocalHost',
        title: 'Sample ECommerce',
        id: 'localhost_aSampleIAAaECommerce',
        database: 'aSampleIAAaECommerce',
      },
      selection: null,
      metadata: {
        ignore: {
          dimensions: [],
          ids: [],
          all: false,
        },
        panels: [
          {
            name: 'categories',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Age Range',
                  dim: '[Commerce.Age Range]',
                  datatype: 'text',
                  merged: true,
                  title: 'Age Range',
                },
                format: {},
              },
            ],
          },
          {
            name: 'values',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Revenue',
                  dim: '[Commerce.Revenue]',
                  datatype: 'numeric',
                  agg: 'sum',
                  title: 'Total Revenue',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: true,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                },
              },
            ],
          },
          {
            name: 'filters',
            items: [
              {
                jaql: {
                  datasource: {
                    title: 'Sample ECommerce',
                    fullname: 'LocalHost/Sample ECommerce',
                    id: 'localhost_aSampleIAAaECommerce',
                    address: 'LocalHost',
                    database: 'aSampleIAAaECommerce',
                  },
                  column: 'Gender',
                  dim: '[Commerce.Gender]',
                  datatype: 'text',
                  filter: {
                    explicit: false,
                    multiSelection: true,
                    exclude: {
                      members: ['Unspecified'],
                    },
                  },
                  title: 'Gender',
                  collapsed: true,
                },
                format: {
                  mask: {
                    isdefault: true,
                  },
                },
              },
            ],
          },
        ],
      },
      dashboardid: '665118e4feabf3002ae94bae',
      options: {
        dashboardFiltersMode: 'select',
        selector: true,
        triggersDomready: true,
      },
      style: {
        legend: {
          enabled: false,
          position: 'bottom',
        },
        labels: {
          enabled: true,
          categories: true,
          value: false,
          percent: true,
          decimals: false,
        },
        dataLimits: {
          seriesCapacity: 100000,
        },
      },
      lastOpened: null,
      _dataSourcePermission: 'owner',
      userAuth: {
        dashboards: {
          create: true,
          delete: true,
          move: true,
          rename: true,
          duplicate: true,
          change_owner: true,
          toggle_edit_mode: true,
          edit_layout: true,
          edit_script: true,
          export_dash: true,
          export_jpeg: true,
          export_image: true,
          export_pdf: true,
          share: true,
          restore: true,
          copy_to_server: true,
          import: true,
          select_palette: true,
          replace_datasource: true,
          undo_import_dash: true,
          toggleDataExploration: true,
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            reorder: true,
            modify_type: true,
            toggle_auto_update: true,
            set_defaults: true,
            advanced: true,
            use_starred: true,
            modify_filter_relationship: true,
          },
        },
        widgets: {
          create: true,
          delete: true,
          rename: true,
          duplicate: true,
          copy_to_dashboard: true,
          edit: true,
          edit_script: true,
          change_type: true,
          export_csv: true,
          export_png: true,
          export_svg: true,
          export_pdf: true,
          modify_selection_attrs: true,
          modify_selection_mode: true,
          drill_to_anywhere: true,
          add_to_pulse: true,
          items: {
            create: true,
            delete: true,
            rename: true,
            modify: true,
            reorder: true,
            modify_type: true,
            modify_format: true,
            on_off: true,
            select_hierarchies: true,
          },
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            modify_layout: true,
            modify_type: true,
            modify_dashboard_filters: true,
            use_starred: true,
          },
          widgetViewOnly: false,
        },
        base: {
          isConsumer: false,
          isContributor: false,
          isAdmin: false,
          isSuper: true,
        },
      },
      _toDisableOptionsList: {
        widgets: {
          duplicate: false,
        },
      },
    },
    {
      _id: '665118e4feabf3002ae94bc7',
      title: 'TOTAL SALES',
      type: 'indicator',
      subtype: 'indicator/gauge',
      oid: '665118e4feabf3002ae94bb2',
      desc: null,
      source: null,
      owner: '66298de3c09e52001c804146',
      userId: '66298de3c09e52001c804146',
      created: '2024-05-24T22:47:00.070Z',
      lastUpdated: '2024-05-24T22:47:00.070Z',
      instanceType: 'owner',
      datasource: {
        address: 'LocalHost',
        title: 'Sample ECommerce',
        id: 'localhost_aSampleIAAaECommerce',
        database: 'aSampleIAAaECommerce',
      },
      selection: null,
      metadata: {
        ignore: {
          dimensions: [],
          ids: [],
          all: false,
        },
        panels: [
          {
            name: 'value',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Visit ID',
                  dim: '[Commerce.Visit ID]',
                  datatype: 'numeric',
                  agg: 'countduplicates',
                  title: '# of Visit ID',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: false,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                  color: {
                    type: 'color',
                  },
                },
              },
            ],
          },
          {
            name: 'secondary',
            items: [],
          },
          {
            name: 'min',
            items: [
              {
                jaql: {
                  formula: '0',
                  title: '0 (default)',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: false,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                },
              },
            ],
          },
          {
            name: 'max',
            items: [
              {
                jaql: {
                  type: 'measure',
                  formula: '100000',
                  context: {},
                  title: '100000',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: false,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                },
              },
            ],
          },
          {
            name: 'filters',
            items: [],
          },
        ],
      },
      dashboardid: '665118e4feabf3002ae94bae',
      options: {
        title: false,
        dashboardFiltersMode: 'filter',
        selector: false,
        allowSelector: false,
        disallowSelector: true,
        triggersDomready: true,
        noTitle: false,
      },
      size: 'big',
      style: {
        'indicator/gauge': {
          subtype: 'round',
          skin: '1',
          components: {
            ticks: {
              inactive: false,
              enabled: true,
            },
            labels: {
              inactive: false,
              enabled: true,
            },
            title: {
              inactive: false,
              enabled: true,
            },
            secondaryTitle: {
              inactive: true,
              enabled: true,
            },
          },
        },
        'indicator/numeric': {
          subtype: 'simple',
          skin: '1',
          components: {
            title: {
              inactive: false,
              enabled: true,
            },
            icon: {
              inactive: false,
              enabled: true,
            },
            secondaryTitle: {
              inactive: true,
              enabled: true,
            },
          },
        },
        skin: '1',
        subtype: 'round',
        'indicator/pictogram': {},
        components: {
          ticks: {
            inactive: false,
            enabled: true,
          },
          labels: {
            inactive: false,
            enabled: true,
          },
          title: {
            inactive: false,
            enabled: false,
          },
          secondaryTitle: {
            inactive: true,
            enabled: true,
          },
        },
      },
      lastOpened: null,
      _dataSourcePermission: 'owner',
      userAuth: {
        dashboards: {
          create: true,
          delete: true,
          move: true,
          rename: true,
          duplicate: true,
          change_owner: true,
          toggle_edit_mode: true,
          edit_layout: true,
          edit_script: true,
          export_dash: true,
          export_jpeg: true,
          export_image: true,
          export_pdf: true,
          share: true,
          restore: true,
          copy_to_server: true,
          import: true,
          select_palette: true,
          replace_datasource: true,
          undo_import_dash: true,
          toggleDataExploration: true,
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            reorder: true,
            modify_type: true,
            toggle_auto_update: true,
            set_defaults: true,
            advanced: true,
            use_starred: true,
            modify_filter_relationship: true,
          },
        },
        widgets: {
          create: true,
          delete: true,
          rename: true,
          duplicate: true,
          copy_to_dashboard: true,
          edit: true,
          edit_script: true,
          change_type: true,
          export_csv: true,
          export_png: true,
          export_svg: true,
          export_pdf: true,
          modify_selection_attrs: true,
          modify_selection_mode: true,
          drill_to_anywhere: true,
          add_to_pulse: true,
          items: {
            create: true,
            delete: true,
            rename: true,
            modify: true,
            reorder: true,
            modify_type: true,
            modify_format: true,
            on_off: true,
            select_hierarchies: true,
          },
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            modify_layout: true,
            modify_type: true,
            modify_dashboard_filters: true,
            use_starred: true,
          },
          widgetViewOnly: false,
        },
        base: {
          isConsumer: false,
          isContributor: false,
          isAdmin: false,
          isSuper: true,
        },
      },
      _toDisableOptionsList: {
        widgets: {
          duplicate: false,
        },
      },
    },
    {
      _id: '665118e4feabf3002ae94bc8',
      title: 'GENDER BREAKDOWN',
      type: 'chart/pie',
      subtype: 'pie/classic',
      oid: '665118e4feabf3002ae94bb3',
      desc: null,
      source: null,
      owner: '66298de3c09e52001c804146',
      userId: '66298de3c09e52001c804146',
      created: '2024-05-24T22:47:00.070Z',
      lastUpdated: '2024-05-24T22:47:00.070Z',
      instanceType: 'owner',
      datasource: {
        address: 'LocalHost',
        title: 'Sample ECommerce',
        id: 'localhost_aSampleIAAaECommerce',
        database: 'aSampleIAAaECommerce',
      },
      selection: null,
      metadata: {
        ignore: {
          dimensions: [],
          ids: ['84A13-99E5-68', '4372A-1ED5-30'],
          all: false,
        },
        panels: [
          {
            name: 'categories',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Gender',
                  dim: '[Commerce.Gender]',
                  datatype: 'text',
                  merged: true,
                  title: 'Gender',
                },
                format: {
                  members: {},
                },
                instanceid: '84A51-B4B2-F6',
              },
            ],
          },
          {
            name: 'values',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Revenue',
                  dim: '[Commerce.Revenue]',
                  datatype: 'numeric',
                  agg: 'sum',
                  title: 'Total Revenue',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: true,
                    },
                    separated: true,
                    decimals: 'auto',
                    abbreviateAll: false,
                    isdefault: true,
                  },
                },
                instanceid: '40E21-B286-47',
              },
            ],
          },
          {
            name: 'filters',
            items: [
              {
                jaql: {
                  datasource: {
                    title: 'Sample ECommerce',
                    fullname: 'LocalHost/Sample ECommerce',
                    id: 'localhost_aSampleIAAaECommerce',
                    address: 'LocalHost',
                    database: 'aSampleIAAaECommerce',
                  },
                  column: 'Gender',
                  dim: '[Commerce.Gender]',
                  datatype: 'text',
                  filter: {
                    explicit: false,
                    multiSelection: true,
                    exclude: {
                      members: ['Unspecified'],
                    },
                  },
                  title: 'Gender',
                  collapsed: true,
                },
                format: {
                  mask: {
                    isdefault: true,
                  },
                },
                instanceid: '6A370-BA2B-D6',
              },
            ],
          },
        ],
        usedFormulasMapping: {},
      },
      dashboardid: '665118e4feabf3002ae94bae',
      options: {
        dashboardFiltersMode: 'select',
        selector: true,
        triggersDomready: true,
        autoUpdateOnEveryChange: true,
        drillToAnywhere: true,
        selectorLocked: false,
      },
      style: {
        legend: {
          enabled: false,
          position: 'left',
        },
        labels: {
          enabled: true,
          categories: true,
          value: false,
          percent: true,
          decimals: false,
          fontFamily: 'Open Sans',
          color: 'red',
        },
        dataLimits: {
          seriesCapacity: 100000,
        },
        convolution: {
          enabled: true,
          selectedConvolutionType: 'byPercentage',
          minimalIndependentSlicePercentage: 3,
          independentSlicesCount: 7,
        },
        narration: {
          enabled: false,
          display: 'above',
          format: 'bullets',
          verbosity: 'medium',
          up_sentiment: 'good',
          aggregation: 'sum',
          labels: [
            {
              id: 'gender',
              title: 'Gender',
              singular: 'Gender',
              plural: 'Gender',
            },
          ],
        },
      },
      lastOpened: null,
      drillToDashboardConfig: {
        drilledDashboardPrefix: '_drill',
        drilledDashboardsFolderPrefix: '',
        displayFilterPane: true,
        displayDashboardsPane: true,
        displayToolbarRow: true,
        displayHeaderRow: true,
        volatile: false,
        hideDrilledDashboards: true,
        hideSharedDashboardsForNonOwner: true,
        drillToDashboardMenuCaption: 'Jump to dashboard',
        drillToDashboardRightMenuCaption: 'Jump to ',
        drillToDashboardNavigateType: 1,
        drillToDashboardNavigateTypePivot: 2,
        drillToDashboardNavigateTypeCharts: 1,
        drillToDashboardNavigateTypeOthers: 3,
        excludeFilterDims: [],
        includeFilterDims: [],
        drilledDashboardDisplayType: 2,
        dashboardIds: [],
        modalWindowResize: false,
        showFolderNameOnMenuSelection: false,
        resetDashFiltersAfterJTD: false,
        sameCubeRestriction: true,
        showJTDIcon: true,
        sendPieChartMeasureFiltersOnClick: true,
        forceZeroInsteadNull: false,
        mergeTargetDashboardFilters: false,
        drillToDashboardByName: false,
        sendBreakByValueFilter: true,
        ignoreFiltersSource: false,
      },
      instanceid: '47B9C-0CA0-D3',
      realTimeRefreshing: false,
      viewState: {
        activeTab: 'filters',
      },
      _dataSourcePermission: 'owner',
      userAuth: {
        dashboards: {
          create: true,
          delete: true,
          move: true,
          rename: true,
          duplicate: true,
          change_owner: true,
          toggle_edit_mode: true,
          edit_layout: true,
          edit_script: true,
          export_dash: true,
          export_jpeg: true,
          export_image: true,
          export_pdf: true,
          share: true,
          restore: true,
          copy_to_server: true,
          import: true,
          select_palette: true,
          replace_datasource: true,
          undo_import_dash: true,
          toggleDataExploration: true,
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            reorder: true,
            modify_type: true,
            toggle_auto_update: true,
            set_defaults: true,
            advanced: true,
            use_starred: true,
            modify_filter_relationship: true,
          },
        },
        widgets: {
          create: true,
          delete: true,
          rename: true,
          duplicate: true,
          copy_to_dashboard: true,
          edit: true,
          edit_script: true,
          change_type: true,
          export_csv: true,
          export_png: true,
          export_svg: true,
          export_pdf: true,
          modify_selection_attrs: true,
          modify_selection_mode: true,
          drill_to_anywhere: true,
          add_to_pulse: true,
          items: {
            create: true,
            delete: true,
            rename: true,
            modify: true,
            reorder: true,
            modify_type: true,
            modify_format: true,
            on_off: true,
            select_hierarchies: true,
          },
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            modify_layout: true,
            modify_type: true,
            modify_dashboard_filters: true,
            use_starred: true,
          },
          widgetViewOnly: false,
        },
        base: {
          isConsumer: false,
          isContributor: false,
          isAdmin: false,
          isSuper: true,
        },
      },
      _toDisableOptionsList: {
        widgets: {
          duplicate: false,
        },
      },
    },
    {
      _id: '665118e4feabf3002ae94bc9',
      title: 'TOTAL REVENUE',
      type: 'indicator',
      subtype: 'indicator/gauge',
      oid: '665118e4feabf3002ae94bb4',
      desc: null,
      source: null,
      owner: '66298de3c09e52001c804146',
      userId: '66298de3c09e52001c804146',
      created: '2024-05-24T22:47:00.070Z',
      lastUpdated: '2024-05-24T22:47:00.070Z',
      instanceType: 'owner',
      datasource: {
        address: 'LocalHost',
        title: 'Sample ECommerce',
        id: 'localhost_aSampleIAAaECommerce',
        database: 'aSampleIAAaECommerce',
      },
      selection: null,
      metadata: {
        ignore: {
          dimensions: [],
          ids: [],
          all: false,
        },
        panels: [
          {
            name: 'value',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Revenue',
                  dim: '[Commerce.Revenue]',
                  datatype: 'numeric',
                  agg: 'sum',
                  title: 'Total Revenue',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: false,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                  color: {
                    type: 'color',
                  },
                },
              },
            ],
          },
          {
            name: 'secondary',
            items: [],
          },
          {
            name: 'min',
            items: [
              {
                jaql: {
                  formula: '0',
                  title: '0 (default)',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: false,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                },
              },
            ],
          },
          {
            name: 'max',
            items: [
              {
                jaql: {
                  type: 'measure',
                  formula: '125000000',
                  context: {},
                  title: '125000000',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: false,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                },
              },
            ],
          },
          {
            name: 'filters',
            items: [],
          },
        ],
      },
      dashboardid: '665118e4feabf3002ae94bae',
      options: {
        title: false,
        dashboardFiltersMode: 'filter',
        selector: false,
        allowSelector: false,
        disallowSelector: true,
        triggersDomready: true,
        noTitle: false,
      },
      size: 'big',
      style: {
        'indicator/gauge': {
          subtype: 'round',
          skin: '1',
          components: {
            ticks: {
              inactive: false,
              enabled: true,
            },
            labels: {
              inactive: false,
              enabled: true,
            },
            title: {
              inactive: false,
              enabled: true,
            },
            secondaryTitle: {
              inactive: true,
              enabled: true,
            },
          },
        },
        'indicator/numeric': {
          subtype: 'simple',
          skin: '1',
          components: {
            title: {
              inactive: false,
              enabled: true,
            },
            icon: {
              inactive: false,
              enabled: true,
            },
            secondaryTitle: {
              inactive: true,
              enabled: true,
            },
          },
        },
        skin: '1',
        subtype: 'round',
        'indicator/pictogram': {},
        components: {
          ticks: {
            inactive: false,
            enabled: true,
          },
          labels: {
            inactive: false,
            enabled: true,
          },
          title: {
            inactive: false,
            enabled: false,
          },
          secondaryTitle: {
            inactive: true,
            enabled: true,
          },
        },
      },
      lastOpened: null,
      _dataSourcePermission: 'owner',
      userAuth: {
        dashboards: {
          create: true,
          delete: true,
          move: true,
          rename: true,
          duplicate: true,
          change_owner: true,
          toggle_edit_mode: true,
          edit_layout: true,
          edit_script: true,
          export_dash: true,
          export_jpeg: true,
          export_image: true,
          export_pdf: true,
          share: true,
          restore: true,
          copy_to_server: true,
          import: true,
          select_palette: true,
          replace_datasource: true,
          undo_import_dash: true,
          toggleDataExploration: true,
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            reorder: true,
            modify_type: true,
            toggle_auto_update: true,
            set_defaults: true,
            advanced: true,
            use_starred: true,
            modify_filter_relationship: true,
          },
        },
        widgets: {
          create: true,
          delete: true,
          rename: true,
          duplicate: true,
          copy_to_dashboard: true,
          edit: true,
          edit_script: true,
          change_type: true,
          export_csv: true,
          export_png: true,
          export_svg: true,
          export_pdf: true,
          modify_selection_attrs: true,
          modify_selection_mode: true,
          drill_to_anywhere: true,
          add_to_pulse: true,
          items: {
            create: true,
            delete: true,
            rename: true,
            modify: true,
            reorder: true,
            modify_type: true,
            modify_format: true,
            on_off: true,
            select_hierarchies: true,
          },
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            modify_layout: true,
            modify_type: true,
            modify_dashboard_filters: true,
            use_starred: true,
          },
          widgetViewOnly: false,
        },
        base: {
          isConsumer: false,
          isContributor: false,
          isAdmin: false,
          isSuper: true,
        },
      },
      _toDisableOptionsList: {
        widgets: {
          duplicate: false,
        },
      },
    },
    {
      _id: '665118e4feabf3002ae94bca',
      title: 'TOP CATEGORIES BY REVENUE, UNITS SOLD AND GENDER',
      type: 'chart/scatter',
      subtype: 'bubble/scatter',
      oid: '665118e4feabf3002ae94bb5',
      desc: null,
      source: null,
      owner: '66298de3c09e52001c804146',
      userId: '66298de3c09e52001c804146',
      created: '2024-05-24T22:47:00.070Z',
      lastUpdated: '2024-05-24T22:47:00.070Z',
      instanceType: 'owner',
      datasource: {
        address: 'LocalHost',
        title: 'Sample ECommerce',
        id: 'localhost_aSampleIAAaECommerce',
        database: 'aSampleIAAaECommerce',
      },
      selection: null,
      metadata: {
        ignore: {
          dimensions: [],
          ids: [],
          all: false,
        },
        panels: [
          {
            name: 'x-axis',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Revenue',
                  dim: '[Commerce.Revenue]',
                  datatype: 'numeric',
                  agg: 'sum',
                  title: 'Total Revenue',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: true,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                },
              },
            ],
          },
          {
            name: 'y-axis',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Quantity',
                  dim: '[Commerce.Quantity]',
                  datatype: 'numeric',
                  agg: 'sum',
                  title: 'Total Quantity',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: true,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                },
              },
            ],
          },
          {
            name: 'point',
            items: [
              {
                jaql: {
                  table: 'category',
                  column: 'Category',
                  dim: '[Category.Category]',
                  datatype: 'text',
                  merged: true,
                  title: 'Category',
                },
              },
            ],
          },
          {
            name: 'Break By / Color',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Gender',
                  dim: '[Commerce.Gender]',
                  datatype: 'text',
                  merged: true,
                  title: 'Gender',
                },
                format: {},
              },
            ],
          },
          {
            name: 'size',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Cost',
                  dim: '[Commerce.Cost]',
                  datatype: 'numeric',
                  agg: 'sum',
                  title: 'Total Cost',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: true,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                },
              },
            ],
          },
          {
            name: 'filters',
            items: [
              {
                jaql: {
                  datasource: {
                    title: 'Sample ECommerce',
                    fullname: 'LocalHost/Sample ECommerce',
                    id: 'localhost_aSampleIAAaECommerce',
                    address: 'LocalHost',
                    database: 'aSampleIAAaECommerce',
                  },
                  column: 'Gender',
                  dim: '[Commerce.Gender]',
                  datatype: 'text',
                  filter: {
                    explicit: false,
                    multiSelection: true,
                    exclude: {
                      members: ['Unspecified'],
                    },
                  },
                  title: 'Gender',
                  collapsed: true,
                },
                format: {
                  mask: {
                    isdefault: true,
                  },
                },
              },
              {
                jaql: {
                  datasource: {
                    title: 'Sample ECommerce',
                    fullname: 'LocalHost/Sample ECommerce',
                    id: 'localhost_aSampleIAAaECommerce',
                    address: 'LocalHost',
                    database: 'aSampleIAAaECommerce',
                  },
                  column: 'Category',
                  dim: '[Category.Category]',
                  datatype: 'text',
                  title: 'Category',
                  filter: {
                    top: 10,
                    by: {
                      column: 'Revenue',
                      dim: '[Commerce.Revenue]',
                      datatype: 'numeric',
                      agg: 'sum',
                      title: 'Total Revenue',
                    },
                  },
                  collapsed: false,
                },
                format: {
                  mask: {
                    isdefault: true,
                  },
                },
              },
            ],
          },
        ],
      },
      dashboardid: '665118e4feabf3002ae94bae',
      options: {
        dashboardFiltersMode: 'select',
        selector: false,
        triggersDomready: true,
      },
      style: {
        legend: {
          enabled: true,
          position: 'right',
        },
        seriesLabels: {
          enabled: false,
          rotation: 0,
        },
        markerSize: {
          min: 12,
          max: 48,
          isRange: true,
          lowest: 10,
          highest: 60,
          step: 1,
          defaultSize: 10,
        },
        xAxis: {
          enabled: true,
          ticks: true,
          labels: {
            enabled: true,
            rotation: 0,
          },
          gridLines: false,
          logarithmic: true,
          title: {
            enabled: false,
            text: 'SALES',
          },
          intervalEnabled: false,
          logarithmicOld: true,
          hideMinMax: false,
        },
        yAxis: {
          enabled: true,
          ticks: true,
          labels: {
            enabled: true,
            rotation: 0,
          },
          gridLines: true,
          logarithmic: true,
          title: {
            enabled: true,
            text: 'QUANTITY',
          },
          intervalEnabled: false,
          logarithmicOld: true,
          hideMinMax: false,
        },
        dataLimits: {
          categoriesCapacityX: 500,
          categoriesCapacityY: 500,
          seriesCapacity: 50,
        },
      },
      lastOpened: null,
      _dataSourcePermission: 'owner',
      userAuth: {
        dashboards: {
          create: true,
          delete: true,
          move: true,
          rename: true,
          duplicate: true,
          change_owner: true,
          toggle_edit_mode: true,
          edit_layout: true,
          edit_script: true,
          export_dash: true,
          export_jpeg: true,
          export_image: true,
          export_pdf: true,
          share: true,
          restore: true,
          copy_to_server: true,
          import: true,
          select_palette: true,
          replace_datasource: true,
          undo_import_dash: true,
          toggleDataExploration: true,
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            reorder: true,
            modify_type: true,
            toggle_auto_update: true,
            set_defaults: true,
            advanced: true,
            use_starred: true,
            modify_filter_relationship: true,
          },
        },
        widgets: {
          create: true,
          delete: true,
          rename: true,
          duplicate: true,
          copy_to_dashboard: true,
          edit: true,
          edit_script: true,
          change_type: true,
          export_csv: true,
          export_png: true,
          export_svg: true,
          export_pdf: true,
          modify_selection_attrs: true,
          modify_selection_mode: true,
          drill_to_anywhere: true,
          add_to_pulse: true,
          items: {
            create: true,
            delete: true,
            rename: true,
            modify: true,
            reorder: true,
            modify_type: true,
            modify_format: true,
            on_off: true,
            select_hierarchies: true,
          },
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            modify_layout: true,
            modify_type: true,
            modify_dashboard_filters: true,
            use_starred: true,
          },
          widgetViewOnly: false,
        },
        base: {
          isConsumer: false,
          isContributor: false,
          isAdmin: false,
          isSuper: true,
        },
      },
      _toDisableOptionsList: {
        widgets: {
          duplicate: false,
        },
      },
    },
    {
      _id: '665118e4feabf3002ae94bcb',
      title: 'REVENUE vs.UNITS SOLD',
      type: 'chart/line',
      subtype: 'line/spline',
      oid: '665118e4feabf3002ae94bb6',
      desc: null,
      source: null,
      owner: '66298de3c09e52001c804146',
      userId: '66298de3c09e52001c804146',
      created: '2024-05-24T22:47:00.070Z',
      lastUpdated: '2024-05-24T22:47:00.070Z',
      instanceType: 'owner',
      datasource: {
        address: 'LocalHost',
        title: 'Sample ECommerce',
        id: 'localhost_aSampleIAAaECommerce',
        database: 'aSampleIAAaECommerce',
      },
      selection: null,
      metadata: {
        ignore: {
          dimensions: [],
          ids: [],
          all: false,
        },
        panels: [
          {
            name: 'x-axis',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Date',
                  dim: '[Commerce.Date (Calendar)]',
                  datatype: 'datetime',
                  merged: true,
                  level: 'months',
                  title: 'Months in Date',
                },
                format: {
                  mask: {
                    years: 'yyyy',
                    quarters: 'yyyy Q',
                    months: 'M-yy',
                    days: 'shortDate',
                  },
                },
              },
            ],
          },
          {
            name: 'values',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Revenue',
                  dim: '[Commerce.Revenue]',
                  datatype: 'numeric',
                  agg: 'sum',
                  title: 'Total Revenue',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: true,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                  color: {
                    type: 'color',
                  },
                },
              },
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Quantity',
                  dim: '[Commerce.Quantity]',
                  datatype: 'numeric',
                  agg: 'sum',
                  title: 'Total Quantity',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: true,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                  color: {
                    type: 'color',
                  },
                },
                y2: true,
                singleSeriesType: 'column',
              },
            ],
          },
          {
            name: 'break by',
            items: [],
          },
          {
            name: 'filters',
            items: [],
          },
        ],
      },
      dashboardid: '665118e4feabf3002ae94bae',
      options: {
        dashboardFiltersMode: 'filter',
        selector: true,
        triggersDomready: true,
      },
      style: {
        lineWidth: {
          width: 'bold',
        },
        legend: {
          enabled: true,
          position: 'bottom',
        },
        seriesLabels: {
          enabled: false,
          rotation: 0,
        },
        markers: {
          enabled: true,
          fill: 'hollow',
          size: 'small',
        },
        xAxis: {
          enabled: true,
          ticks: true,
          labels: {
            enabled: true,
            rotation: 0,
          },
          gridLines: false,
          title: {
            enabled: false,
            text: 'MONTH',
          },
          x2Title: {
            enabled: false,
          },
          intervalEnabled: false,
        },
        yAxis: {
          inactive: false,
          enabled: true,
          ticks: true,
          labels: {
            enabled: true,
            rotation: 0,
          },
          gridLines: true,
          logarithmic: true,
          title: {
            enabled: true,
            text: 'SALES',
          },
          min: '',
          intervalEnabled: false,
        },
        y2Axis: {
          inactive: false,
          enabled: true,
          ticks: true,
          labels: {
            enabled: true,
            rotation: 0,
          },
          gridLines: false,
          logarithmic: false,
          title: {
            enabled: true,
            text: 'QUANTITY',
          },
          templateMainYHasGridLines: true,
          intervalEnabled: true,
        },
        navigator: {
          enabled: true,
        },
        dataLimits: {
          seriesCapacity: 50,
          categoriesCapacity: 100000,
        },
      },
      lastOpened: null,
      _dataSourcePermission: 'owner',
      userAuth: {
        dashboards: {
          create: true,
          delete: true,
          move: true,
          rename: true,
          duplicate: true,
          change_owner: true,
          toggle_edit_mode: true,
          edit_layout: true,
          edit_script: true,
          export_dash: true,
          export_jpeg: true,
          export_image: true,
          export_pdf: true,
          share: true,
          restore: true,
          copy_to_server: true,
          import: true,
          select_palette: true,
          replace_datasource: true,
          undo_import_dash: true,
          toggleDataExploration: true,
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            reorder: true,
            modify_type: true,
            toggle_auto_update: true,
            set_defaults: true,
            advanced: true,
            use_starred: true,
            modify_filter_relationship: true,
          },
        },
        widgets: {
          create: true,
          delete: true,
          rename: true,
          duplicate: true,
          copy_to_dashboard: true,
          edit: true,
          edit_script: true,
          change_type: true,
          export_csv: true,
          export_png: true,
          export_svg: true,
          export_pdf: true,
          modify_selection_attrs: true,
          modify_selection_mode: true,
          drill_to_anywhere: true,
          add_to_pulse: true,
          items: {
            create: true,
            delete: true,
            rename: true,
            modify: true,
            reorder: true,
            modify_type: true,
            modify_format: true,
            on_off: true,
            select_hierarchies: true,
          },
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            modify_layout: true,
            modify_type: true,
            modify_dashboard_filters: true,
            use_starred: true,
          },
          widgetViewOnly: false,
        },
        base: {
          isConsumer: false,
          isContributor: false,
          isAdmin: false,
          isSuper: true,
        },
      },
      _toDisableOptionsList: {
        widgets: {
          duplicate: false,
        },
      },
    },
    {
      _id: '665118e4feabf3002ae94bcc',
      title: 'TOP 3 CATEGORIES BY REVENUE AND AGE',
      type: 'chart/bar',
      subtype: 'bar/stacked',
      oid: '665118e4feabf3002ae94bb7',
      desc: null,
      source: null,
      owner: '66298de3c09e52001c804146',
      userId: '66298de3c09e52001c804146',
      created: '2024-05-24T22:47:00.070Z',
      lastUpdated: '2024-05-24T22:47:00.070Z',
      instanceType: 'owner',
      datasource: {
        address: 'LocalHost',
        title: 'Sample ECommerce',
        id: 'localhost_aSampleIAAaECommerce',
        database: 'aSampleIAAaECommerce',
      },
      selection: null,
      metadata: {
        ignore: {
          dimensions: [],
          ids: [],
          all: false,
        },
        panels: [
          {
            name: 'categories',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Age Range',
                  dim: '[Commerce.Age Range]',
                  datatype: 'text',
                  merged: true,
                  title: 'Age Range',
                },
              },
            ],
          },
          {
            name: 'values',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Revenue',
                  dim: '[Commerce.Revenue]',
                  datatype: 'numeric',
                  agg: 'sum',
                  title: 'Total Revenue',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: true,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                },
              },
            ],
          },
          {
            name: 'break by',
            items: [
              {
                jaql: {
                  table: 'category',
                  column: 'Category',
                  dim: '[Category.Category]',
                  datatype: 'text',
                  merged: true,
                  title: 'Category',
                },
                format: {},
              },
            ],
          },
          {
            name: 'filters',
            items: [
              {
                jaql: {
                  datasource: {
                    title: 'Sample ECommerce',
                    fullname: 'LocalHost/Sample ECommerce',
                    id: 'localhost_aSampleIAAaECommerce',
                    address: 'LocalHost',
                    database: 'aSampleIAAaECommerce',
                  },
                  table: 'category',
                  column: 'Category',
                  dim: '[Category.Category]',
                  datatype: 'text',
                  merged: true,
                  title: 'Category',
                  filter: {
                    top: 3,
                    by: {
                      table: 'Commerce',
                      column: 'Revenue',
                      dim: '[Commerce.Revenue]',
                      datatype: 'numeric',
                      agg: 'sum',
                      title: 'Total Revenue',
                    },
                  },
                  collapsed: false,
                },
                format: {
                  mask: {
                    isdefault: true,
                  },
                },
              },
            ],
          },
        ],
      },
      dashboardid: '665118e4feabf3002ae94bae',
      options: {
        dashboardFiltersMode: 'filter',
        selector: true,
        triggersDomready: true,
        maxCharsPerLabelXAxis: 9,
      },
      style: {
        legend: {
          enabled: true,
          position: 'bottom',
        },
        seriesLabels: {
          enabled: false,
          rotation: 0,
        },
        xAxis: {
          enabled: true,
          ticks: true,
          labels: {
            enabled: true,
            rotation: 0,
          },
          gridLines: false,
          title: {
            enabled: true,
            text: 'AGE RANGE',
          },
          x2Title: {
            enabled: false,
          },
          intervalEnabled: false,
        },
        yAxis: {
          inactive: false,
          enabled: true,
          ticks: true,
          labels: {
            enabled: true,
            rotation: 0,
          },
          gridLines: true,
          logarithmic: false,
          title: {
            enabled: true,
            text: 'SALES',
          },
          intervalEnabled: true,
          hideMinMax: false,
        },
        y2Axis: {
          inactive: true,
          enabled: true,
          ticks: true,
          labels: {
            enabled: true,
            rotation: 0,
          },
          gridLines: false,
          logarithmic: false,
          title: {
            enabled: false,
          },
          intervalEnabled: true,
          hideMinMax: false,
        },
        dataLimits: {
          seriesCapacity: 50,
          categoriesCapacity: 100000,
        },
        navigator: {
          enabled: true,
        },
      },
      viewState: {
        activeTab: 'design',
      },
      lastOpened: null,
      _dataSourcePermission: 'owner',
      userAuth: {
        dashboards: {
          create: true,
          delete: true,
          move: true,
          rename: true,
          duplicate: true,
          change_owner: true,
          toggle_edit_mode: true,
          edit_layout: true,
          edit_script: true,
          export_dash: true,
          export_jpeg: true,
          export_image: true,
          export_pdf: true,
          share: true,
          restore: true,
          copy_to_server: true,
          import: true,
          select_palette: true,
          replace_datasource: true,
          undo_import_dash: true,
          toggleDataExploration: true,
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            reorder: true,
            modify_type: true,
            toggle_auto_update: true,
            set_defaults: true,
            advanced: true,
            use_starred: true,
            modify_filter_relationship: true,
          },
        },
        widgets: {
          create: true,
          delete: true,
          rename: true,
          duplicate: true,
          copy_to_dashboard: true,
          edit: true,
          edit_script: true,
          change_type: true,
          export_csv: true,
          export_png: true,
          export_svg: true,
          export_pdf: true,
          modify_selection_attrs: true,
          modify_selection_mode: true,
          drill_to_anywhere: true,
          add_to_pulse: true,
          items: {
            create: true,
            delete: true,
            rename: true,
            modify: true,
            reorder: true,
            modify_type: true,
            modify_format: true,
            on_off: true,
            select_hierarchies: true,
          },
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            modify_layout: true,
            modify_type: true,
            modify_dashboard_filters: true,
            use_starred: true,
          },
          widgetViewOnly: false,
        },
        base: {
          isConsumer: false,
          isContributor: false,
          isAdmin: false,
          isSuper: true,
        },
      },
      _toDisableOptionsList: {
        widgets: {
          duplicate: false,
        },
      },
    },
  ],
  isDatasourceBeingReplaced: false,
  _dataSourcePermission: 'owner',
  userAuth: {
    dashboards: {
      create: true,
      delete: true,
      move: true,
      rename: true,
      duplicate: true,
      change_owner: true,
      toggle_edit_mode: true,
      edit_layout: true,
      edit_script: true,
      export_dash: true,
      export_jpeg: true,
      export_image: true,
      export_pdf: true,
      share: true,
      restore: true,
      copy_to_server: true,
      import: true,
      select_palette: true,
      replace_datasource: true,
      undo_import_dash: true,
      toggleDataExploration: true,
      filters: {
        create: true,
        delete: true,
        save: true,
        on_off: true,
        toggle_expansion: true,
        modify: true,
        reorder: true,
        modify_type: true,
        toggle_auto_update: true,
        set_defaults: true,
        advanced: true,
        use_starred: true,
        modify_filter_relationship: true,
      },
    },
    widgets: {
      create: true,
      delete: true,
      rename: true,
      duplicate: true,
      copy_to_dashboard: true,
      edit: true,
      edit_script: true,
      change_type: true,
      export_csv: true,
      export_png: true,
      export_svg: true,
      export_pdf: true,
      modify_selection_attrs: true,
      modify_selection_mode: true,
      drill_to_anywhere: true,
      add_to_pulse: true,
      items: {
        create: true,
        delete: true,
        rename: true,
        modify: true,
        reorder: true,
        modify_type: true,
        modify_format: true,
        on_off: true,
        select_hierarchies: true,
      },
      filters: {
        create: true,
        delete: true,
        save: true,
        on_off: true,
        toggle_expansion: true,
        modify: true,
        modify_layout: true,
        modify_type: true,
        modify_dashboard_filters: true,
        use_starred: true,
      },
      widgetViewOnly: false,
    },
    base: {
      isConsumer: false,
      isContributor: false,
      isAdmin: false,
      isSuper: true,
    },
  },
  _toDisableOptionsList: {
    dashboards: {
      duplicate: false,
      export_dash: false,
    },
  },
} as unknown as DashboardDto;
