import { DashboardDto } from '../../api/types/dashboard-dto';

export const dashboardWithTextWidget = {
  _id: '66d998d1ab28a90032b5b491',
  title: 'default text widget',
  oid: '66d998d1ab28a90032b5b490',
  desc: '',
  source: null,
  type: 'dashboard',
  shares: [
    {
      shareId: '662ba7319f04e5001cbc7f58',
      type: 'user',
    },
  ],
  style: {
    palette: {
      _id: '662ba7319f04e5001cbc7f59',
      colors: ['#00cee6', '#9b9bd7', '#6EDA55', '#fc7570', '#fbb755', '#218A8C'],
      name: 'Vivid',
      isDefault: true,
      sortOrder: 10,
      isSystem: true,
      systemDefault: true,
    },
  },
  owner: '662ba7319f04e5001cbc7f58',
  userId: '662ba7319f04e5001cbc7f58',
  created: '2024-09-05T11:41:05.127Z',
  lastUpdated: '2024-09-10T14:40:22.119Z',
  lastUsed: '2024-09-10T14:40:22.119Z',
  usageCount: 1,
  layout: {
    instanceid: 'D2CA0-910D-C8',
    type: 'columnar',
    columns: [
      {
        width: 100,
        cells: [
          {
            subcells: [
              {
                elements: [
                  {
                    minHeight: 96,
                    maxHeight: 2048,
                    minWidth: 128,
                    maxWidth: 2048,
                    height: 384,
                    defaultWidth: 512,
                    widgetid: '66e02b59ab28a90032b5b4d3',
                  },
                ],
                width: 100,
                stretchable: false,
                pxlWidth: 1380,
                index: 0,
              },
            ],
          },
          {
            subcells: [
              {
                elements: [
                  {
                    minHeight: 64,
                    maxHeight: 2048,
                    minWidth: 64,
                    maxWidth: 2048,
                    height: '476px',
                    defaultWidth: 128,
                    widgetid: '66d9a146ab28a90032b5b494',
                  },
                ],
                width: 100,
                stretchable: false,
                pxlWidth: 1383,
                index: 0,
              },
            ],
          },
        ],
        pxlWidth: 1383,
        index: 0,
      },
    ],
    container: {},
  },
  instanceType: 'owner',
  original: null,
  dataExploration: false,
  tenantId: '662ba7329f04e5001cbc7f65',
  lastOpened: '2024-09-10T14:02:47.380Z',
  previewLayout: [],
  datasource: {
    address: 'LocalHost',
    title: 'Sample ECommerce',
    id: 'localhost_aSampleIAAaECommerce',
    database: 'aSampleIAAaECommerce',
    fullname: 'localhost/Sample ECommerce',
    live: false,
  },
  filters: [
    {
      jaql: {
        table: 'Category',
        column: 'Category',
        dim: '[Category.Category]',
        datatype: 'text',
        merged: true,
        datasource: {
          address: 'LocalHost',
          title: 'Sample ECommerce',
          id: 'localhost_aSampleIAAaECommerce',
          database: 'aSampleIAAaECommerce',
          fullname: 'localhost/Sample ECommerce',
          live: false,
        },
        firstday: 'mon',
        locale: 'en-gb',
        filter: {
          explicit: true,
          multiSelection: true,
          members: [
            'Camcorders',
            'Camera Flashes',
            'Car Amplifiers',
            'Car Speakers and Subwoofers',
          ],
        },
        title: 'Category',
        collapsed: true,
        isDashboardFilter: true,
      },
      instanceid: '7D7BD-E7C4-FB',
      isCascading: false,
    },
    {
      jaql: {
        table: 'Commerce',
        column: 'Gender',
        dim: '[Commerce.Gender]',
        datatype: 'text',
        merged: true,
        datasource: {
          address: 'LocalHost',
          title: 'Sample ECommerce',
          id: 'localhost_aSampleIAAaECommerce',
          database: 'aSampleIAAaECommerce',
          fullname: 'localhost/Sample ECommerce',
          live: false,
        },
        firstday: 'mon',
        locale: 'en-gb',
        title: 'Gender',
        collapsed: true,
        isDashboardFilter: true,
        filter: {
          explicit: true,
          multiSelection: true,
          members: ['Female'],
        },
      },
      instanceid: '9A2F2-F785-36',
      isCascading: false,
      disabled: false,
    },
  ],
  editing: true,
  settings: {
    autoUpdateOnFiltersChange: true,
  },
  filterRelations: [],
  filterToDatasourceMapping: {},
  widgets: [
    {
      _id: '66d9a146ab28a90032b5b495',
      title: 'RICHTEXT_MAIN.TITLE',
      type: 'richtexteditor',
      subtype: 'richtexteditor',
      oid: '66d9a146ab28a90032b5b494',
      desc: null,
      source: null,
      owner: '662ba7319f04e5001cbc7f58',
      userId: '662ba7319f04e5001cbc7f58',
      created: '2024-09-05T12:17:10.314Z',
      lastUpdated: '2024-09-10T12:19:14.010Z',
      instanceType: 'owner',
      datasource: {
        address: 'LocalHost',
        title: 'Sample ECommerce',
        id: 'localhost_aSampleIAAaECommerce',
        database: 'aSampleIAAaECommerce',
        fullname: 'localhost/Sample ECommerce',
        live: false,
      },
      selection: null,
      metadata: {
        ignore: {
          dimensions: [],
          ids: [],
          all: false,
        },
        panels: [],
        usedFormulasMapping: {},
      },
      tags: [],
      style: {
        content: {
          html: '<font color="#008c9c" size="5"><u style="">fancy text</u></font>',
          vAlign: 'valign-middle',
          bgColor: '#FFFFFF',
          textAlign: 'center',
        },
      },
      instanceid: '2E7CC-1178-BA',
      realTimeRefreshing: false,
      options: {
        triggersDomready: true,
        hideFromWidgetList: true,
        disableExportToCSV: true,
        disableExportToImage: true,
        toolbarButton: {
          css: 'add-rich-text',
          tooltip: 'RICHTEXT_MAIN.TOOLBAR_BUTTON',
        },
        selector: false,
        disallowSelector: true,
        disallowWidgetTitle: true,
        supportsHierarchies: false,
        dashboardFiltersMode: 'filter',
      },
      dashboardid: '66d998d1ab28a90032b5b490',
      _dataSourcePermission: 'owner',
      userAuth: {
        dashboards: {
          create: true,
          delete: true,
          move: true,
          rename: true,
          duplicate: true,
          change_owner: true,
          toggle_edit_mode: true,
          edit_layout: true,
          edit_script: true,
          export_dash: true,
          export_jpeg: true,
          export_image: true,
          export_pdf: true,
          share: true,
          restore: true,
          copy_to_server: true,
          import: true,
          select_palette: true,
          replace_datasource: true,
          undo_import_dash: true,
          toggleDataExploration: true,
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            reorder: true,
            modify_type: true,
            toggle_auto_update: true,
            set_defaults: true,
            advanced: true,
            use_starred: true,
            modify_filter_relationship: true,
          },
        },
        widgets: {
          create: true,
          delete: true,
          rename: true,
          duplicate: true,
          copy_to_dashboard: true,
          edit: true,
          edit_script: true,
          change_type: true,
          export_csv: true,
          export_png: true,
          export_svg: true,
          export_pdf: true,
          modify_selection_attrs: true,
          modify_selection_mode: true,
          drill_to_anywhere: true,
          add_to_pulse: true,
          items: {
            create: true,
            delete: true,
            rename: true,
            modify: true,
            reorder: true,
            modify_type: true,
            modify_format: true,
            on_off: true,
            select_hierarchies: true,
          },
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            modify_layout: true,
            modify_type: true,
            modify_dashboard_filters: true,
            use_starred: true,
          },
          widgetViewOnly: false,
        },
        base: {
          isConsumer: false,
          isContributor: false,
          isAdmin: false,
          isSuper: true,
        },
      },
      _toDisableOptionsList: {
        widgets: {
          duplicate: false,
        },
      },
    },
    {
      _id: '66e02b59ab28a90032b5b4d4',
      title: '',
      type: 'chart/pie',
      subtype: 'pie/classic',
      oid: '66e02b59ab28a90032b5b4d3',
      desc: null,
      source: null,
      owner: '662ba7319f04e5001cbc7f58',
      userId: '662ba7319f04e5001cbc7f58',
      created: '2024-09-10T11:19:53.948Z',
      lastUpdated: '2024-09-10T14:40:12.469Z',
      instanceType: 'owner',
      datasource: {
        address: 'LocalHost',
        title: 'Sample ECommerce',
        id: 'aLOCALHOST_aSAMPLEIAAaECOMMERCE',
        database: 'aSampleIAAaECommerce',
        fullname: 'LocalHost/Sample ECommerce',
      },
      selection: null,
      metadata: {
        ignore: {
          dimensions: [],
          ids: [],
          all: false,
        },
        panels: [
          {
            name: 'categories',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Gender',
                  dim: '[Commerce.Gender]',
                  datatype: 'text',
                  merged: true,
                  title: 'Gender',
                },
                instanceid: '7FFC2-6334-12',
                format: {
                  members: {},
                },
              },
            ],
          },
          {
            name: 'values',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Cost',
                  dim: '[Commerce.Cost]',
                  datatype: 'numeric',
                  agg: 'sum',
                  title: 'Total Cost',
                },
                instanceid: '75F04-7F38-F0',
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: true,
                    },
                    separated: true,
                    decimals: 'auto',
                    abbreviateAll: false,
                    isdefault: true,
                  },
                },
              },
            ],
          },
          {
            name: 'filters',
            items: [],
          },
        ],
        usedFormulasMapping: {},
      },
      tags: [],
      style: {
        legend: {
          enabled: true,
          position: 'bottom',
        },
        labels: {
          enabled: true,
          categories: true,
          value: false,
          percent: true,
          decimals: false,
          fontFamily: 'Open Sans',
          color: 'red',
        },
        convolution: {
          enabled: true,
          selectedConvolutionType: 'byPercentage',
          minimalIndependentSlicePercentage: 3,
          independentSlicesCount: 7,
        },
        dataLimits: {
          seriesCapacity: 100000,
        },
        lineWidth: {
          width: 'bold',
        },
        seriesLabels: {
          enabled: false,
          rotation: 0,
        },
        markers: {
          enabled: false,
          fill: 'filled',
          size: 'small',
        },
        xAxis: {
          enabled: true,
          ticks: true,
          labels: {
            enabled: true,
            rotation: 0,
          },
          title: {
            enabled: false,
          },
          x2Title: {
            enabled: false,
          },
          gridLines: true,
          isIntervalEnabled: true,
        },
        yAxis: {
          inactive: true,
          enabled: true,
          ticks: true,
          labels: {
            enabled: true,
            rotation: 0,
          },
          title: {
            enabled: false,
          },
          gridLines: true,
          logarithmic: false,
          isIntervalEnabled: true,
        },
        y2Axis: {
          inactive: true,
          enabled: true,
          ticks: true,
          labels: {
            enabled: true,
            rotation: 0,
          },
          title: {
            enabled: false,
          },
          gridLines: false,
          logarithmic: false,
          isIntervalEnabled: true,
        },
        navigator: {
          enabled: true,
        },
        narration: {
          enabled: false,
          display: 'above',
          format: 'bullets',
          verbosity: 'medium',
          up_sentiment: 'good',
          aggregation: 'sum',
          labels: [
            {
              id: 'gender',
              title: 'Gender',
              singular: 'Gender',
              plural: 'Gender',
            },
          ],
        },
        automaticHeight: false,
      },
      instanceid: '64D07-9BFD-DB',
      realTimeRefreshing: false,
      options: {
        dashboardFiltersMode: 'select',
        selector: true,
        triggersDomready: true,
        autoUpdateOnEveryChange: true,
        drillToAnywhere: true,
        selectorLocked: false,
      },
      dashboardid: '66d998d1ab28a90032b5b490',
      _dataSourcePermission: 'owner',
      userAuth: {
        dashboards: {
          create: true,
          delete: true,
          move: true,
          rename: true,
          duplicate: true,
          change_owner: true,
          toggle_edit_mode: true,
          edit_layout: true,
          edit_script: true,
          export_dash: true,
          export_jpeg: true,
          export_image: true,
          export_pdf: true,
          share: true,
          restore: true,
          copy_to_server: true,
          import: true,
          select_palette: true,
          replace_datasource: true,
          undo_import_dash: true,
          toggleDataExploration: true,
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            reorder: true,
            modify_type: true,
            toggle_auto_update: true,
            set_defaults: true,
            advanced: true,
            use_starred: true,
            modify_filter_relationship: true,
          },
        },
        widgets: {
          create: true,
          delete: true,
          rename: true,
          duplicate: true,
          copy_to_dashboard: true,
          edit: true,
          edit_script: true,
          change_type: true,
          export_csv: true,
          export_png: true,
          export_svg: true,
          export_pdf: true,
          modify_selection_attrs: true,
          modify_selection_mode: true,
          drill_to_anywhere: true,
          add_to_pulse: true,
          items: {
            create: true,
            delete: true,
            rename: true,
            modify: true,
            reorder: true,
            modify_type: true,
            modify_format: true,
            on_off: true,
            select_hierarchies: true,
          },
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            modify_layout: true,
            modify_type: true,
            modify_dashboard_filters: true,
            use_starred: true,
          },
          widgetViewOnly: false,
        },
        base: {
          isConsumer: false,
          isContributor: false,
          isAdmin: false,
          isSuper: true,
        },
      },
      _toDisableOptionsList: {
        widgets: {
          duplicate: false,
        },
      },
    },
  ],
  isDatasourceBeingReplaced: false,
  _dataSourcePermission: 'owner',
  userAuth: {
    dashboards: {
      create: true,
      delete: true,
      move: true,
      rename: true,
      duplicate: true,
      change_owner: true,
      toggle_edit_mode: true,
      edit_layout: true,
      edit_script: true,
      export_dash: true,
      export_jpeg: true,
      export_image: true,
      export_pdf: true,
      share: true,
      restore: true,
      copy_to_server: true,
      import: true,
      select_palette: true,
      replace_datasource: true,
      undo_import_dash: true,
      toggleDataExploration: true,
      filters: {
        create: true,
        delete: true,
        save: true,
        on_off: true,
        toggle_expansion: true,
        modify: true,
        reorder: true,
        modify_type: true,
        toggle_auto_update: true,
        set_defaults: true,
        advanced: true,
        use_starred: true,
        modify_filter_relationship: true,
      },
    },
    widgets: {
      create: true,
      delete: true,
      rename: true,
      duplicate: true,
      copy_to_dashboard: true,
      edit: true,
      edit_script: true,
      change_type: true,
      export_csv: true,
      export_png: true,
      export_svg: true,
      export_pdf: true,
      modify_selection_attrs: true,
      modify_selection_mode: true,
      drill_to_anywhere: true,
      add_to_pulse: true,
      items: {
        create: true,
        delete: true,
        rename: true,
        modify: true,
        reorder: true,
        modify_type: true,
        modify_format: true,
        on_off: true,
        select_hierarchies: true,
      },
      filters: {
        create: true,
        delete: true,
        save: true,
        on_off: true,
        toggle_expansion: true,
        modify: true,
        modify_layout: true,
        modify_type: true,
        modify_dashboard_filters: true,
        use_starred: true,
      },
      widgetViewOnly: false,
    },
    base: {
      isConsumer: false,
      isContributor: false,
      isAdmin: false,
      isSuper: true,
    },
  },
  _toDisableOptionsList: {
    dashboards: {
      duplicate: false,
      export_dash: false,
    },
  },
} as DashboardDto;
