import { DashboardDto } from '../../api/types/dashboard-dto';

/**
 * 'Sample - Ecommerce' dashboard from Analytics tab in Sisense.
 */
export const sampleEcommerceDashboard = {
  _id: '6560ce3b6f1df500326a06af',
  title: 'Sample - Ecommerce',
  desc: '',
  source: null,
  type: 'dashboard',
  shares: [
    {
      shareId: '64b933f34e4e67001a40353e',
      type: 'user',
    },
  ],
  style: {
    palette: {
      _id: '64b933f34e4e67001a403549',
      colors: [
        '#117899',
        '#60B8CC',
        '#5CA793',
        '#A2B86C',
        '#EBC844',
        '#ECAA38',
        '#EF8B2C',
        '#F16C20',
        '#D94E1F',
        '#C02E1D',
        '#893B32',
        '#0D3C55',
        '#0F5B78',
      ],
      name: 'Midnight Light',
      isDefault: false,
      sortOrder: 30,
      isSystem: true,
    },
  },
  owner: '64b933f34e4e67001a40353e',
  userId: '64b933f34e4e67001a40353e',
  created: '2023-11-24T16:24:27.494Z',
  lastUpdated: '2023-11-24T16:24:27.494Z',
  lastUsed: '2023-11-24T16:24:27.494Z',
  usageCount: 1,
  layout: {
    type: 'columnar',
    columns: [
      {
        width: 16.869192280200142,
        cells: [
          {
            subcells: [
              {
                elements: [
                  {
                    minHeight: 48,
                    maxHeight: 1028,
                    minWidth: 48,
                    maxWidth: 1028,
                    defaultWidth: 512,
                    widgetid: '6560ce3b6f1df500326a06a2',
                    height: '184px',
                  },
                ],
                width: 100,
                stretchable: false,
                pxlWidth: 220,
                index: 0,
              },
            ],
          },
          {
            subcells: [
              {
                elements: [
                  {
                    minHeight: 48,
                    maxHeight: 1028,
                    height: '172px',
                    minWidth: 48,
                    maxWidth: 1028,
                    defaultWidth: 512,
                    widgetid: '6560ce3b6f1df500326a069e',
                  },
                ],
                width: 100,
                stretchable: false,
                pxlWidth: 220,
                index: 0,
              },
            ],
          },
          {
            subcells: [
              {
                elements: [
                  {
                    minHeight: 48,
                    maxHeight: 1028,
                    height: '172px',
                    minWidth: 48,
                    maxWidth: 1028,
                    defaultWidth: 512,
                    widgetid: '6560ce3b6f1df500326a06a0',
                  },
                ],
                width: 100,
                stretchable: false,
                pxlWidth: 220,
                index: 0,
              },
            ],
          },
          {
            subcells: [
              {
                elements: [
                  {
                    minHeight: 48,
                    maxHeight: 1028,
                    minWidth: 48,
                    maxWidth: 1028,
                    defaultWidth: 512,
                    widgetid: '6560ce3b6f1df500326a069d',
                    height: '184px',
                  },
                ],
                width: 100,
                stretchable: false,
                pxlWidth: 220,
                index: 0,
              },
            ],
          },
        ],
        pxlWidth: 235,
        index: 0,
      },
      {
        width: 43.9921530161844,
        pxlWidth: 612,
        index: 1,
        cells: [
          {
            subcells: [
              {
                elements: [
                  {
                    minHeight: 96,
                    maxHeight: 2048,
                    minWidth: 128,
                    maxWidth: 2048,
                    height: '392px',
                    defaultWidth: 512,
                    widgetid: '6560ce3b6f1df500326a06a4',
                  },
                ],
                width: 100,
                stretchable: false,
                pxlWidth: 582,
                index: 0,
              },
            ],
          },
          {
            subcells: [
              {
                elements: [
                  {
                    minHeight: 96,
                    maxHeight: 2048,
                    minWidth: 128,
                    maxWidth: 2048,
                    defaultWidth: 512,
                    widgetid: '6560ce3b6f1df500326a06a1',
                    height: '384px',
                  },
                ],
                width: 50.25466893039049,
                stretchable: false,
                pxlWidth: 296,
                index: 0,
              },
              {
                elements: [
                  {
                    minHeight: 96,
                    maxHeight: 2048,
                    minWidth: 128,
                    maxWidth: 2048,
                    defaultWidth: 512,
                    widgetid: '6560ce3b6f1df500326a069f',
                    height: '384px',
                  },
                ],
                width: 49.745331069609506,
                stretchable: false,
                pxlWidth: 293,
                index: 1,
              },
            ],
          },
        ],
      },
      {
        width: 39.13865470361545,
        pxlWidth: 544,
        index: 2,
        cells: [
          {
            subcells: [
              {
                elements: [
                  {
                    minHeight: 96,
                    maxHeight: 2048,
                    minWidth: 128,
                    maxWidth: 2048,
                    height: '392px',
                    defaultWidth: 512,
                    widgetid: '6560ce3b6f1df500326a06a3',
                  },
                ],
                width: 100,
                stretchable: false,
                pxlWidth: 521,
                index: 0,
              },
            ],
          },
          {
            subcells: [
              {
                elements: [
                  {
                    minHeight: 96,
                    maxHeight: 2048,
                    minWidth: 128,
                    maxWidth: 2048,
                    height: '384px',
                    defaultWidth: 512,
                    widgetid: '6560ce3b6f1df500326a06a5',
                  },
                ],
                width: 100,
                stretchable: false,
                pxlWidth: 521,
                index: 0,
              },
            ],
          },
        ],
      },
      {
        width: 43.9921530161844,
        pxlWidth: 612,
        index: 3,
        cells: [
          {
            subcells: [
              {
                elements: [
                  {
                    minHeight: 96,
                    maxHeight: 2048,
                    minWidth: 128,
                    maxWidth: 2048,
                    height: '392px',
                    defaultWidth: 512,
                    widgetid: '67111cb76ab71f0032d8599d',
                  },
                ],
                width: 100,
                stretchable: false,
                pxlWidth: 582,
                index: 0,
              },
            ],
          },
          {
            subcells: [
              {
                elements: [
                  {
                    minHeight: 96,
                    maxHeight: 2048,
                    minWidth: 128,
                    maxWidth: 2048,
                    defaultWidth: 512,
                    widgetid: '672352d827ea67002bdcf485',
                    height: '384px',
                  },
                ],
                width: 50.25466893039049,
                stretchable: false,
                pxlWidth: 296,
                index: 0,
              },
              {
                elements: [
                  {
                    minHeight: 96,
                    maxHeight: 2048,
                    minWidth: 128,
                    maxWidth: 2048,
                    defaultWidth: 512,
                    widgetid: '6742206527ea67002bdcf6ac',
                    height: '384px',
                  },
                ],
                width: 49.745331069609506,
                stretchable: false,
                pxlWidth: 293,
                index: 1,
              },
            ],
          },
        ],
      },
    ],
  },
  instanceType: 'owner',
  original: null,
  previewLayout: [],
  datasource: {
    title: 'Sample ECommerce',
    id: 'localhost_aSampleIAAaECommerce',
    address: 'LocalHost',
    database: 'aSampleIAAaECommerce',
  },
  editing: true,
  filters: [
    {
      jaql: {
        datasource: {
          title: 'Sample ECommerce',
          fullname: 'LocalHost/Sample ECommerce',
          id: 'localhost_aSampleIAAaECommerce',
          address: 'LocalHost',
          database: 'aSampleIAAaECommerce',
        },
        column: 'Country',
        dim: '[Country.Country]',
        datatype: 'text',
        filter: {
          explicit: false,
          multiSelection: true,
          all: true,
        },
        title: 'COUNTRY',
        collapsed: false,
      },
      isCascading: false,
    },
    {
      jaql: {
        datasource: {
          title: 'Sample ECommerce',
          fullname: 'LocalHost/Sample ECommerce',
          id: 'localhost_aSampleIAAaECommerce',
          address: 'LocalHost',
          database: 'aSampleIAAaECommerce',
        },
        column: 'Date',
        dim: '[Commerce.Date (Calendar)]',
        datatype: 'datetime',
        level: 'years',
        title: 'YEARS',
        collapsed: false,
        filter: {
          explicit: true,
          multiSelection: true,
          members: ['2013-01-01T00:00:00'],
        },
      },
      isCascading: false,
      disabled: false,
    },
    {
      jaql: {
        datasource: {
          title: 'Sample ECommerce',
          fullname: 'LocalHost/Sample ECommerce',
          id: 'localhost_aSampleIAAaECommerce',
          address: 'LocalHost',
          database: 'aSampleIAAaECommerce',
        },
        column: 'Revenue',
        dim: '[Commerce.Revenue]',
        datatype: 'numeric',
        filter: {
          fromNotEqual: 0,
        },
        title: 'SALES REVENUE RANGE',
        collapsed: false,
      },
      isCascading: false,
    },
  ],
  isPublic: null,
  oid: '6560ce3b6f1df500326a069c',
  options: {
    manual: false,
  },
  parentFolder: null,
  tenantId: '64b933f34e4e67001a40354b',
  widgets: [
    {
      _id: '6560ce3b6f1df500326a06b0',
      title: 'TOTAL BRANDS',
      type: 'indicator',
      subtype: 'indicator/gauge',
      oid: '6560ce3b6f1df500326a069d',
      desc: null,
      source: null,
      owner: '64b933f34e4e67001a40353e',
      userId: '64b933f34e4e67001a40353e',
      created: '2023-11-24T16:24:27.495Z',
      lastUpdated: '2023-11-24T16:24:27.495Z',
      instanceType: 'owner',
      datasource: {
        title: 'Sample ECommerce',
        id: 'localhost_aSampleIAAaECommerce',
        address: 'LocalHost',
        database: 'aSampleIAAaECommerce',
      },
      selection: null,
      metadata: {
        ignore: {
          dimensions: [],
          ids: [],
          all: false,
        },
        panels: [
          {
            name: 'value',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Brand ID',
                  dim: '[Commerce.Brand ID]',
                  datatype: 'numeric',
                  merged: true,
                  agg: 'count',
                  title: '# of unique Brand ID',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: false,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                  color: {
                    type: 'color',
                  },
                },
              },
            ],
          },
          {
            name: 'secondary',
            items: [],
          },
          {
            name: 'min',
            items: [
              {
                jaql: {
                  formula: '0',
                  title: '0 (default)',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: false,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                },
              },
            ],
          },
          {
            name: 'max',
            items: [
              {
                jaql: {
                  type: 'measure',
                  formula: '2500',
                  context: {},
                  title: '2500',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: false,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                },
              },
            ],
          },
          {
            name: 'filters',
            items: [],
          },
        ],
      },
      dashboardid: '6560ce3b6f1df500326a069c',
      options: {
        title: false,
        dashboardFiltersMode: 'filter',
        selector: false,
        allowSelector: false,
        disallowSelector: true,
        triggersDomready: true,
        noTitle: false,
      },
      size: 'big',
      style: {
        'indicator/pictogram': {},
        subtype: 'round',
        'indicator/numeric': {
          subtype: 'simple',
          skin: '1',
          components: {
            title: {
              inactive: false,
              enabled: true,
            },
            icon: {
              inactive: false,
              enabled: true,
            },
            secondaryTitle: {
              inactive: true,
              enabled: true,
            },
          },
        },
        skin: '1',
        'indicator/gauge': {
          subtype: 'round',
          skin: '1',
          components: {
            ticks: {
              inactive: false,
              enabled: true,
            },
            labels: {
              inactive: false,
              enabled: true,
            },
            title: {
              inactive: false,
              enabled: true,
            },
            secondaryTitle: {
              inactive: true,
              enabled: true,
            },
          },
        },
        components: {
          ticks: {
            inactive: false,
            enabled: true,
          },
          labels: {
            inactive: false,
            enabled: true,
          },
          title: {
            inactive: false,
            enabled: false,
          },
          secondaryTitle: {
            inactive: true,
            enabled: true,
          },
        },
      },
      _dataSourcePermission: 'owner',
      userAuth: {
        dashboards: {
          create: true,
          delete: true,
          move: true,
          rename: true,
          duplicate: true,
          change_owner: true,
          toggle_edit_mode: true,
          edit_layout: true,
          edit_script: true,
          export_dash: true,
          export_jpeg: true,
          export_image: true,
          export_pdf: true,
          share: true,
          restore: true,
          copy_to_server: true,
          import: true,
          select_palette: true,
          replace_datasource: true,
          undo_import_dash: true,
          toggleDataExploration: true,
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            reorder: true,
            modify_type: true,
            toggle_auto_update: true,
            set_defaults: true,
            advanced: true,
            use_starred: true,
            modify_filter_relationship: true,
          },
        },
        widgets: {
          create: true,
          delete: true,
          rename: true,
          duplicate: true,
          copy_to_dashboard: true,
          edit: true,
          edit_script: true,
          change_type: true,
          export_csv: true,
          export_png: true,
          export_svg: true,
          export_pdf: true,
          modify_selection_attrs: true,
          modify_selection_mode: true,
          drill_to_anywhere: true,
          add_to_pulse: true,
          items: {
            create: true,
            delete: true,
            rename: true,
            modify: true,
            reorder: true,
            modify_type: true,
            modify_format: true,
            on_off: true,
            select_hierarchies: true,
          },
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            modify_layout: true,
            modify_type: true,
            modify_dashboard_filters: true,
            use_starred: true,
          },
          widgetViewOnly: false,
        },
        base: {
          isConsumer: false,
          isContributor: false,
          isAdmin: false,
          isSuper: true,
        },
      },
      _toDisableOptionsList: {
        widgets: {
          duplicate: false,
        },
      },
    },
    {
      _id: '6560ce3b6f1df500326a06b1',
      title: 'TOTAL UNITS SOLD',
      type: 'indicator',
      subtype: 'indicator/gauge',
      oid: '6560ce3b6f1df500326a069e',
      desc: null,
      source: null,
      owner: '64b933f34e4e67001a40353e',
      userId: '64b933f34e4e67001a40353e',
      created: '2023-11-24T16:24:27.495Z',
      lastUpdated: '2023-11-24T16:24:27.495Z',
      instanceType: 'owner',
      datasource: {
        title: 'Sample ECommerce',
        id: 'localhost_aSampleIAAaECommerce',
        address: 'LocalHost',
        database: 'aSampleIAAaECommerce',
      },
      selection: null,
      metadata: {
        ignore: {
          dimensions: [],
          ids: [],
          all: false,
        },
        panels: [
          {
            name: 'value',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Quantity',
                  dim: '[Commerce.Quantity]',
                  datatype: 'numeric',
                  agg: 'sum',
                  title: 'Total Quantity',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: false,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                  color: {
                    type: 'color',
                  },
                },
              },
            ],
          },
          {
            name: 'secondary',
            items: [],
          },
          {
            name: 'min',
            items: [
              {
                jaql: {
                  formula: '0',
                  title: '0 (default)',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: false,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                },
              },
            ],
          },
          {
            name: 'max',
            items: [
              {
                jaql: {
                  type: 'measure',
                  formula: '250000',
                  context: {},
                  title: '250000',
                },
                format: {
                  mask: {
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: true,
                    },
                    decimals: 'auto',
                    number: {
                      separated: true,
                    },
                    currency: null,
                    percent: null,
                    type: null,
                  },
                },
              },
            ],
          },
          {
            name: 'filters',
            items: [],
          },
        ],
      },
      dashboardid: '6560ce3b6f1df500326a069c',
      options: {
        title: false,
        dashboardFiltersMode: 'filter',
        selector: false,
        allowSelector: false,
        disallowSelector: true,
        triggersDomready: true,
        noTitle: false,
      },
      size: 'big',
      style: {
        'indicator/pictogram': {},
        subtype: 'round',
        'indicator/numeric': {
          subtype: 'simple',
          skin: '1',
          components: {
            title: {
              inactive: false,
              enabled: true,
            },
            icon: {
              inactive: false,
              enabled: true,
            },
            secondaryTitle: {
              inactive: true,
              enabled: true,
            },
          },
        },
        skin: '1',
        'indicator/gauge': {
          subtype: 'round',
          skin: '1',
          components: {
            ticks: {
              inactive: false,
              enabled: true,
            },
            labels: {
              inactive: false,
              enabled: true,
            },
            title: {
              inactive: false,
              enabled: true,
            },
            secondaryTitle: {
              inactive: true,
              enabled: true,
            },
          },
        },
        components: {
          ticks: {
            inactive: false,
            enabled: true,
          },
          labels: {
            inactive: false,
            enabled: true,
          },
          title: {
            inactive: false,
            enabled: false,
          },
          secondaryTitle: {
            inactive: true,
            enabled: true,
          },
        },
      },
      _dataSourcePermission: 'owner',
      userAuth: {
        dashboards: {
          create: true,
          delete: true,
          move: true,
          rename: true,
          duplicate: true,
          change_owner: true,
          toggle_edit_mode: true,
          edit_layout: true,
          edit_script: true,
          export_dash: true,
          export_jpeg: true,
          export_image: true,
          export_pdf: true,
          share: true,
          restore: true,
          copy_to_server: true,
          import: true,
          select_palette: true,
          replace_datasource: true,
          undo_import_dash: true,
          toggleDataExploration: true,
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            reorder: true,
            modify_type: true,
            toggle_auto_update: true,
            set_defaults: true,
            advanced: true,
            use_starred: true,
            modify_filter_relationship: true,
          },
        },
        widgets: {
          create: true,
          delete: true,
          rename: true,
          duplicate: true,
          copy_to_dashboard: true,
          edit: true,
          edit_script: true,
          change_type: true,
          export_csv: true,
          export_png: true,
          export_svg: true,
          export_pdf: true,
          modify_selection_attrs: true,
          modify_selection_mode: true,
          drill_to_anywhere: true,
          add_to_pulse: true,
          items: {
            create: true,
            delete: true,
            rename: true,
            modify: true,
            reorder: true,
            modify_type: true,
            modify_format: true,
            on_off: true,
            select_hierarchies: true,
          },
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            modify_layout: true,
            modify_type: true,
            modify_dashboard_filters: true,
            use_starred: true,
          },
          widgetViewOnly: false,
        },
        base: {
          isConsumer: false,
          isContributor: false,
          isAdmin: false,
          isSuper: true,
        },
      },
      _toDisableOptionsList: {
        widgets: {
          duplicate: false,
        },
      },
    },
    {
      _id: '6560ce3b6f1df500326a06b2',
      title: 'AGE RANGE BREAKDOWN',
      type: 'chart/pie',
      subtype: 'pie/classic',
      oid: '6560ce3b6f1df500326a069f',
      desc: null,
      source: null,
      owner: '64b933f34e4e67001a40353e',
      userId: '64b933f34e4e67001a40353e',
      created: '2023-11-24T16:24:27.495Z',
      lastUpdated: '2023-11-24T16:24:27.495Z',
      instanceType: 'owner',
      datasource: {
        title: 'Sample ECommerce',
        id: 'localhost_aSampleIAAaECommerce',
        address: 'LocalHost',
        database: 'aSampleIAAaECommerce',
      },
      selection: null,
      metadata: {
        ignore: {
          dimensions: [],
          ids: [],
          all: false,
        },
        panels: [
          {
            name: 'categories',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Age Range',
                  dim: '[Commerce.Age Range]',
                  datatype: 'text',
                  merged: true,
                  title: 'Age Range',
                },
                format: {},
              },
            ],
          },
          {
            name: 'values',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Revenue',
                  dim: '[Commerce.Revenue]',
                  datatype: 'numeric',
                  agg: 'sum',
                  title: 'Total Revenue',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: true,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                },
              },
            ],
          },
          {
            name: 'filters',
            items: [
              {
                jaql: {
                  datasource: {
                    title: 'Sample ECommerce',
                    fullname: 'LocalHost/Sample ECommerce',
                    id: 'localhost_aSampleIAAaECommerce',
                    address: 'LocalHost',
                    database: 'aSampleIAAaECommerce',
                  },
                  column: 'Gender',
                  dim: '[Commerce.Gender]',
                  datatype: 'text',
                  filter: {
                    explicit: false,
                    multiSelection: true,
                    exclude: {
                      members: ['Unspecified'],
                    },
                  },
                  title: 'Gender',
                  collapsed: true,
                },
                format: {
                  mask: {
                    isdefault: true,
                  },
                },
              },
            ],
          },
        ],
      },
      dashboardid: '6560ce3b6f1df500326a069c',
      options: {
        dashboardFiltersMode: 'select',
        selector: true,
        triggersDomready: true,
      },
      style: {
        legend: {
          enabled: false,
          position: 'bottom',
        },
        labels: {
          enabled: true,
          categories: true,
          value: false,
          percent: true,
          decimals: false,
        },
        dataLimits: {
          seriesCapacity: 100000,
        },
      },
      _dataSourcePermission: 'owner',
      userAuth: {
        dashboards: {
          create: true,
          delete: true,
          move: true,
          rename: true,
          duplicate: true,
          change_owner: true,
          toggle_edit_mode: true,
          edit_layout: true,
          edit_script: true,
          export_dash: true,
          export_jpeg: true,
          export_image: true,
          export_pdf: true,
          share: true,
          restore: true,
          copy_to_server: true,
          import: true,
          select_palette: true,
          replace_datasource: true,
          undo_import_dash: true,
          toggleDataExploration: true,
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            reorder: true,
            modify_type: true,
            toggle_auto_update: true,
            set_defaults: true,
            advanced: true,
            use_starred: true,
            modify_filter_relationship: true,
          },
        },
        widgets: {
          create: true,
          delete: true,
          rename: true,
          duplicate: true,
          copy_to_dashboard: true,
          edit: true,
          edit_script: true,
          change_type: true,
          export_csv: true,
          export_png: true,
          export_svg: true,
          export_pdf: true,
          modify_selection_attrs: true,
          modify_selection_mode: true,
          drill_to_anywhere: true,
          add_to_pulse: true,
          items: {
            create: true,
            delete: true,
            rename: true,
            modify: true,
            reorder: true,
            modify_type: true,
            modify_format: true,
            on_off: true,
            select_hierarchies: true,
          },
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            modify_layout: true,
            modify_type: true,
            modify_dashboard_filters: true,
            use_starred: true,
          },
          widgetViewOnly: false,
        },
        base: {
          isConsumer: false,
          isContributor: false,
          isAdmin: false,
          isSuper: true,
        },
      },
      _toDisableOptionsList: {
        widgets: {
          duplicate: false,
        },
      },
    },
    {
      _id: '6560ce3b6f1df500326a06b3',
      title: 'TOTAL SALES',
      type: 'indicator',
      subtype: 'indicator/gauge',
      oid: '6560ce3b6f1df500326a06a0',
      desc: null,
      source: null,
      owner: '64b933f34e4e67001a40353e',
      userId: '64b933f34e4e67001a40353e',
      created: '2023-11-24T16:24:27.495Z',
      lastUpdated: '2023-11-24T16:24:27.495Z',
      instanceType: 'owner',
      datasource: {
        title: 'Sample ECommerce',
        id: 'localhost_aSampleIAAaECommerce',
        address: 'LocalHost',
        database: 'aSampleIAAaECommerce',
      },
      selection: null,
      metadata: {
        ignore: {
          dimensions: [],
          ids: [],
          all: false,
        },
        panels: [
          {
            name: 'value',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Visit ID',
                  dim: '[Commerce.Visit ID]',
                  datatype: 'numeric',
                  agg: 'countduplicates',
                  title: '# of Visit ID',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: false,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                  color: {
                    type: 'color',
                  },
                },
              },
            ],
          },
          {
            name: 'secondary',
            items: [],
          },
          {
            name: 'min',
            items: [
              {
                jaql: {
                  formula: '0',
                  title: '0 (default)',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: false,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                },
              },
            ],
          },
          {
            name: 'max',
            items: [
              {
                jaql: {
                  type: 'measure',
                  formula: '100000',
                  context: {},
                  title: '100000',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: false,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                },
              },
            ],
          },
          {
            name: 'filters',
            items: [],
          },
        ],
      },
      dashboardid: '6560ce3b6f1df500326a069c',
      options: {
        title: false,
        dashboardFiltersMode: 'filter',
        selector: false,
        allowSelector: false,
        disallowSelector: true,
        triggersDomready: true,
        noTitle: false,
      },
      size: 'big',
      style: {
        'indicator/gauge': {
          subtype: 'round',
          skin: '1',
          components: {
            ticks: {
              inactive: false,
              enabled: true,
            },
            labels: {
              inactive: false,
              enabled: true,
            },
            title: {
              inactive: false,
              enabled: true,
            },
            secondaryTitle: {
              inactive: true,
              enabled: true,
            },
          },
        },
        'indicator/numeric': {
          subtype: 'simple',
          skin: '1',
          components: {
            title: {
              inactive: false,
              enabled: true,
            },
            icon: {
              inactive: false,
              enabled: true,
            },
            secondaryTitle: {
              inactive: true,
              enabled: true,
            },
          },
        },
        skin: '1',
        subtype: 'round',
        'indicator/pictogram': {},
        components: {
          ticks: {
            inactive: false,
            enabled: true,
          },
          labels: {
            inactive: false,
            enabled: true,
          },
          title: {
            inactive: false,
            enabled: false,
          },
          secondaryTitle: {
            inactive: true,
            enabled: true,
          },
        },
      },
      _dataSourcePermission: 'owner',
      userAuth: {
        dashboards: {
          create: true,
          delete: true,
          move: true,
          rename: true,
          duplicate: true,
          change_owner: true,
          toggle_edit_mode: true,
          edit_layout: true,
          edit_script: true,
          export_dash: true,
          export_jpeg: true,
          export_image: true,
          export_pdf: true,
          share: true,
          restore: true,
          copy_to_server: true,
          import: true,
          select_palette: true,
          replace_datasource: true,
          undo_import_dash: true,
          toggleDataExploration: true,
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            reorder: true,
            modify_type: true,
            toggle_auto_update: true,
            set_defaults: true,
            advanced: true,
            use_starred: true,
            modify_filter_relationship: true,
          },
        },
        widgets: {
          create: true,
          delete: true,
          rename: true,
          duplicate: true,
          copy_to_dashboard: true,
          edit: true,
          edit_script: true,
          change_type: true,
          export_csv: true,
          export_png: true,
          export_svg: true,
          export_pdf: true,
          modify_selection_attrs: true,
          modify_selection_mode: true,
          drill_to_anywhere: true,
          add_to_pulse: true,
          items: {
            create: true,
            delete: true,
            rename: true,
            modify: true,
            reorder: true,
            modify_type: true,
            modify_format: true,
            on_off: true,
            select_hierarchies: true,
          },
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            modify_layout: true,
            modify_type: true,
            modify_dashboard_filters: true,
            use_starred: true,
          },
          widgetViewOnly: false,
        },
        base: {
          isConsumer: false,
          isContributor: false,
          isAdmin: false,
          isSuper: true,
        },
      },
      _toDisableOptionsList: {
        widgets: {
          duplicate: false,
        },
      },
    },
    {
      _id: '6560ce3b6f1df500326a06b4',
      title: 'GENDER BREAKDOWN',
      type: 'chart/pie',
      subtype: 'pie/classic',
      oid: '6560ce3b6f1df500326a06a1',
      desc: null,
      source: null,
      owner: '64b933f34e4e67001a40353e',
      userId: '64b933f34e4e67001a40353e',
      created: '2023-11-24T16:24:27.495Z',
      lastUpdated: '2023-11-24T16:24:27.495Z',
      instanceType: 'owner',
      datasource: {
        title: 'Sample ECommerce',
        id: 'localhost_aSampleIAAaECommerce',
        address: 'LocalHost',
        database: 'aSampleIAAaECommerce',
      },
      selection: null,
      metadata: {
        ignore: {
          dimensions: [],
          ids: [],
          all: false,
        },
        panels: [
          {
            name: 'categories',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Gender',
                  dim: '[Commerce.Gender]',
                  datatype: 'text',
                  merged: true,
                  title: 'Gender',
                },
                format: {},
              },
            ],
          },
          {
            name: 'values',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Revenue',
                  dim: '[Commerce.Revenue]',
                  datatype: 'numeric',
                  agg: 'sum',
                  title: 'Total Revenue',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: true,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                },
              },
            ],
          },
          {
            name: 'filters',
            items: [
              {
                jaql: {
                  datasource: {
                    title: 'Sample ECommerce',
                    fullname: 'LocalHost/Sample ECommerce',
                    id: 'localhost_aSampleIAAaECommerce',
                    address: 'LocalHost',
                    database: 'aSampleIAAaECommerce',
                  },
                  column: 'Gender',
                  dim: '[Commerce.Gender]',
                  datatype: 'text',
                  filter: {
                    explicit: false,
                    multiSelection: true,
                    exclude: {
                      members: ['Unspecified'],
                    },
                  },
                  title: 'Gender',
                  collapsed: true,
                },
                format: {
                  mask: {
                    isdefault: true,
                  },
                },
              },
            ],
          },
        ],
      },
      dashboardid: '6560ce3b6f1df500326a069c',
      options: {
        dashboardFiltersMode: 'select',
        selector: true,
        triggersDomready: true,
      },
      style: {
        legend: {
          enabled: false,
          position: 'left',
        },
        labels: {
          enabled: true,
          categories: true,
          value: false,
          percent: true,
          decimals: false,
        },
        dataLimits: {
          seriesCapacity: 100000,
        },
      },
      _dataSourcePermission: 'owner',
      userAuth: {
        dashboards: {
          create: true,
          delete: true,
          move: true,
          rename: true,
          duplicate: true,
          change_owner: true,
          toggle_edit_mode: true,
          edit_layout: true,
          edit_script: true,
          export_dash: true,
          export_jpeg: true,
          export_image: true,
          export_pdf: true,
          share: true,
          restore: true,
          copy_to_server: true,
          import: true,
          select_palette: true,
          replace_datasource: true,
          undo_import_dash: true,
          toggleDataExploration: true,
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            reorder: true,
            modify_type: true,
            toggle_auto_update: true,
            set_defaults: true,
            advanced: true,
            use_starred: true,
            modify_filter_relationship: true,
          },
        },
        widgets: {
          create: true,
          delete: true,
          rename: true,
          duplicate: true,
          copy_to_dashboard: true,
          edit: true,
          edit_script: true,
          change_type: true,
          export_csv: true,
          export_png: true,
          export_svg: true,
          export_pdf: true,
          modify_selection_attrs: true,
          modify_selection_mode: true,
          drill_to_anywhere: true,
          add_to_pulse: true,
          items: {
            create: true,
            delete: true,
            rename: true,
            modify: true,
            reorder: true,
            modify_type: true,
            modify_format: true,
            on_off: true,
            select_hierarchies: true,
          },
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            modify_layout: true,
            modify_type: true,
            modify_dashboard_filters: true,
            use_starred: true,
          },
          widgetViewOnly: false,
        },
        base: {
          isConsumer: false,
          isContributor: false,
          isAdmin: false,
          isSuper: true,
        },
      },
      _toDisableOptionsList: {
        widgets: {
          duplicate: false,
        },
      },
    },
    {
      _id: '6560ce3b6f1df500326a06b5',
      title: 'TOTAL REVENUE',
      type: 'indicator',
      subtype: 'indicator/gauge',
      oid: '6560ce3b6f1df500326a06a2',
      desc: null,
      source: null,
      owner: '64b933f34e4e67001a40353e',
      userId: '64b933f34e4e67001a40353e',
      created: '2023-11-24T16:24:27.496Z',
      lastUpdated: '2023-11-24T16:24:27.496Z',
      instanceType: 'owner',
      datasource: {
        title: 'Sample ECommerce',
        id: 'localhost_aSampleIAAaECommerce',
        address: 'LocalHost',
        database: 'aSampleIAAaECommerce',
      },
      selection: null,
      metadata: {
        ignore: {
          dimensions: [],
          ids: [],
          all: false,
        },
        panels: [
          {
            name: 'value',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Revenue',
                  dim: '[Commerce.Revenue]',
                  datatype: 'numeric',
                  agg: 'sum',
                  title: 'Total Revenue',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: false,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                  color: {
                    type: 'color',
                  },
                },
              },
            ],
          },
          {
            name: 'secondary',
            items: [],
          },
          {
            name: 'min',
            items: [
              {
                jaql: {
                  formula: '0',
                  title: '0 (default)',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: false,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                },
              },
            ],
          },
          {
            name: 'max',
            items: [
              {
                jaql: {
                  type: 'measure',
                  formula: '125000000',
                  context: {},
                  title: '125000000',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: false,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                },
              },
            ],
          },
          {
            name: 'filters',
            items: [],
          },
        ],
      },
      dashboardid: '6560ce3b6f1df500326a069c',
      options: {
        title: false,
        dashboardFiltersMode: 'filter',
        selector: false,
        allowSelector: false,
        disallowSelector: true,
        triggersDomready: true,
        noTitle: false,
      },
      size: 'big',
      style: {
        'indicator/gauge': {
          subtype: 'round',
          skin: '1',
          components: {
            ticks: {
              inactive: false,
              enabled: true,
            },
            labels: {
              inactive: false,
              enabled: true,
            },
            title: {
              inactive: false,
              enabled: true,
            },
            secondaryTitle: {
              inactive: true,
              enabled: true,
            },
          },
        },
        'indicator/numeric': {
          subtype: 'simple',
          skin: '1',
          components: {
            title: {
              inactive: false,
              enabled: true,
            },
            icon: {
              inactive: false,
              enabled: true,
            },
            secondaryTitle: {
              inactive: true,
              enabled: true,
            },
          },
        },
        skin: '1',
        subtype: 'round',
        'indicator/pictogram': {},
        components: {
          ticks: {
            inactive: false,
            enabled: true,
          },
          labels: {
            inactive: false,
            enabled: true,
          },
          title: {
            inactive: false,
            enabled: false,
          },
          secondaryTitle: {
            inactive: true,
            enabled: true,
          },
        },
      },
      _dataSourcePermission: 'owner',
      userAuth: {
        dashboards: {
          create: true,
          delete: true,
          move: true,
          rename: true,
          duplicate: true,
          change_owner: true,
          toggle_edit_mode: true,
          edit_layout: true,
          edit_script: true,
          export_dash: true,
          export_jpeg: true,
          export_image: true,
          export_pdf: true,
          share: true,
          restore: true,
          copy_to_server: true,
          import: true,
          select_palette: true,
          replace_datasource: true,
          undo_import_dash: true,
          toggleDataExploration: true,
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            reorder: true,
            modify_type: true,
            toggle_auto_update: true,
            set_defaults: true,
            advanced: true,
            use_starred: true,
            modify_filter_relationship: true,
          },
        },
        widgets: {
          create: true,
          delete: true,
          rename: true,
          duplicate: true,
          copy_to_dashboard: true,
          edit: true,
          edit_script: true,
          change_type: true,
          export_csv: true,
          export_png: true,
          export_svg: true,
          export_pdf: true,
          modify_selection_attrs: true,
          modify_selection_mode: true,
          drill_to_anywhere: true,
          add_to_pulse: true,
          items: {
            create: true,
            delete: true,
            rename: true,
            modify: true,
            reorder: true,
            modify_type: true,
            modify_format: true,
            on_off: true,
            select_hierarchies: true,
          },
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            modify_layout: true,
            modify_type: true,
            modify_dashboard_filters: true,
            use_starred: true,
          },
          widgetViewOnly: false,
        },
        base: {
          isConsumer: false,
          isContributor: false,
          isAdmin: false,
          isSuper: true,
        },
      },
      _toDisableOptionsList: {
        widgets: {
          duplicate: false,
        },
      },
    },
    {
      _id: '6560ce3b6f1df500326a06b6',
      title: 'TOP CATEGORIES BY REVENUE, UNITS SOLD AND GENDER',
      type: 'chart/scatter',
      subtype: 'bubble/scatter',
      oid: '6560ce3b6f1df500326a06a3',
      desc: null,
      source: null,
      owner: '64b933f34e4e67001a40353e',
      userId: '64b933f34e4e67001a40353e',
      created: '2023-11-24T16:24:27.496Z',
      lastUpdated: '2023-11-24T16:24:27.496Z',
      instanceType: 'owner',
      datasource: {
        title: 'Sample ECommerce',
        id: 'localhost_aSampleIAAaECommerce',
        address: 'LocalHost',
        database: 'aSampleIAAaECommerce',
      },
      selection: null,
      metadata: {
        ignore: {
          dimensions: [],
          ids: [],
          all: false,
        },
        panels: [
          {
            name: 'x-axis',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Revenue',
                  dim: '[Commerce.Revenue]',
                  datatype: 'numeric',
                  agg: 'sum',
                  title: 'Total Revenue',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: true,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                },
              },
            ],
          },
          {
            name: 'y-axis',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Quantity',
                  dim: '[Commerce.Quantity]',
                  datatype: 'numeric',
                  agg: 'sum',
                  title: 'Total Quantity',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: true,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                },
              },
            ],
          },
          {
            name: 'point',
            items: [
              {
                jaql: {
                  table: 'Category',
                  column: 'Category',
                  dim: '[Category.Category]',
                  datatype: 'text',
                  merged: true,
                  title: 'Category',
                },
              },
            ],
          },
          {
            name: 'Break By / Color',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Gender',
                  dim: '[Commerce.Gender]',
                  datatype: 'text',
                  merged: true,
                  title: 'Gender',
                },
                format: {},
              },
            ],
          },
          {
            name: 'size',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Cost',
                  dim: '[Commerce.Cost]',
                  datatype: 'numeric',
                  agg: 'sum',
                  title: 'Total Cost',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: true,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                },
              },
            ],
          },
          {
            name: 'filters',
            items: [
              {
                jaql: {
                  datasource: {
                    title: 'Sample ECommerce',
                    fullname: 'LocalHost/Sample ECommerce',
                    id: 'localhost_aSampleIAAaECommerce',
                    address: 'LocalHost',
                    database: 'aSampleIAAaECommerce',
                  },
                  column: 'Gender',
                  dim: '[Commerce.Gender]',
                  datatype: 'text',
                  filter: {
                    explicit: false,
                    multiSelection: true,
                    exclude: {
                      members: ['Unspecified'],
                    },
                  },
                  title: 'Gender',
                  collapsed: true,
                },
                format: {
                  mask: {
                    isdefault: true,
                  },
                },
              },
              {
                jaql: {
                  datasource: {
                    title: 'Sample ECommerce',
                    fullname: 'LocalHost/Sample ECommerce',
                    id: 'localhost_aSampleIAAaECommerce',
                    address: 'LocalHost',
                    database: 'aSampleIAAaECommerce',
                  },
                  column: 'Category',
                  dim: '[Category.Category]',
                  datatype: 'text',
                  title: 'Category',
                  filter: {
                    top: 10,
                    by: {
                      column: 'Revenue',
                      dim: '[Commerce.Revenue]',
                      datatype: 'numeric',
                      agg: 'sum',
                      title: 'Total Revenue',
                    },
                  },
                  collapsed: false,
                },
                format: {
                  mask: {
                    isdefault: true,
                  },
                },
              },
            ],
          },
        ],
      },
      dashboardid: '6560ce3b6f1df500326a069c',
      options: {
        dashboardFiltersMode: 'select',
        selector: false,
        triggersDomready: true,
      },
      style: {
        legend: {
          enabled: true,
          position: 'right',
        },
        seriesLabels: {
          enabled: false,
          rotation: 0,
        },
        markerSize: {
          min: 12,
          max: 48,
          isRange: true,
          lowest: 10,
          highest: 60,
          step: 1,
          defaultSize: 10,
        },
        xAxis: {
          enabled: true,
          ticks: true,
          labels: {
            enabled: true,
            rotation: 0,
          },
          gridLines: false,
          logarithmic: true,
          title: {
            enabled: false,
            text: 'SALES',
          },
          intervalEnabled: false,
          logarithmicOld: true,
          hideMinMax: false,
        },
        yAxis: {
          enabled: true,
          ticks: true,
          labels: {
            enabled: true,
            rotation: 0,
          },
          gridLines: true,
          logarithmic: true,
          title: {
            enabled: true,
            text: 'QUANTITY',
          },
          intervalEnabled: false,
          logarithmicOld: true,
          hideMinMax: false,
        },
        dataLimits: {
          categoriesCapacityX: 500,
          categoriesCapacityY: 500,
          seriesCapacity: 50,
        },
      },
      _dataSourcePermission: 'owner',
      userAuth: {
        dashboards: {
          create: true,
          delete: true,
          move: true,
          rename: true,
          duplicate: true,
          change_owner: true,
          toggle_edit_mode: true,
          edit_layout: true,
          edit_script: true,
          export_dash: true,
          export_jpeg: true,
          export_image: true,
          export_pdf: true,
          share: true,
          restore: true,
          copy_to_server: true,
          import: true,
          select_palette: true,
          replace_datasource: true,
          undo_import_dash: true,
          toggleDataExploration: true,
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            reorder: true,
            modify_type: true,
            toggle_auto_update: true,
            set_defaults: true,
            advanced: true,
            use_starred: true,
            modify_filter_relationship: true,
          },
        },
        widgets: {
          create: true,
          delete: true,
          rename: true,
          duplicate: true,
          copy_to_dashboard: true,
          edit: true,
          edit_script: true,
          change_type: true,
          export_csv: true,
          export_png: true,
          export_svg: true,
          export_pdf: true,
          modify_selection_attrs: true,
          modify_selection_mode: true,
          drill_to_anywhere: true,
          add_to_pulse: true,
          items: {
            create: true,
            delete: true,
            rename: true,
            modify: true,
            reorder: true,
            modify_type: true,
            modify_format: true,
            on_off: true,
            select_hierarchies: true,
          },
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            modify_layout: true,
            modify_type: true,
            modify_dashboard_filters: true,
            use_starred: true,
          },
          widgetViewOnly: false,
        },
        base: {
          isConsumer: false,
          isContributor: false,
          isAdmin: false,
          isSuper: true,
        },
      },
      _toDisableOptionsList: {
        widgets: {
          duplicate: false,
        },
      },
    },
    {
      _id: '6560ce3b6f1df500326a06b7',
      title: 'REVENUE vs.UNITS SOLD',
      type: 'chart/line',
      subtype: 'line/spline',
      oid: '6560ce3b6f1df500326a06a4',
      desc: null,
      source: null,
      owner: '64b933f34e4e67001a40353e',
      userId: '64b933f34e4e67001a40353e',
      created: '2023-11-24T16:24:27.496Z',
      lastUpdated: '2023-11-24T16:24:27.496Z',
      instanceType: 'owner',
      datasource: {
        title: 'Sample ECommerce',
        id: 'localhost_aSampleIAAaECommerce',
        address: 'LocalHost',
        database: 'aSampleIAAaECommerce',
      },
      selection: null,
      metadata: {
        ignore: {
          dimensions: [],
          ids: [],
          all: false,
        },
        panels: [
          {
            name: 'x-axis',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Date',
                  dim: '[Commerce.Date (Calendar)]',
                  datatype: 'datetime',
                  merged: true,
                  level: 'months',
                  title: 'Months in Date',
                },
                format: {
                  mask: {
                    years: 'yyyy',
                    quarters: 'yyyy Q',
                    months: 'M-yy',
                    days: 'shortDate',
                  },
                },
              },
            ],
          },
          {
            name: 'values',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Revenue',
                  dim: '[Commerce.Revenue]',
                  datatype: 'numeric',
                  agg: 'sum',
                  title: 'Total Revenue',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: true,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                  color: {
                    type: 'color',
                  },
                },
              },
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Quantity',
                  dim: '[Commerce.Quantity]',
                  datatype: 'numeric',
                  agg: 'sum',
                  title: 'Total Quantity',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: true,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                  color: {
                    type: 'color',
                  },
                },
                y2: true,
                singleSeriesType: 'column',
              },
            ],
          },
          {
            name: 'break by',
            items: [],
          },
          {
            name: 'filters',
            items: [],
          },
        ],
      },
      dashboardid: '6560ce3b6f1df500326a069c',
      options: {
        dashboardFiltersMode: 'filter',
        selector: true,
        triggersDomready: true,
      },
      style: {
        lineWidth: {
          width: 'bold',
        },
        legend: {
          enabled: true,
          position: 'bottom',
        },
        seriesLabels: {
          enabled: false,
          rotation: 0,
        },
        markers: {
          enabled: true,
          fill: 'hollow',
          size: 'small',
        },
        xAxis: {
          enabled: true,
          ticks: true,
          labels: {
            enabled: true,
            rotation: 0,
          },
          gridLines: false,
          title: {
            enabled: false,
            text: 'MONTH',
          },
          x2Title: {
            enabled: false,
          },
          intervalEnabled: false,
        },
        yAxis: {
          inactive: false,
          enabled: true,
          ticks: true,
          labels: {
            enabled: true,
            rotation: 0,
          },
          gridLines: true,
          logarithmic: true,
          title: {
            enabled: true,
            text: 'SALES',
          },
          min: '',
          intervalEnabled: false,
        },
        y2Axis: {
          inactive: false,
          enabled: true,
          ticks: true,
          labels: {
            enabled: true,
            rotation: 0,
          },
          gridLines: false,
          logarithmic: false,
          title: {
            enabled: true,
            text: 'QUANTITY',
          },
          templateMainYHasGridLines: true,
          intervalEnabled: true,
        },
        navigator: {
          enabled: true,
        },
        dataLimits: {
          seriesCapacity: 50,
          categoriesCapacity: 100000,
        },
      },
      _dataSourcePermission: 'owner',
      userAuth: {
        dashboards: {
          create: true,
          delete: true,
          move: true,
          rename: true,
          duplicate: true,
          change_owner: true,
          toggle_edit_mode: true,
          edit_layout: true,
          edit_script: true,
          export_dash: true,
          export_jpeg: true,
          export_image: true,
          export_pdf: true,
          share: true,
          restore: true,
          copy_to_server: true,
          import: true,
          select_palette: true,
          replace_datasource: true,
          undo_import_dash: true,
          toggleDataExploration: true,
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            reorder: true,
            modify_type: true,
            toggle_auto_update: true,
            set_defaults: true,
            advanced: true,
            use_starred: true,
            modify_filter_relationship: true,
          },
        },
        widgets: {
          create: true,
          delete: true,
          rename: true,
          duplicate: true,
          copy_to_dashboard: true,
          edit: true,
          edit_script: true,
          change_type: true,
          export_csv: true,
          export_png: true,
          export_svg: true,
          export_pdf: true,
          modify_selection_attrs: true,
          modify_selection_mode: true,
          drill_to_anywhere: true,
          add_to_pulse: true,
          items: {
            create: true,
            delete: true,
            rename: true,
            modify: true,
            reorder: true,
            modify_type: true,
            modify_format: true,
            on_off: true,
            select_hierarchies: true,
          },
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            modify_layout: true,
            modify_type: true,
            modify_dashboard_filters: true,
            use_starred: true,
          },
          widgetViewOnly: false,
        },
        base: {
          isConsumer: false,
          isContributor: false,
          isAdmin: false,
          isSuper: true,
        },
      },
      _toDisableOptionsList: {
        widgets: {
          duplicate: false,
        },
      },
    },
    {
      _id: '6560ce3b6f1df500326a06b8',
      title: 'TOP 3 CATEGORIES BY REVENUE AND AGE',
      type: 'chart/bar',
      subtype: 'bar/stacked',
      oid: '6560ce3b6f1df500326a06a5',
      desc: null,
      source: null,
      owner: '64b933f34e4e67001a40353e',
      userId: '64b933f34e4e67001a40353e',
      created: '2023-11-24T16:24:27.496Z',
      lastUpdated: '2023-11-24T16:24:27.496Z',
      instanceType: 'owner',
      datasource: {
        title: 'Sample ECommerce',
        id: 'localhost_aSampleIAAaECommerce',
        address: 'LocalHost',
        database: 'aSampleIAAaECommerce',
      },
      selection: null,
      metadata: {
        ignore: {
          dimensions: [],
          ids: [],
          all: false,
        },
        panels: [
          {
            name: 'categories',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Age Range',
                  dim: '[Commerce.Age Range]',
                  datatype: 'text',
                  merged: true,
                  title: 'Age Range',
                },
              },
            ],
          },
          {
            name: 'values',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Revenue',
                  dim: '[Commerce.Revenue]',
                  datatype: 'numeric',
                  agg: 'sum',
                  title: 'Total Revenue',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: true,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                },
              },
            ],
          },
          {
            name: 'break by',
            items: [
              {
                jaql: {
                  table: 'Category',
                  column: 'Category',
                  dim: '[Category.Category]',
                  datatype: 'text',
                  merged: true,
                  title: 'Category',
                },
                format: {},
              },
            ],
          },
          {
            name: 'filters',
            items: [
              {
                jaql: {
                  datasource: {
                    title: 'Sample ECommerce',
                    fullname: 'LocalHost/Sample ECommerce',
                    id: 'localhost_aSampleIAAaECommerce',
                    address: 'LocalHost',
                    database: 'aSampleIAAaECommerce',
                  },
                  table: 'Category',
                  column: 'Category',
                  dim: '[Category.Category]',
                  datatype: 'text',
                  merged: true,
                  title: 'Category',
                  filter: {
                    top: 3,
                    by: {
                      table: 'Commerce',
                      column: 'Revenue',
                      dim: '[Commerce.Revenue]',
                      datatype: 'numeric',
                      agg: 'sum',
                      title: 'Total Revenue',
                    },
                  },
                  collapsed: false,
                },
                format: {
                  mask: {
                    isdefault: true,
                  },
                },
              },
            ],
          },
        ],
      },
      dashboardid: '6560ce3b6f1df500326a069c',
      options: {
        dashboardFiltersMode: 'filter',
        selector: true,
        triggersDomready: true,
        maxCharsPerLabelXAxis: 9,
      },
      style: {
        legend: {
          enabled: true,
          position: 'bottom',
        },
        seriesLabels: {
          enabled: false,
          rotation: 0,
        },
        xAxis: {
          enabled: true,
          ticks: true,
          labels: {
            enabled: true,
            rotation: 0,
          },
          gridLines: false,
          title: {
            enabled: true,
            text: 'AGE RANGE',
          },
          x2Title: {
            enabled: false,
          },
          intervalEnabled: false,
        },
        yAxis: {
          inactive: false,
          enabled: true,
          ticks: true,
          labels: {
            enabled: true,
            rotation: 0,
          },
          gridLines: true,
          logarithmic: false,
          title: {
            enabled: true,
            text: 'SALES',
          },
          intervalEnabled: true,
          hideMinMax: false,
        },
        y2Axis: {
          inactive: true,
          enabled: true,
          ticks: true,
          labels: {
            enabled: true,
            rotation: 0,
          },
          gridLines: false,
          logarithmic: false,
          title: {
            enabled: false,
          },
          intervalEnabled: true,
          hideMinMax: false,
        },
        dataLimits: {
          seriesCapacity: 50,
          categoriesCapacity: 100000,
        },
        navigator: {
          enabled: true,
        },
      },
      viewState: {
        activeTab: 'design',
      },
      _dataSourcePermission: 'owner',
      userAuth: {
        dashboards: {
          create: true,
          delete: true,
          move: true,
          rename: true,
          duplicate: true,
          change_owner: true,
          toggle_edit_mode: true,
          edit_layout: true,
          edit_script: true,
          export_dash: true,
          export_jpeg: true,
          export_image: true,
          export_pdf: true,
          share: true,
          restore: true,
          copy_to_server: true,
          import: true,
          select_palette: true,
          replace_datasource: true,
          undo_import_dash: true,
          toggleDataExploration: true,
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            reorder: true,
            modify_type: true,
            toggle_auto_update: true,
            set_defaults: true,
            advanced: true,
            use_starred: true,
            modify_filter_relationship: true,
          },
        },
        widgets: {
          create: true,
          delete: true,
          rename: true,
          duplicate: true,
          copy_to_dashboard: true,
          edit: true,
          edit_script: true,
          change_type: true,
          export_csv: true,
          export_png: true,
          export_svg: true,
          export_pdf: true,
          modify_selection_attrs: true,
          modify_selection_mode: true,
          drill_to_anywhere: true,
          add_to_pulse: true,
          items: {
            create: true,
            delete: true,
            rename: true,
            modify: true,
            reorder: true,
            modify_type: true,
            modify_format: true,
            on_off: true,
            select_hierarchies: true,
          },
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            modify_layout: true,
            modify_type: true,
            modify_dashboard_filters: true,
            use_starred: true,
          },
          widgetViewOnly: false,
        },
        base: {
          isConsumer: false,
          isContributor: false,
          isAdmin: false,
          isSuper: true,
        },
      },
      _toDisableOptionsList: {
        widgets: {
          duplicate: false,
        },
      },
    },
    {
      _id: '67111e2daf1abd22adead46d',
      title: '',
      type: 'tablewidget',
      subtype: 'tablewidget',
      oid: '67111cb76ab71f0032d8599d',
      desc: null,
      source: null,
      owner: '64b933f34e4e67001a40353e',
      created: '2024-10-17T14:18:31.285Z',
      lastUpdated: '2024-10-17T14:24:45.270Z',
      datasource: {
        address: 'LocalHost',
        title: 'Sample ECommerce',
        id: 'localhost_aSampleIAAaECommerce',
        database: 'aSampleIAAaECommerce',
        fullname: 'localhost/Sample ECommerce',
        live: false,
      },
      selection: null,
      metadata: {
        ignore: {
          dimensions: [],
          ids: [],
          all: false,
        },
        panels: [
          {
            name: 'columns',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Brand ID',
                  dim: '[Commerce.Brand ID]',
                  datatype: 'numeric',
                  merged: true,
                  title: 'Brand ID',
                },
                instanceid: 'A9E9F-5167-08',
                field: {
                  id: '[Commerce.Brand ID]',
                  index: 0,
                },
                panel: 'rows',
              },
              {
                jaql: {
                  table: 'Brand',
                  column: 'Brand',
                  dim: '[Brand.Brand]',
                  datatype: 'text',
                  merged: true,
                  title: 'Brand',
                },
                instanceid: 'C11FC-EC06-60',
                panel: 'rows',
                field: {
                  id: '[Brand.Brand]',
                  index: 1,
                },
              },
            ],
          },
          {
            name: 'filters',
            items: [],
          },
        ],
        usedFormulasMapping: {},
      },
      tags: [],
      style: {
        'borders/all': true,
        'borders/grid': false,
        'borders/rows': false,
        'borders/columns': false,
        'width/content': true,
        'width/window': false,
        'colors/headers': true,
        'colors/rows': true,
        'colors/columns': false,
        'wordwrap/headers': true,
        'wordwrap/rows': false,
        scroll: false,
        pageSize: 25,
        tableState: {
          columns: [
            {
              visible: true,
              search: {},
            },
            {
              visible: true,
              search: {},
            },
          ],
          colResize: {
            columns: ['84.3906px', '191.539px'],
            tableSize: 275,
          },
          headers: [
            {
              title: 'Brand ID',
              dim: '[Commerce.Brand ID]',
              datatype: 'numeric',
            },
            {
              title: 'Brand',
              dim: '[Brand.Brand]',
              datatype: 'text',
            },
          ],
          length: 25,
          start: 0,
          iScrollerTopRow: 0,
          iScroller: 0,
          search: {
            search: '',
            smart: true,
            regex: false,
            caseInsensitive: true,
          },
          order: [[0, 'asc']],
          time: 1729175082658,
        },
        automaticHeight: true,
        narration: {
          enabled: false,
          display: 'above',
          format: 'bullets',
          verbosity: 'medium',
          up_sentiment: 'good',
          aggregation: 'sum',
          labels: [
            {
              id: 'brand_id',
              title: 'Brand ID',
              singular: 'Brand ID',
              plural: 'Brand ID',
            },
            {
              id: 'brand',
              title: 'Brand',
              singular: 'Brand',
              plural: 'Brand',
            },
          ],
        },
      },
      instanceid: '86434-620C-39',
      realTimeRefreshing: false,
      options: {
        dashboardFiltersMode: 'filter',
        disallowSelector: true,
        triggersDomready: true,
        selector: false,
        dataTypes: {
          dimensions: true,
          measures: false,
          filter: false,
        },
        autoUpdateOnEveryChange: true,
        supportsHierarchies: false,
      },
      dashboardid: '6560ce3b6f1df500326a069c',
      userId: '64b933f34e4e67001a40353e',
      currentPage: 0,
      instanceType: 'owner',
    },
    {
      _id: '67237bc573cbd2676208678c',
      title: 'Revenue by age in Ukraine,France and Israel',
      type: 'chart/polar',
      subtype: 'area/polar',
      oid: '672352d827ea67002bdcf485',
      desc: '',
      source: null,
      owner: '64b933f34e4e67001a40353e',
      created: '2024-10-31T09:50:16.433Z',
      lastUpdated: '2024-10-31T14:55:39.850Z',
      datasource: {
        address: 'LocalHost',
        title: 'Sample ECommerce',
        id: 'localhost_aSampleIAAaECommerce',
        database: 'aSampleIAAaECommerce',
        fullname: 'localhost/Sample ECommerce',
        live: false,
      },
      selection: null,
      metadata: {
        ignore: {
          dimensions: [],
          ids: [],
          all: false,
        },
        panels: [
          {
            name: 'categories',
            items: [
              {
                jaql: {
                  table: 'Country',
                  column: 'Country',
                  dim: '[Country.Country]',
                  datatype: 'text',
                  merged: true,
                  title: 'Country',
                },
                instanceid: '16BB3-B171-C3',
                panel: 'rows',
              },
            ],
          },
          {
            name: 'values',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Revenue',
                  dim: '[Commerce.Revenue]',
                  datatype: 'numeric',
                  agg: 'sum',
                  title: 'Total Revenue',
                },
                instanceid: '6916B-31E2-37',
                panel: 'measures',
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: true,
                    },
                    separated: true,
                    decimals: 'auto',
                    abbreviateAll: false,
                    isdefault: true,
                  },
                },
              },
            ],
          },
          {
            name: 'break by',
            items: [
              {
                jaql: {
                  table: 'Commerce',
                  column: 'Age Range',
                  dim: '[Commerce.Age Range]',
                  datatype: 'text',
                  merged: true,
                  title: 'Age Range',
                },
                instanceid: '9DFE2-2712-CD',
                panel: 'columns',
                format: {
                  members: {},
                },
              },
            ],
          },
          {
            name: 'filters',
            items: [
              {
                jaql: {
                  dimension: {
                    table: 'Country',
                    column: 'Country',
                    dim: '[Country.Country]',
                    datatype: 'text',
                    merged: true,
                    title: 'Country',
                  },
                  table: 'Country',
                  column: 'Country',
                  dim: '[Country.Country]',
                  datatype: 'text',
                  merged: true,
                  datasource: {
                    address: 'LocalHost',
                    title: 'Sample ECommerce',
                    id: 'localhost_aSampleIAAaECommerce',
                    database: 'aSampleIAAaECommerce',
                    fullname: 'localhost/Sample ECommerce',
                    live: false,
                  },
                  firstday: 'mon',
                  locale: 'en-gb',
                  filter: {
                    explicit: true,
                    multiSelection: true,
                    members: ['France', 'Israel', 'Ukraine'],
                  },
                  title: 'Country',
                  collapsed: true,
                },
                instanceid: 'D0658-314A-9D',
                panel: 'scope',
              },
            ],
          },
        ],
        usedFormulasMapping: {},
      },
      style: {
        legend: {
          enabled: true,
          position: 'bottom',
        },
        seriesLabels: {
          enabled: false,
          rotation: 0,
        },
        categories: {
          enabled: true,
          labels: {
            enabled: true,
            rotation: 0,
          },
          title: {
            enabled: false,
          },
          gridLines: true,
          isIntervalEnabled: false,
        },
        axis: {
          enabled: true,
          labels: {
            enabled: true,
            rotation: 0,
          },
          gridLines: true,
          logarithmic: false,
          isIntervalEnabled: true,
        },
        dataLimits: {
          seriesCapacity: 50,
          categoriesCapacity: 200,
        },
        narration: {
          enabled: false,
          display: 'above',
          format: 'bullets',
          verbosity: 'medium',
          up_sentiment: 'good',
          aggregation: 'sum',
          labels: [
            {
              id: 'country',
              title: 'Country',
              singular: 'Country',
              plural: 'Country',
            },
            {
              id: 'age_range',
              title: 'Age Range',
              singular: 'Age Range',
              plural: 'Age Range',
            },
          ],
        },
      },
      dashboardid: '6560ce3b6f1df500326a069c',
      userId: '64b933f34e4e67001a40353e',
      instanceid: '86434-620C-39',
      options: {
        dashboardFiltersMode: 'select',
        selector: true,
        triggersDomready: true,
        autoUpdateOnEveryChange: true,
        drillToAnywhere: true,
      },
      realTimeRefreshing: false,
      tags: [],
      viewState: {
        activeTab: 'design',
      },
      instanceType: 'owner',
      _dataSourcePermission: 'owner',
      userAuth: {
        dashboards: {
          create: true,
          delete: true,
          move: true,
          rename: true,
          duplicate: true,
          change_owner: true,
          toggle_edit_mode: true,
          edit_layout: true,
          edit_script: true,
          export_dash: true,
          export_jpeg: true,
          export_image: true,
          export_pdf: true,
          share: true,
          restore: true,
          copy_to_server: true,
          import: true,
          select_palette: true,
          replace_datasource: true,
          undo_import_dash: true,
          toggleDataExploration: true,
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            reorder: true,
            modify_type: true,
            toggle_auto_update: true,
            set_defaults: true,
            advanced: true,
            use_starred: true,
            modify_filter_relationship: true,
          },
        },
        widgets: {
          create: true,
          delete: true,
          rename: true,
          duplicate: true,
          copy_to_dashboard: true,
          edit: true,
          edit_script: true,
          change_type: true,
          export_csv: true,
          export_png: true,
          export_svg: true,
          export_pdf: true,
          modify_selection_attrs: true,
          modify_selection_mode: true,
          drill_to_anywhere: true,
          add_to_pulse: true,
          items: {
            create: true,
            delete: true,
            rename: true,
            modify: true,
            reorder: true,
            modify_type: true,
            modify_format: true,
            on_off: true,
            select_hierarchies: true,
          },
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            modify_layout: true,
            modify_type: true,
            modify_dashboard_filters: true,
            use_starred: true,
          },
          widgetViewOnly: false,
        },
        base: {
          isConsumer: false,
          isContributor: false,
          isAdmin: false,
          isSuper: true,
        },
      },
      _toDisableOptionsList: {
        widgets: {
          duplicate: false,
        },
      },
    },
    {
      _id: '674220f0bc6751795fbd04a3',
      title: 'total of Revenue by Country',
      type: 'treemap',
      subtype: 'treemap',
      oid: '6742206527ea67002bdcf6ac',
      desc: '',
      source: null,
      owner: '64b933f34e4e67001a40353e',
      created: '2024-11-23T18:35:17.639Z',
      lastUpdated: '2024-11-23T18:37:36.886Z',
      datasource: {
        address: 'LocalHost',
        title: 'Sample ECommerce',
        id: 'localhost_aSampleIAAaECommerce',
        database: 'aSampleIAAaECommerce',
        fullname: 'localhost/Sample ECommerce',
        live: false,
      },
      selection: null,
      metadata: {
        ignore: {
          dimensions: [],
          ids: [],
          all: false,
        },
        panels: [
          {
            name: 'categories',
            items: [
              {
                jaql: {
                  dim: '[Country.Country]',
                  table: 'Country',
                  column: 'Country',
                  datatype: 'text',
                  title: 'Country',
                },
                panel: 'rows',
                instanceid: '3BC2C-2046-F4',
              },
            ],
          },
          {
            name: 'size',
            items: [
              {
                jaql: {
                  type: 'measure',
                  context: {
                    '[d6fb]': {
                      dim: '[Commerce.Revenue]',
                      table: 'Commerce',
                      column: 'Revenue',
                    },
                  },
                  formula: 'sum([d6fb])',
                  title: 'total of Revenue',
                },
                panel: 'measures',
                instanceid: '1E8E7-95C7-66',
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: true,
                    },
                    separated: true,
                    decimals: 'auto',
                    abbreviateAll: false,
                    isdefault: true,
                  },
                },
              },
            ],
          },
          {
            name: 'color',
            items: [],
          },
          {
            name: 'filters',
            items: [],
          },
        ],
        usedFormulasMapping: {},
      },
      style: {
        'title/1': true,
        'title/2': true,
        'title/3': true,
        'tooltip/value': true,
        'tooltip/contribution': false,
        narration: {
          enabled: false,
          display: 'above',
          format: 'bullets',
          verbosity: 'medium',
          up_sentiment: 'good',
          aggregation: 'sum',
          labels: [
            {
              id: 'country',
              title: 'Country',
              singular: 'Country',
              plural: 'Country',
            },
          ],
        },
      },
      dashboardid: '6560ce3b6f1df500326a069c',
      userId: '64b933f34e4e67001a40353e',
      instanceid: '86434-620C-39',
      options: {
        dashboardFiltersMode: 'select',
        triggersDomready: true,
        selector: true,
        disallowSelector: false,
        autoUpdateOnEveryChange: true,
        supportsHierarchies: false,
      },
      realTimeRefreshing: false,
      instanceType: 'owner',
    },
  ],
  _dataSourcePermission: 'owner',
  userAuth: {
    dashboards: {
      create: true,
      delete: true,
      move: true,
      rename: true,
      duplicate: true,
      change_owner: true,
      toggle_edit_mode: true,
      edit_layout: true,
      edit_script: true,
      export_dash: true,
      export_jpeg: true,
      export_image: true,
      export_pdf: true,
      share: true,
      restore: true,
      copy_to_server: true,
      import: true,
      select_palette: true,
      replace_datasource: true,
      undo_import_dash: true,
      toggleDataExploration: true,
      filters: {
        create: true,
        delete: true,
        save: true,
        on_off: true,
        toggle_expansion: true,
        modify: true,
        reorder: true,
        modify_type: true,
        toggle_auto_update: true,
        set_defaults: true,
        advanced: true,
        use_starred: true,
        modify_filter_relationship: true,
      },
    },
    widgets: {
      create: true,
      delete: true,
      rename: true,
      duplicate: true,
      copy_to_dashboard: true,
      edit: true,
      edit_script: true,
      change_type: true,
      export_csv: true,
      export_png: true,
      export_svg: true,
      export_pdf: true,
      modify_selection_attrs: true,
      modify_selection_mode: true,
      drill_to_anywhere: true,
      add_to_pulse: true,
      items: {
        create: true,
        delete: true,
        rename: true,
        modify: true,
        reorder: true,
        modify_type: true,
        modify_format: true,
        on_off: true,
        select_hierarchies: true,
      },
      filters: {
        create: true,
        delete: true,
        save: true,
        on_off: true,
        toggle_expansion: true,
        modify: true,
        modify_layout: true,
        modify_type: true,
        modify_dashboard_filters: true,
        use_starred: true,
      },
      widgetViewOnly: false,
    },
    base: {
      isConsumer: false,
      isContributor: false,
      isAdmin: false,
      isSuper: true,
    },
  },
  _toDisableOptionsList: {
    dashboards: {
      duplicate: false,
      export_dash: false,
    },
  },
} as unknown as DashboardDto;
