import { DashboardDto } from '../../api/types/dashboard-dto';

/**
 * 'Sample - Healthcare' dashboard from Analitycs tab in Sisense.
 *
 * Pivot widget replaced with table one.
 */
export const sampleHealthcareDashboard = {
  _id: '6560d4326f1df500326a06c8',
  title: 'Sample - Healthcare',
  desc: '',
  source: null,
  type: 'dashboard',
  shares: [
    {
      shareId: '64b933f34e4e67001a40353e',
      type: 'user',
    },
  ],
  style: {
    palette: {
      _id: '64b933f34e4e67001a403549',
      colors: [
        '#117899',
        '#60B8CC',
        '#5CA793',
        '#A2B86C',
        '#EBC844',
        '#ECAA38',
        '#EF8B2C',
        '#F16C20',
        '#D94E1F',
        '#C02E1D',
        '#893B32',
        '#0D3C55',
        '#0F5B78',
      ],
      name: 'Midnight Light',
      isDefault: false,
      sortOrder: 30,
      isSystem: true,
    },
  },
  owner: '64b933f34e4e67001a40353e',
  userId: '64b933f34e4e67001a40353e',
  created: '2023-11-24T16:49:54.752Z',
  lastUpdated: '2023-11-24T17:27:16.435Z',
  lastUsed: '2023-11-24T16:49:56.152Z',
  usageCount: 1,
  layout: {
    type: 'columnar',
    columns: [
      {
        width: 100,
        cells: [
          {
            subcells: [
              {
                elements: [
                  {
                    minHeight: 48,
                    maxHeight: 1028,
                    height: '120px',
                    minWidth: 48,
                    maxWidth: 1028,
                    defaultWidth: 512,
                    widgetid: '6560d4326f1df500326a06bc',
                  },
                ],
                width: 24.034334763948497,
                stretchable: false,
                pxlWidth: 332,
                index: 0,
              },
              {
                elements: [
                  {
                    minHeight: 48,
                    maxHeight: 1028,
                    height: '120px',
                    minWidth: 48,
                    maxWidth: 1028,
                    defaultWidth: 512,
                    widgetid: '6560d4326f1df500326a06bd',
                  },
                ],
                width: 26.609442060085836,
                stretchable: false,
                pxlWidth: 372,
                index: 1,
              },
              {
                elements: [
                  {
                    minHeight: 48,
                    maxHeight: 1028,
                    height: '120px',
                    minWidth: 48,
                    maxWidth: 1028,
                    defaultWidth: 512,
                    widgetid: '6560d4326f1df500326a06be',
                  },
                ],
                width: 25.17882689556509,
                stretchable: false,
                pxlWidth: 352,
                index: 2,
              },
              {
                elements: [
                  {
                    minHeight: 48,
                    maxHeight: 1028,
                    minWidth: 48,
                    maxWidth: 1028,
                    defaultWidth: 512,
                    widgetid: '6560d4326f1df500326a06ba',
                    height: '120px',
                  },
                ],
                width: 24.17739628040058,
                stretchable: false,
                pxlWidth: 1046,
                index: 3,
              },
            ],
          },
          {
            subcells: [
              {
                elements: [
                  {
                    minHeight: 96,
                    maxHeight: 2048,
                    minWidth: 128,
                    maxWidth: 2048,
                    height: '312px',
                    defaultWidth: 512,
                    widgetid: '6560d4326f1df500326a06bf',
                  },
                ],
                width: 100,
                stretchable: false,
                pxlWidth: 1383,
                index: 0,
              },
            ],
          },
          {
            subcells: [
              {
                elements: [
                  {
                    minHeight: 96,
                    maxHeight: 2048,
                    minWidth: 128,
                    maxWidth: 2048,
                    height: '324px',
                    defaultWidth: 512,
                    widgetid: '6560d4326f1df500326a06bb',
                  },
                ],
                width: 49.78540772532189,
                stretchable: false,
                pxlWidth: 689,
                index: 0,
              },
              {
                elements: [
                  {
                    minHeight: 128,
                    maxHeight: 2048,
                    minWidth: 128,
                    maxWidth: 2048,
                    height: '324px',
                    defaultWidth: 512,
                    widgetid: '6560d4326f1df500326a06c0',
                  },
                ],
                width: 50.21459227467811,
                stretchable: false,
                pxlWidth: 694,
                index: 1,
              },
            ],
          },
        ],
        pxlWidth: 1391,
        index: 0,
      },
    ],
  },
  instanceType: 'owner',
  original: null,
  previewLayout: [],
  datasource: {
    title: 'Sample Healthcare',
    fullname: 'LocalHost/Sample Healthcare',
    id: 'localhost_aSampleIAAaHealthcare',
    address: 'localHost',
    database: 'aSampleIAAaHealthcare',
  },
  editing: true,
  filters: [
    {
      jaql: {
        datasource: {
          title: 'Sample Healthcare',
          fullname: 'LocalHost/Sample Healthcare',
          id: 'localhost_aSampleIAAaHealthcare',
          address: 'localHost',
          database: 'aSampleIAAaHealthcare',
        },
        column: 'Gender',
        dim: '[Patients.Gender]',
        datatype: 'text',
        filter: {
          explicit: false,
          multiSelection: true,
          all: true,
        },
        title: 'GENDER',
        collapsed: true,
      },
      isCascading: false,
    },
    {
      jaql: {
        datasource: {
          title: 'Sample Healthcare',
          fullname: 'LocalHost/Sample Healthcare',
          id: 'localhost_aSampleIAAaHealthcare',
          address: 'localHost',
          database: 'aSampleIAAaHealthcare',
        },
        column: 'Divison_name',
        dim: '[Divisions.Divison_name]',
        datatype: 'text',
        filter: {
          explicit: false,
          multiSelection: true,
          all: true,
        },
        title: 'DIVISION',
        collapsed: false,
      },
      isCascading: false,
    },
    {
      jaql: {
        datasource: {
          title: 'Sample Healthcare',
          fullname: 'LocalHost/Sample Healthcare',
          id: 'localhost_aSampleIAAaHealthcare',
          address: 'localHost',
          database: 'aSampleIAAaHealthcare',
        },
        table: 'Admissions',
        column: 'Admission_Time',
        dim: '[Admissions.Admission_Time (Calendar)]',
        datatype: 'datetime',
        level: 'years',
        title: 'ADMISSION DATE',
        merged: true,
        collapsed: false,
        filter: {
          explicit: true,
          multiSelection: true,
          members: ['2013-01-01T00:00:00'],
        },
      },
      isCascading: false,
    },
    {
      jaql: {
        datasource: {
          title: 'Sample Healthcare',
          fullname: 'LocalHost/Sample Healthcare',
          id: 'localhost_aSampleIAAaHealthcare',
          address: 'localHost',
          database: 'aSampleIAAaHealthcare',
        },
        table: 'Diagnosis',
        column: 'Description',
        dim: '[Diagnosis.Description]',
        datatype: 'text',
        title: 'TOP DIAGNOSES',
        merged: true,
        collapsed: false,
        filter: {
          top: 10,
          by: {
            type: 'measure',
            formula: 'DupCount([BDE1B-4DA])',
            context: {
              '[BDE1B-4DA]': {
                table: 'Admissions',
                column: 'Patient_ID',
                dim: '[Admissions.Patient_ID]',
                datatype: 'numeric',
                title: 'Patient_ID',
              },
            },
            title: 'DupCount([Patient_ID])',
          },
        },
      },
      isCascading: false,
    },
  ],
  oid: '6560d4326f1df500326a06b9',
  options: {
    manual: false,
  },
  parentFolder: null,
  tenantId: '64b933f34e4e67001a40354b',
  settings: {
    autoUpdateOnFiltersChange: true,
  },
  lastOpened: '2023-11-24T17:30:01.020Z',
  widgets: [
    {
      _id: '6560d4326f1df500326a06c9',
      title: 'TOTAL PATIENTS ADMITTED',
      type: 'indicator',
      subtype: 'indicator/numeric',
      oid: '6560d4326f1df500326a06ba',
      desc: null,
      source: null,
      owner: '64b933f34e4e67001a40353e',
      userId: '64b933f34e4e67001a40353e',
      created: '2023-11-24T16:49:54.752Z',
      lastUpdated: '2023-11-24T16:49:54.752Z',
      instanceType: 'owner',
      datasource: {
        title: 'Sample Healthcare',
        fullname: 'LocalHost/Sample Healthcare',
        id: 'localhost_aSampleIAAaHealthcare',
        address: 'localHost',
        database: 'aSampleIAAaHealthcare',
      },
      selection: null,
      metadata: {
        ignore: {
          dimensions: [],
          ids: [],
          all: false,
        },
        panels: [
          {
            name: 'value',
            items: [
              {
                jaql: {
                  table: 'Admissions',
                  column: 'Patient_ID',
                  dim: '[Admissions.Patient_ID]',
                  datatype: 'numeric',
                  merged: true,
                  agg: 'count',
                  title: '# of unique Patient_ID',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: false,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                  color: {
                    type: 'color',
                  },
                },
              },
            ],
          },
          {
            name: 'secondary',
            items: [
              {
                jaql: {
                  type: 'measure',
                  formula: 'GrowthPastYear([# of Patient_ID])',
                  context: {
                    '[# of Patient_ID]': {
                      column: 'Patient_ID',
                      dim: '[Admissions.Patient_ID]',
                      datatype: 'numeric',
                      agg: 'countduplicates',
                      title: '# of Patient_ID',
                    },
                  },
                  title: 'ANNUAL CHANGE',
                },
                format: {
                  mask: {
                    type: 'percent',
                    separated: true,
                    decimals: '1',
                    isdefault: true,
                  },
                },
                originalJaql: {
                  column: 'Patient_ID',
                  dim: '[Admissions.Patient_ID]',
                  datatype: 'numeric',
                  agg: 'countduplicates',
                  title: '# of Patient_ID',
                },
                quickFunction: 'GrowthPastYear',
              },
            ],
          },
          {
            name: 'min',
            items: [],
          },
          {
            name: 'max',
            items: [],
          },
          {
            name: 'filters',
            items: [],
          },
        ],
      },
      dashboardid: '6560d4326f1df500326a06b9',
      options: {
        title: false,
        dashboardFiltersMode: 'filter',
        selector: false,
        allowSelector: false,
        disallowSelector: true,
        triggersDomready: true,
        noTitle: false,
      },
      size: 'big',
      style: {
        'indicator/gauge': {
          subtype: 'round',
          skin: '1',
          components: {
            ticks: {
              inactive: false,
              enabled: true,
            },
            labels: {
              inactive: false,
              enabled: true,
            },
            title: {
              inactive: false,
              enabled: true,
            },
            secondaryTitle: {
              inactive: true,
              enabled: true,
            },
          },
        },
        'indicator/numeric': {
          subtype: 'simple',
          skin: '1',
          components: {
            title: {
              inactive: false,
              enabled: true,
            },
            icon: {
              inactive: false,
              enabled: true,
            },
            secondaryTitle: {
              inactive: true,
              enabled: true,
            },
          },
        },
        skin: '1',
        subtype: 'simple',
        'indicator/pictogram': {},
        components: {
          title: {
            inactive: false,
            enabled: false,
          },
          icon: {
            inactive: true,
            enabled: true,
          },
          secondaryTitle: {
            inactive: false,
            enabled: true,
          },
        },
      },
      _dataSourcePermission: 'owner',
      userAuth: {
        dashboards: {
          create: true,
          delete: true,
          move: true,
          rename: true,
          duplicate: true,
          change_owner: true,
          toggle_edit_mode: true,
          edit_layout: true,
          edit_script: true,
          export_dash: true,
          export_jpeg: true,
          export_image: true,
          export_pdf: true,
          share: true,
          restore: true,
          copy_to_server: true,
          import: true,
          select_palette: true,
          replace_datasource: true,
          undo_import_dash: true,
          toggleDataExploration: true,
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            reorder: true,
            modify_type: true,
            toggle_auto_update: true,
            set_defaults: true,
            advanced: true,
            use_starred: true,
            modify_filter_relationship: true,
          },
        },
        widgets: {
          create: true,
          delete: true,
          rename: true,
          duplicate: true,
          copy_to_dashboard: true,
          edit: true,
          edit_script: true,
          change_type: true,
          export_csv: true,
          export_png: true,
          export_svg: true,
          export_pdf: true,
          modify_selection_attrs: true,
          modify_selection_mode: true,
          drill_to_anywhere: true,
          add_to_pulse: true,
          items: {
            create: true,
            delete: true,
            rename: true,
            modify: true,
            reorder: true,
            modify_type: true,
            modify_format: true,
            on_off: true,
            select_hierarchies: true,
          },
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            modify_layout: true,
            modify_type: true,
            modify_dashboard_filters: true,
            use_starred: true,
          },
          widgetViewOnly: false,
        },
        base: {
          isConsumer: false,
          isContributor: false,
          isAdmin: false,
          isSuper: true,
        },
      },
      _toDisableOptionsList: {
        widgets: {
          duplicate: false,
        },
      },
    },
    {
      _id: '6560d4326f1df500326a06ca',
      title: 'TOTAL ADMISSIONS BY DIVISION',
      type: 'chart/polar',
      subtype: 'column/polar',
      oid: '6560d4326f1df500326a06bb',
      desc: null,
      source: null,
      owner: '64b933f34e4e67001a40353e',
      userId: '64b933f34e4e67001a40353e',
      created: '2023-11-24T16:49:54.753Z',
      lastUpdated: '2023-11-24T16:49:54.753Z',
      instanceType: 'owner',
      datasource: {
        title: 'Sample Healthcare',
        fullname: 'LocalHost/Sample Healthcare',
        id: 'localhost_aSampleIAAaHealthcare',
        address: 'localHost',
        database: 'aSampleIAAaHealthcare',
      },
      selection: null,
      metadata: {
        ignore: {
          dimensions: [],
          ids: [],
          all: false,
        },
        panels: [
          {
            name: 'categories',
            items: [
              {
                jaql: {
                  table: 'Divisions',
                  column: 'Divison_name',
                  dim: '[Divisions.Divison_name]',
                  datatype: 'text',
                  merged: true,
                  title: 'Divison_name',
                },
              },
            ],
          },
          {
            name: 'values',
            items: [
              {
                jaql: {
                  type: 'measure',
                  formula: 'count([D953B-86F])',
                  context: {
                    '[D953B-86F]': {
                      table: 'Admissions',
                      column: 'Patient_ID',
                      dim: '[Admissions.Patient_ID]',
                      datatype: 'numeric',
                      merged: true,
                      title: 'Patient ID',
                    },
                  },
                  title: 'count([Patient ID])',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: true,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                  color: {
                    type: 'color',
                  },
                },
              },
            ],
          },
          {
            name: 'break by',
            items: [],
          },
          {
            name: 'filters',
            items: [],
          },
        ],
      },
      dashboardid: '6560d4326f1df500326a06b9',
      options: {
        dashboardFiltersMode: 'select',
        selector: true,
        previousScrollerLocation: {
          min: null,
          max: null,
        },
        triggersDomready: true,
      },
      style: {
        legend: {
          enabled: false,
          position: 'bottom',
        },
        seriesLabels: {
          enabled: false,
          rotation: 0,
        },
        categories: {
          enabled: true,
          labels: {
            enabled: true,
            rotation: 0,
          },
          gridLines: true,
          title: {
            enabled: false,
          },
          intervalEnabled: false,
        },
        axis: {
          enabled: true,
          labels: {
            enabled: true,
            rotation: 0,
          },
          gridLines: true,
          logarithmic: true,
          intervalEnabled: false,
        },
        dataLimits: {
          seriesCapacity: 50,
          categoriesCapacity: 200,
        },
      },
      _dataSourcePermission: 'owner',
      userAuth: {
        dashboards: {
          create: true,
          delete: true,
          move: true,
          rename: true,
          duplicate: true,
          change_owner: true,
          toggle_edit_mode: true,
          edit_layout: true,
          edit_script: true,
          export_dash: true,
          export_jpeg: true,
          export_image: true,
          export_pdf: true,
          share: true,
          restore: true,
          copy_to_server: true,
          import: true,
          select_palette: true,
          replace_datasource: true,
          undo_import_dash: true,
          toggleDataExploration: true,
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            reorder: true,
            modify_type: true,
            toggle_auto_update: true,
            set_defaults: true,
            advanced: true,
            use_starred: true,
            modify_filter_relationship: true,
          },
        },
        widgets: {
          create: true,
          delete: true,
          rename: true,
          duplicate: true,
          copy_to_dashboard: true,
          edit: true,
          edit_script: true,
          change_type: true,
          export_csv: true,
          export_png: true,
          export_svg: true,
          export_pdf: true,
          modify_selection_attrs: true,
          modify_selection_mode: true,
          drill_to_anywhere: true,
          add_to_pulse: true,
          items: {
            create: true,
            delete: true,
            rename: true,
            modify: true,
            reorder: true,
            modify_type: true,
            modify_format: true,
            on_off: true,
            select_hierarchies: true,
          },
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            modify_layout: true,
            modify_type: true,
            modify_dashboard_filters: true,
            use_starred: true,
          },
          widgetViewOnly: false,
        },
        base: {
          isConsumer: false,
          isContributor: false,
          isAdmin: false,
          isSuper: true,
        },
      },
      _toDisableOptionsList: {
        widgets: {
          duplicate: false,
        },
      },
    },
    {
      _id: '6560d4326f1df500326a06cb',
      title: 'AVERAGE ADMISSION COST',
      type: 'indicator',
      subtype: 'indicator/numeric',
      oid: '6560d4326f1df500326a06bc',
      desc: null,
      source: null,
      owner: '64b933f34e4e67001a40353e',
      userId: '64b933f34e4e67001a40353e',
      created: '2023-11-24T16:49:54.753Z',
      lastUpdated: '2023-11-24T16:49:54.753Z',
      instanceType: 'owner',
      datasource: {
        title: 'Sample Healthcare',
        fullname: 'LocalHost/Sample Healthcare',
        id: 'localhost_aSampleIAAaHealthcare',
        address: 'localHost',
        database: 'aSampleIAAaHealthcare',
      },
      selection: null,
      metadata: {
        ignore: {
          dimensions: [],
          ids: [],
          all: false,
        },
        panels: [
          {
            name: 'value',
            items: [
              {
                jaql: {
                  table: 'Admissions',
                  column: 'Cost_of_admission',
                  dim: '[Admissions.Cost_of_admission]',
                  datatype: 'numeric',
                  agg: 'avg',
                  title: 'Average Cost_of_admission',
                },
                format: {
                  mask: {
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: true,
                    },
                    decimals: '0',
                    currency: {
                      symbol: '$',
                      position: 'pre',
                    },
                  },
                  color: {
                    type: 'color',
                  },
                },
              },
            ],
          },
          {
            name: 'secondary',
            items: [
              {
                jaql: {
                  type: 'measure',
                  formula: 'GrowthPastYear([AVG COST ADMISSION])',
                  context: {
                    '[AVG COST ADMISSION]': {
                      column: 'Cost_of_admission',
                      dim: '[Admissions.Cost_of_admission]',
                      datatype: 'numeric',
                      agg: 'avg',
                      title: 'AVG COST ADMISSION',
                    },
                  },
                  title: 'ANNUAL CHANGE',
                },
                format: {
                  mask: {
                    type: 'percent',
                    separated: true,
                    decimals: '1',
                    isdefault: true,
                  },
                },
                originalJaql: {
                  column: 'Cost_of_admission',
                  dim: '[Admissions.Cost_of_admission]',
                  datatype: 'numeric',
                  agg: 'avg',
                  title: 'AVG COST ADMISSION',
                },
                quickFunction: 'GrowthPastYear',
              },
            ],
          },
          {
            name: 'min',
            items: [],
          },
          {
            name: 'max',
            items: [],
          },
          {
            name: 'filters',
            items: [],
          },
        ],
      },
      dashboardid: '6560d4326f1df500326a06b9',
      options: {
        title: false,
        dashboardFiltersMode: 'filter',
        selector: false,
        allowSelector: false,
        disallowSelector: true,
        triggersDomready: true,
        noTitle: false,
      },
      size: 'big',
      style: {
        'indicator/gauge': {
          subtype: 'round',
          skin: '1',
          components: {
            ticks: {
              inactive: false,
              enabled: true,
            },
            labels: {
              inactive: false,
              enabled: true,
            },
            title: {
              inactive: false,
              enabled: true,
            },
            secondaryTitle: {
              inactive: true,
              enabled: true,
            },
          },
        },
        'indicator/numeric': {
          subtype: 'simple',
          skin: '1',
          components: {
            title: {
              inactive: false,
              enabled: true,
            },
            icon: {
              inactive: false,
              enabled: true,
            },
            secondaryTitle: {
              inactive: true,
              enabled: true,
            },
          },
        },
        skin: '1',
        subtype: 'simple',
        'indicator/pictogram': {},
        components: {
          title: {
            inactive: false,
            enabled: false,
          },
          icon: {
            inactive: true,
            enabled: true,
          },
          secondaryTitle: {
            inactive: false,
            enabled: true,
          },
        },
      },
      _dataSourcePermission: 'owner',
      userAuth: {
        dashboards: {
          create: true,
          delete: true,
          move: true,
          rename: true,
          duplicate: true,
          change_owner: true,
          toggle_edit_mode: true,
          edit_layout: true,
          edit_script: true,
          export_dash: true,
          export_jpeg: true,
          export_image: true,
          export_pdf: true,
          share: true,
          restore: true,
          copy_to_server: true,
          import: true,
          select_palette: true,
          replace_datasource: true,
          undo_import_dash: true,
          toggleDataExploration: true,
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            reorder: true,
            modify_type: true,
            toggle_auto_update: true,
            set_defaults: true,
            advanced: true,
            use_starred: true,
            modify_filter_relationship: true,
          },
        },
        widgets: {
          create: true,
          delete: true,
          rename: true,
          duplicate: true,
          copy_to_dashboard: true,
          edit: true,
          edit_script: true,
          change_type: true,
          export_csv: true,
          export_png: true,
          export_svg: true,
          export_pdf: true,
          modify_selection_attrs: true,
          modify_selection_mode: true,
          drill_to_anywhere: true,
          add_to_pulse: true,
          items: {
            create: true,
            delete: true,
            rename: true,
            modify: true,
            reorder: true,
            modify_type: true,
            modify_format: true,
            on_off: true,
            select_hierarchies: true,
          },
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            modify_layout: true,
            modify_type: true,
            modify_dashboard_filters: true,
            use_starred: true,
          },
          widgetViewOnly: false,
        },
        base: {
          isConsumer: false,
          isContributor: false,
          isAdmin: false,
          isSuper: true,
        },
      },
      _toDisableOptionsList: {
        widgets: {
          duplicate: false,
        },
      },
    },
    {
      _id: '6560d4326f1df500326a06cc',
      title: 'TOTAL COST',
      type: 'indicator',
      subtype: 'indicator/numeric',
      oid: '6560d4326f1df500326a06bd',
      desc: null,
      source: null,
      owner: '64b933f34e4e67001a40353e',
      userId: '64b933f34e4e67001a40353e',
      created: '2023-11-24T16:49:54.753Z',
      lastUpdated: '2023-11-24T16:49:54.753Z',
      instanceType: 'owner',
      datasource: {
        title: 'Sample Healthcare',
        fullname: 'LocalHost/Sample Healthcare',
        id: 'localhost_aSampleIAAaHealthcare',
        address: 'localHost',
        database: 'aSampleIAAaHealthcare',
      },
      selection: null,
      metadata: {
        ignore: {
          dimensions: [],
          ids: [],
          all: false,
        },
        panels: [
          {
            name: 'value',
            items: [
              {
                jaql: {
                  table: 'Admissions',
                  column: 'Cost_of_admission',
                  dim: '[Admissions.Cost_of_admission]',
                  datatype: 'numeric',
                  agg: 'sum',
                  title: 'Total Cost_of_admission',
                },
                format: {
                  mask: {
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: false,
                    },
                    decimals: 1,
                    currency: {
                      symbol: '$',
                      position: 'pre',
                    },
                  },
                  color: {
                    type: 'color',
                  },
                },
              },
            ],
          },
          {
            name: 'secondary',
            items: [
              {
                jaql: {
                  type: 'measure',
                  formula: 'GrowthPastYear([Total Cost_of_admission])',
                  context: {
                    '[Total Cost_of_admission]': {
                      column: 'Cost_of_admission',
                      dim: '[Admissions.Cost_of_admission]',
                      datatype: 'numeric',
                      agg: 'sum',
                      title: 'Total Cost_of_admission',
                    },
                  },
                  title: 'ANNUAL CHANGE',
                },
                format: {
                  mask: {
                    type: 'percent',
                    separated: true,
                    decimals: '1',
                    isdefault: true,
                  },
                },
                originalJaql: {
                  column: 'Cost_of_admission',
                  dim: '[Admissions.Cost_of_admission]',
                  datatype: 'numeric',
                  agg: 'sum',
                  title: 'Total Cost_of_admission',
                },
                quickFunction: 'GrowthPastYear',
              },
            ],
          },
          {
            name: 'min',
            items: [],
          },
          {
            name: 'max',
            items: [],
          },
          {
            name: 'filters',
            items: [],
          },
        ],
      },
      dashboardid: '6560d4326f1df500326a06b9',
      options: {
        title: false,
        dashboardFiltersMode: 'filter',
        selector: false,
        allowSelector: false,
        disallowSelector: true,
        triggersDomready: true,
        noTitle: false,
      },
      size: 'medium',
      style: {
        'indicator/gauge': {
          subtype: 'round',
          skin: '1',
          components: {
            ticks: {
              inactive: false,
              enabled: true,
            },
            labels: {
              inactive: false,
              enabled: true,
            },
            title: {
              inactive: false,
              enabled: true,
            },
            secondaryTitle: {
              inactive: true,
              enabled: true,
            },
          },
        },
        'indicator/numeric': {
          subtype: 'simple',
          skin: '1',
          components: {
            title: {
              inactive: false,
              enabled: true,
            },
            icon: {
              inactive: false,
              enabled: true,
            },
            secondaryTitle: {
              inactive: true,
              enabled: true,
            },
          },
        },
        skin: '1',
        subtype: 'simple',
        'indicator/pictogram': {},
        components: {
          title: {
            inactive: false,
            enabled: false,
          },
          icon: {
            inactive: true,
            enabled: true,
          },
          secondaryTitle: {
            inactive: false,
            enabled: true,
          },
        },
      },
      _dataSourcePermission: 'owner',
      userAuth: {
        dashboards: {
          create: true,
          delete: true,
          move: true,
          rename: true,
          duplicate: true,
          change_owner: true,
          toggle_edit_mode: true,
          edit_layout: true,
          edit_script: true,
          export_dash: true,
          export_jpeg: true,
          export_image: true,
          export_pdf: true,
          share: true,
          restore: true,
          copy_to_server: true,
          import: true,
          select_palette: true,
          replace_datasource: true,
          undo_import_dash: true,
          toggleDataExploration: true,
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            reorder: true,
            modify_type: true,
            toggle_auto_update: true,
            set_defaults: true,
            advanced: true,
            use_starred: true,
            modify_filter_relationship: true,
          },
        },
        widgets: {
          create: true,
          delete: true,
          rename: true,
          duplicate: true,
          copy_to_dashboard: true,
          edit: true,
          edit_script: true,
          change_type: true,
          export_csv: true,
          export_png: true,
          export_svg: true,
          export_pdf: true,
          modify_selection_attrs: true,
          modify_selection_mode: true,
          drill_to_anywhere: true,
          add_to_pulse: true,
          items: {
            create: true,
            delete: true,
            rename: true,
            modify: true,
            reorder: true,
            modify_type: true,
            modify_format: true,
            on_off: true,
            select_hierarchies: true,
          },
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            modify_layout: true,
            modify_type: true,
            modify_dashboard_filters: true,
            use_starred: true,
          },
          widgetViewOnly: false,
        },
        base: {
          isConsumer: false,
          isContributor: false,
          isAdmin: false,
          isSuper: true,
        },
      },
      _toDisableOptionsList: {
        widgets: {
          duplicate: false,
        },
      },
    },
    {
      _id: '6560d4326f1df500326a06cd',
      title: 'AVERAGE DAYS ADMITTED',
      type: 'indicator',
      subtype: 'indicator/numeric',
      oid: '6560d4326f1df500326a06be',
      desc: null,
      source: null,
      owner: '64b933f34e4e67001a40353e',
      userId: '64b933f34e4e67001a40353e',
      created: '2023-11-24T16:49:54.753Z',
      lastUpdated: '2023-11-24T16:49:54.753Z',
      instanceType: 'owner',
      datasource: {
        title: 'Sample Healthcare',
        fullname: 'LocalHost/Sample Healthcare',
        id: 'localhost_aSampleIAAaHealthcare',
        address: 'localHost',
        database: 'aSampleIAAaHealthcare',
      },
      selection: null,
      metadata: {
        ignore: {
          dimensions: [],
          ids: [],
          all: false,
        },
        panels: [
          {
            name: 'value',
            items: [
              {
                jaql: {
                  type: 'measure',
                  formula: 'Avg(DDiff([DC7C1-251],[74C2F-ADD]))',
                  context: {
                    '[74C2F-ADD]': {
                      column: 'Admission_Time',
                      dim: '[Admissions.Admission_Time (Calendar)]',
                      datatype: 'datetime',
                      level: 'days',
                      title: 'Days in Admission  Time',
                    },
                    '[DC7C1-251]': {
                      column: 'Discharge_Time',
                      dim: '[Admissions.Discharge_Time (Calendar)]',
                      datatype: 'datetime',
                      level: 'days',
                      title: 'Days in Discharge  Time',
                    },
                  },
                  title: 'AVG DAYS ADMITTED',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: false,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                  color: {
                    type: 'color',
                  },
                },
              },
            ],
          },
          {
            name: 'secondary',
            items: [
              {
                jaql: {
                  type: 'measure',
                  formula: 'GrowthPastYear([943C8-B94])',
                  context: {
                    '[943C8-B94]': {
                      type: 'measure',
                      formula: 'Avg(DDiff([DC7C1-251],[74C2F-ADD]))',
                      context: {
                        '[74C2F-ADD]': {
                          column: 'Admission_Time',
                          dim: '[Admissions.Admission_Time (Calendar)]',
                          datatype: 'datetime',
                          level: 'days',
                          title: 'Days in Admission  Time',
                        },
                        '[DC7C1-251]': {
                          column: 'Discharge_Time',
                          dim: '[Admissions.Discharge_Time (Calendar)]',
                          datatype: 'datetime',
                          level: 'days',
                          title: 'Days in Discharge  Time',
                        },
                      },
                      title: 'AVERAGE DAYS ADMITTED',
                    },
                  },
                  title: 'ANNUAL CHANGE',
                },
                format: {
                  mask: {
                    type: 'percent',
                    separated: true,
                    decimals: '1',
                    isdefault: true,
                  },
                },
                originalJaql: {
                  type: 'measure',
                  formula: 'Avg(DDiff([Days in Discharge_Time1],[Days in Admission_Time1]))',
                  context: {
                    '[Days in Discharge_Time1]': {
                      column: 'Discharge_Time',
                      dim: '[Admissions.Discharge_Time (Calendar)]',
                      datatype: 'datetime',
                      level: 'days',
                    },
                    '[Days in Admission_Time1]': {
                      column: 'Admission_Time',
                      dim: '[Admissions.Admission_Time (Calendar)]',
                      datatype: 'datetime',
                      level: 'days',
                    },
                  },
                  title: 'Avg(DDiff([Days in Discharge_Time1],[Days in Admission_Time1]))',
                },
                quickFunction: 'GrowthPastYear',
              },
            ],
          },
          {
            name: 'min',
            items: [],
          },
          {
            name: 'max',
            items: [],
          },
          {
            name: 'filters',
            items: [],
          },
        ],
      },
      dashboardid: '6560d4326f1df500326a06b9',
      options: {
        title: false,
        dashboardFiltersMode: 'filter',
        selector: false,
        allowSelector: false,
        disallowSelector: true,
        triggersDomready: true,
        noTitle: false,
      },
      size: 'big',
      style: {
        'indicator/pictogram': {},
        subtype: 'simple',
        'indicator/numeric': {
          subtype: 'simple',
          skin: '1',
          components: {
            title: {
              inactive: false,
              enabled: true,
            },
            icon: {
              inactive: false,
              enabled: true,
            },
            secondaryTitle: {
              inactive: true,
              enabled: true,
            },
          },
        },
        skin: '1',
        'indicator/gauge': {
          subtype: 'round',
          skin: '1',
          components: {
            ticks: {
              inactive: false,
              enabled: true,
            },
            labels: {
              inactive: false,
              enabled: true,
            },
            title: {
              inactive: false,
              enabled: true,
            },
            secondaryTitle: {
              inactive: true,
              enabled: true,
            },
          },
        },
        components: {
          title: {
            inactive: false,
            enabled: false,
          },
          icon: {
            inactive: true,
            enabled: true,
          },
          secondaryTitle: {
            inactive: false,
            enabled: true,
          },
        },
      },
      _dataSourcePermission: 'owner',
      userAuth: {
        dashboards: {
          create: true,
          delete: true,
          move: true,
          rename: true,
          duplicate: true,
          change_owner: true,
          toggle_edit_mode: true,
          edit_layout: true,
          edit_script: true,
          export_dash: true,
          export_jpeg: true,
          export_image: true,
          export_pdf: true,
          share: true,
          restore: true,
          copy_to_server: true,
          import: true,
          select_palette: true,
          replace_datasource: true,
          undo_import_dash: true,
          toggleDataExploration: true,
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            reorder: true,
            modify_type: true,
            toggle_auto_update: true,
            set_defaults: true,
            advanced: true,
            use_starred: true,
            modify_filter_relationship: true,
          },
        },
        widgets: {
          create: true,
          delete: true,
          rename: true,
          duplicate: true,
          copy_to_dashboard: true,
          edit: true,
          edit_script: true,
          change_type: true,
          export_csv: true,
          export_png: true,
          export_svg: true,
          export_pdf: true,
          modify_selection_attrs: true,
          modify_selection_mode: true,
          drill_to_anywhere: true,
          add_to_pulse: true,
          items: {
            create: true,
            delete: true,
            rename: true,
            modify: true,
            reorder: true,
            modify_type: true,
            modify_format: true,
            on_off: true,
            select_hierarchies: true,
          },
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            modify_layout: true,
            modify_type: true,
            modify_dashboard_filters: true,
            use_starred: true,
          },
          widgetViewOnly: false,
        },
        base: {
          isConsumer: false,
          isContributor: false,
          isAdmin: false,
          isSuper: true,
        },
      },
      _toDisableOptionsList: {
        widgets: {
          duplicate: false,
        },
      },
    },
    {
      _id: '6560d4326f1df500326a06ce',
      title: 'TOTAL PATIENT ADMISSIONS & LENGTH OF STAY (DAYS)',
      type: 'chart/line',
      subtype: 'line/spline',
      oid: '6560d4326f1df500326a06bf',
      desc: null,
      source: null,
      owner: '64b933f34e4e67001a40353e',
      userId: '64b933f34e4e67001a40353e',
      created: '2023-11-24T16:49:54.753Z',
      lastUpdated: '2023-11-24T16:49:54.753Z',
      instanceType: 'owner',
      datasource: {
        title: 'Sample Healthcare',
        fullname: 'LocalHost/Sample Healthcare',
        id: 'localhost_aSampleIAAaHealthcare',
        address: 'localHost',
        database: 'aSampleIAAaHealthcare',
      },
      selection: null,
      metadata: {
        drillHistory: [
          {
            jaql: {
              column: 'Admission_Time',
              dim: '[Admissions.Admission_Time (Calendar)]',
              datatype: 'datetime',
              level: 'days',
              title: 'Days in Admission_Time',
            },
            through: {
              jaql: {
                datatype: 'datetime',
                column: 'Admission_Time',
                dim: '[Admissions.Admission_Time (Calendar)]',
                title: 'Months in Admission_Time',
                level: 'months',
                filter: {
                  explicit: true,
                  singleSelect: false,
                  members: ['2013-02-01T00:00:00.000Z'],
                },
              },
            },
            parent: {
              jaql: {
                column: 'Admission_Time',
                dim: '[Admissions.Admission_Time (Calendar)]',
                datatype: 'datetime',
                level: 'months',
                title: 'Months in Admission_Time',
              },
              format: {
                mask: {
                  years: 'yyyy',
                  quarters: 'Q yyyy',
                  months: 'MM yyyy',
                  days: 'shortDate',
                  isdefault: true,
                },
              },
            },
            format: {
              mask: {
                years: 'yyyy',
                quarters: 'Q yyyy',
                months: 'MM yyyy',
                days: 'shortDate',
                isdefault: true,
              },
            },
          },
          {
            jaql: {
              column: 'Gender',
              dim: '[Patients.Gender]',
              datatype: 'text',
              title: 'Gender',
            },
            through: {
              jaql: {
                datatype: 'datetime',
                column: 'Admission_Time',
                dim: '[Admissions.Admission_Time (Calendar)]',
                title: 'Days in Admission_Time',
                level: 'days',
                filter: {
                  explicit: true,
                  singleSelect: false,
                  members: ['2013-02-18T00:00:00.000Z'],
                },
              },
            },
            parent: {
              jaql: {
                column: 'Admission_Time',
                dim: '[Admissions.Admission_Time (Calendar)]',
                datatype: 'datetime',
                level: 'days',
                title: 'Days in Admission_Time',
              },
              through: {
                jaql: {
                  datatype: 'datetime',
                  column: 'Admission_Time',
                  dim: '[Admissions.Admission_Time (Calendar)]',
                  title: 'Months in Admission_Time',
                  level: 'months',
                  filter: {
                    explicit: true,
                    singleSelect: false,
                    members: ['2013-02-01T00:00:00.000Z'],
                  },
                },
              },
              parent: {
                jaql: {
                  column: 'Admission_Time',
                  dim: '[Admissions.Admission_Time (Calendar)]',
                  datatype: 'datetime',
                  level: 'months',
                  title: 'Months in Admission_Time',
                },
                format: {
                  mask: {
                    years: 'yyyy',
                    quarters: 'Q yyyy',
                    months: 'MM yyyy',
                    days: 'shortDate',
                    isdefault: true,
                  },
                },
              },
              format: {
                mask: {
                  years: 'yyyy',
                  quarters: 'Q yyyy',
                  months: 'MM yyyy',
                  days: 'shortDate',
                  isdefault: true,
                },
              },
            },
            format: {
              mask: {
                isdefault: true,
              },
            },
          },
          {
            jaql: {
              column: 'Description',
              dim: '[Diagnosis.Description]',
              datatype: 'text',
              title: 'Description',
            },
            through: {
              jaql: {
                datatype: 'text',
                column: 'Gender',
                dim: '[Patients.Gender]',
                title: 'Gender',
                filter: {
                  explicit: true,
                  singleSelect: false,
                  members: ['Male'],
                },
              },
            },
            parent: {
              jaql: {
                column: 'Gender',
                dim: '[Patients.Gender]',
                datatype: 'text',
                title: 'Gender',
              },
              through: {
                jaql: {
                  datatype: 'datetime',
                  column: 'Admission_Time',
                  dim: '[Admissions.Admission_Time (Calendar)]',
                  title: 'Days in Admission_Time',
                  level: 'days',
                  filter: {
                    explicit: true,
                    singleSelect: false,
                    members: ['2013-02-18T00:00:00.000Z'],
                  },
                },
              },
              parent: {
                jaql: {
                  column: 'Admission_Time',
                  dim: '[Admissions.Admission_Time (Calendar)]',
                  datatype: 'datetime',
                  level: 'days',
                  title: 'Days in Admission_Time',
                },
                through: {
                  jaql: {
                    datatype: 'datetime',
                    column: 'Admission_Time',
                    dim: '[Admissions.Admission_Time (Calendar)]',
                    title: 'Months in Admission_Time',
                    level: 'months',
                    filter: {
                      explicit: true,
                      singleSelect: false,
                      members: ['2013-02-01T00:00:00.000Z'],
                    },
                  },
                },
                parent: {
                  jaql: {
                    column: 'Admission_Time',
                    dim: '[Admissions.Admission_Time (Calendar)]',
                    datatype: 'datetime',
                    level: 'months',
                    title: 'Months in Admission_Time',
                  },
                  format: {
                    mask: {
                      years: 'yyyy',
                      quarters: 'Q yyyy',
                      months: 'MM yyyy',
                      days: 'shortDate',
                      isdefault: true,
                    },
                  },
                },
                format: {
                  mask: {
                    years: 'yyyy',
                    quarters: 'Q yyyy',
                    months: 'MM yyyy',
                    days: 'shortDate',
                    isdefault: true,
                  },
                },
              },
              format: {
                mask: {
                  isdefault: true,
                },
              },
            },
            format: {
              mask: {
                isdefault: true,
              },
            },
          },
        ],
        ignore: {
          dimensions: [],
          ids: [],
          all: false,
        },
        panels: [
          {
            name: 'x-axis',
            items: [
              {
                jaql: {
                  table: 'Admissions',
                  column: 'Admission_Time',
                  dim: '[Admissions.Admission_Time (Calendar)]',
                  datatype: 'datetime',
                  merged: true,
                  level: 'months',
                  title: 'Months in Admission_Time',
                },
                format: {
                  mask: {
                    years: 'yyyy',
                    quarters: 'yyyy Q',
                    months: 'MM/yyyy',
                    days: 'shortDate',
                    isdefault: true,
                  },
                },
              },
            ],
          },
          {
            name: 'values',
            items: [
              {
                jaql: {
                  type: 'measure',
                  formula: 'Avg(DDiff([EF06E-0FD],[36941-55C]))',
                  context: {
                    '[36941-55C]': {
                      column: 'Admission_Time',
                      dim: '[Admissions.Admission_Time (Calendar)]',
                      datatype: 'datetime',
                      level: 'days',
                      title: 'Days in Admission  Time',
                    },
                    '[EF06E-0FD]': {
                      column: 'Discharge_Time',
                      dim: '[Admissions.Discharge_Time (Calendar)]',
                      datatype: 'datetime',
                      level: 'days',
                      title: 'Days in Discharge  Time',
                    },
                  },
                  title: 'Avg Stay in Days',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: true,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                  color: {
                    type: 'color',
                  },
                },
                y2: true,
                singleSeriesType: 'column',
              },
              {
                jaql: {
                  type: 'measure',
                  formula: 'count([8A99E-1C7])',
                  context: {
                    '[8A99E-1C7]': {
                      column: 'Patient_ID',
                      dim: '[Admissions.Patient_ID]',
                      datatype: 'numeric',
                      title: 'Patient ID',
                    },
                  },
                  title: 'Tot. Patient Admissions',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: true,
                      b: true,
                      m: true,
                      k: true,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                  color: {
                    type: 'color',
                  },
                },
              },
            ],
          },
          {
            name: 'break by',
            items: [],
          },
          {
            name: 'filters',
            items: [],
          },
        ],
      },
      dashboardid: '6560d4326f1df500326a06b9',
      options: {
        dashboardFiltersMode: 'select',
        selector: true,
        triggersDomready: true,
      },
      style: {
        lineWidth: {
          width: 'thick',
        },
        legend: {
          enabled: true,
          position: 'top',
        },
        seriesLabels: {
          enabled: false,
          rotation: 0,
        },
        markers: {
          enabled: true,
          fill: 'hollow',
          size: 'small',
        },
        xAxis: {
          enabled: true,
          ticks: true,
          labels: {
            enabled: true,
            rotation: 0,
          },
          gridLines: false,
          title: {
            enabled: false,
          },
          x2Title: {
            enabled: false,
          },
          intervalEnabled: false,
        },
        yAxis: {
          inactive: false,
          enabled: true,
          ticks: true,
          labels: {
            enabled: true,
            rotation: 0,
          },
          gridLines: true,
          logarithmic: false,
          title: {
            enabled: true,
            text: 'Tot. Patients',
          },
          intervalEnabled: true,
        },
        y2Axis: {
          inactive: false,
          enabled: true,
          ticks: true,
          labels: {
            enabled: true,
            rotation: 0,
          },
          gridLines: false,
          logarithmic: false,
          title: {
            enabled: true,
          },
          templateMainYHasGridLines: true,
          intervalEnabled: true,
        },
        navigator: {
          enabled: true,
        },
        dataLimits: {
          seriesCapacity: 50,
          categoriesCapacity: 100000,
        },
      },
      _dataSourcePermission: 'owner',
      userAuth: {
        dashboards: {
          create: true,
          delete: true,
          move: true,
          rename: true,
          duplicate: true,
          change_owner: true,
          toggle_edit_mode: true,
          edit_layout: true,
          edit_script: true,
          export_dash: true,
          export_jpeg: true,
          export_image: true,
          export_pdf: true,
          share: true,
          restore: true,
          copy_to_server: true,
          import: true,
          select_palette: true,
          replace_datasource: true,
          undo_import_dash: true,
          toggleDataExploration: true,
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            reorder: true,
            modify_type: true,
            toggle_auto_update: true,
            set_defaults: true,
            advanced: true,
            use_starred: true,
            modify_filter_relationship: true,
          },
        },
        widgets: {
          create: true,
          delete: true,
          rename: true,
          duplicate: true,
          copy_to_dashboard: true,
          edit: true,
          edit_script: true,
          change_type: true,
          export_csv: true,
          export_png: true,
          export_svg: true,
          export_pdf: true,
          modify_selection_attrs: true,
          modify_selection_mode: true,
          drill_to_anywhere: true,
          add_to_pulse: true,
          items: {
            create: true,
            delete: true,
            rename: true,
            modify: true,
            reorder: true,
            modify_type: true,
            modify_format: true,
            on_off: true,
            select_hierarchies: true,
          },
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            modify_layout: true,
            modify_type: true,
            modify_dashboard_filters: true,
            use_starred: true,
          },
          widgetViewOnly: false,
        },
        base: {
          isConsumer: false,
          isContributor: false,
          isAdmin: false,
          isSuper: true,
        },
      },
      _toDisableOptionsList: {
        widgets: {
          duplicate: false,
        },
      },
    },
    {
      _id: '6560d4326f1df500326a06cf',
      title: 'TOP 10 DIAGNOSIS',
      type: 'tablewidget',
      subtype: 'tablewidget',
      oid: '6560d4326f1df500326a06c0',
      desc: null,
      source: null,
      owner: '64b933f34e4e67001a40353e',
      userId: '64b933f34e4e67001a40353e',
      created: '2023-11-24T16:49:54.753Z',
      lastUpdated: '2023-11-24T17:27:16.432Z',
      instanceType: 'owner',
      datasource: {
        title: 'Sample Healthcare',
        fullname: 'LocalHost/Sample Healthcare',
        id: 'localhost_aSampleIAAaHealthcare',
        address: 'localHost',
        database: 'aSampleIAAaHealthcare',
      },
      selection: null,
      metadata: {
        ignore: {
          dimensions: [],
          ids: [],
          all: false,
        },
        panels: [
          {
            name: 'columns',
            items: [
              {
                jaql: {
                  table: 'Diagnosis',
                  column: 'Description',
                  dim: '[Diagnosis.Description]',
                  datatype: 'text',
                  merged: true,
                  title: 'DIAGNOSIS',
                },
                field: {
                  id: '[Diagnosis.Description]',
                  index: 0,
                },
                instanceid: '677EC-EDEF-44',
                panel: 'rows',
              },
              {
                jaql: {
                  table: 'Admissions',
                  column: 'Patient_ID',
                  dim: '[Admissions.Patient_ID]',
                  datatype: 'numeric',
                  merged: true,
                  agg: 'count',
                  title: '# PATIENTS',
                },
                format: {
                  mask: {
                    type: 'number',
                    abbreviations: {
                      t: false,
                      b: false,
                      m: false,
                      k: false,
                    },
                    separated: true,
                    decimals: 'auto',
                    isdefault: true,
                  },
                  width: 134,
                },
                field: {
                  id: '[Admissions.Patient_ID]_count',
                  index: 1,
                },
                instanceid: 'A7664-0C98-19',
                panel: 'measures',
              },
              {
                jaql: {
                  table: 'Admissions',
                  column: 'Cost_of_admission',
                  dim: '[Admissions.Cost_of_admission]',
                  datatype: 'numeric',
                  agg: 'avg',
                  title: 'AVG COST',
                },
                format: {
                  mask: {
                    abbreviations: {
                      t: false,
                      b: false,
                      m: false,
                      k: false,
                    },
                    decimals: '0',
                    currency: {
                      symbol: '$',
                      position: 'pre',
                    },
                  },
                  width: 182,
                },
                field: {
                  id: '[Admissions.Cost_of_admission]_avg',
                  index: 2,
                },
                instanceid: 'B6D91-757A-71',
                panel: 'measures',
              },
            ],
          },
          {
            name: 'filters',
            items: [
              {
                jaql: {
                  datasource: {
                    title: 'Sample Healthcare',
                    fullname: 'LocalHost/Sample Healthcare',
                    id: 'localhost_aSampleIAAaHealthcare',
                    address: 'localHost',
                    database: 'aSampleIAAaHealthcare',
                  },
                  column: 'Description',
                  dim: '[Diagnosis.Description]',
                  datatype: 'text',
                  title: 'DESCRIPTION',
                  filter: {
                    top: 10,
                    by: {
                      column: 'Patient_ID',
                      dim: '[Admissions.Patient_ID]',
                      datatype: 'numeric',
                      agg: 'count',
                      title: '# PATIENTS',
                    },
                  },
                  collapsed: false,
                },
                format: {
                  mask: {
                    isdefault: true,
                  },
                },
                instanceid: '20C52-FEA7-43',
                panel: 'scope',
              },
            ],
          },
        ],
        usedFormulasMapping: {},
      },
      dashboardid: '6560d4326f1df500326a06b9',
      options: {
        dashboardFiltersMode: 'select',
        disallowSelector: true,
        triggersDomready: true,
        selector: false,
        dataTypes: {
          dimensions: true,
          measures: false,
          filter: false,
        },
        autoUpdateOnEveryChange: true,
        supportsHierarchies: false,
      },
      style: {
        'borders/all': true,
        'borders/grid': false,
        'borders/rows': false,
        'borders/columns': false,
        'width/content': true,
        'width/window': false,
        'colors/headers': true,
        'colors/rows': true,
        'colors/columns': false,
        'wordwrap/headers': true,
        'wordwrap/rows': false,
        scroll: false,
        pageSize: 25,
        tableState: {
          columns: [
            {
              visible: true,
              search: {},
            },
            {
              visible: true,
              search: {},
            },
            {
              visible: true,
              search: {},
            },
          ],
          colResize: {
            columns: ['127.945px', '101.008px', '92.4609px'],
            tableSize: 320,
          },
          headers: [
            {
              title: 'DIAGNOSIS',
              dim: '[Diagnosis.Description]',
              datatype: 'text',
            },
            {
              title: '# PATIENTS',
              dim: '[Admissions.Patient_ID]',
              datatype: 'numeric',
            },
            {
              title: 'AVG COST',
              dim: '[Admissions.Cost_of_admission]',
              datatype: 'numeric',
            },
          ],
          length: 25,
          start: 0,
          iScrollerTopRow: 0,
          iScroller: 0,
          search: {
            search: '',
            smart: true,
            regex: false,
            caseInsensitive: true,
          },
          order: [[0, 'asc']],
          time: 1700846843298,
        },
        automaticHeight: true,
        narration: {
          enabled: false,
          display: 'above',
          format: 'bullets',
          verbosity: 'medium',
          up_sentiment: 'good',
          aggregation: 'sum',
          labels: [
            {
              id: 'diagnosis',
              title: 'DIAGNOSIS',
              singular: 'DIAGNOSIS',
              plural: 'DIAGNOSIS',
            },
            {
              id: 'description',
              title: 'DESCRIPTION',
              singular: 'DESCRIPTION',
              plural: 'DESCRIPTION',
            },
          ],
        },
      },
      currentPage: 0,
      instanceid: '486C0-48FD-72',
      realTimeRefreshing: false,
      tags: [],
      _dataSourcePermission: 'owner',
      userAuth: {
        dashboards: {
          create: true,
          delete: true,
          move: true,
          rename: true,
          duplicate: true,
          change_owner: true,
          toggle_edit_mode: true,
          edit_layout: true,
          edit_script: true,
          export_dash: true,
          export_jpeg: true,
          export_image: true,
          export_pdf: true,
          share: true,
          restore: true,
          copy_to_server: true,
          import: true,
          select_palette: true,
          replace_datasource: true,
          undo_import_dash: true,
          toggleDataExploration: true,
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            reorder: true,
            modify_type: true,
            toggle_auto_update: true,
            set_defaults: true,
            advanced: true,
            use_starred: true,
            modify_filter_relationship: true,
          },
        },
        widgets: {
          create: true,
          delete: true,
          rename: true,
          duplicate: true,
          copy_to_dashboard: true,
          edit: true,
          edit_script: true,
          change_type: true,
          export_csv: true,
          export_png: true,
          export_svg: true,
          export_pdf: true,
          modify_selection_attrs: true,
          modify_selection_mode: true,
          drill_to_anywhere: true,
          add_to_pulse: true,
          items: {
            create: true,
            delete: true,
            rename: true,
            modify: true,
            reorder: true,
            modify_type: true,
            modify_format: true,
            on_off: true,
            select_hierarchies: true,
          },
          filters: {
            create: true,
            delete: true,
            save: true,
            on_off: true,
            toggle_expansion: true,
            modify: true,
            modify_layout: true,
            modify_type: true,
            modify_dashboard_filters: true,
            use_starred: true,
          },
          widgetViewOnly: false,
        },
        base: {
          isConsumer: false,
          isContributor: false,
          isAdmin: false,
          isSuper: true,
        },
      },
      _toDisableOptionsList: {
        widgets: {
          duplicate: false,
        },
      },
    },
  ],
  _dataSourcePermission: 'owner',
  userAuth: {
    dashboards: {
      create: true,
      delete: true,
      move: true,
      rename: true,
      duplicate: true,
      change_owner: true,
      toggle_edit_mode: true,
      edit_layout: true,
      edit_script: true,
      export_dash: true,
      export_jpeg: true,
      export_image: true,
      export_pdf: true,
      share: true,
      restore: true,
      copy_to_server: true,
      import: true,
      select_palette: true,
      replace_datasource: true,
      undo_import_dash: true,
      toggleDataExploration: true,
      filters: {
        create: true,
        delete: true,
        save: true,
        on_off: true,
        toggle_expansion: true,
        modify: true,
        reorder: true,
        modify_type: true,
        toggle_auto_update: true,
        set_defaults: true,
        advanced: true,
        use_starred: true,
        modify_filter_relationship: true,
      },
    },
    widgets: {
      create: true,
      delete: true,
      rename: true,
      duplicate: true,
      copy_to_dashboard: true,
      edit: true,
      edit_script: true,
      change_type: true,
      export_csv: true,
      export_png: true,
      export_svg: true,
      export_pdf: true,
      modify_selection_attrs: true,
      modify_selection_mode: true,
      drill_to_anywhere: true,
      add_to_pulse: true,
      items: {
        create: true,
        delete: true,
        rename: true,
        modify: true,
        reorder: true,
        modify_type: true,
        modify_format: true,
        on_off: true,
        select_hierarchies: true,
      },
      filters: {
        create: true,
        delete: true,
        save: true,
        on_off: true,
        toggle_expansion: true,
        modify: true,
        modify_layout: true,
        modify_type: true,
        modify_dashboard_filters: true,
        use_starred: true,
      },
      widgetViewOnly: false,
    },
    base: {
      isConsumer: false,
      isContributor: false,
      isAdmin: false,
      isSuper: true,
    },
  },
  _toDisableOptionsList: {
    dashboards: {
      duplicate: false,
      export_dash: false,
    },
  },
} as DashboardDto;
