/* eslint-disable security/detect-object-injection */
export const messages = {
  xAxis: 'X-Axis',
  value: 'Value',
  values: 'Values',
  categories: 'Categories',
  secondary: 'Secondary',
  columns: 'Columns',
  classic: 'Classic',
  stacked: 'Stacked',
  stack100: 'Stack100',
  min: 'Min',
  max: 'Max',
  position: 'Position',
  breakBy: 'Break by',
  addField: 'Add a field',
  defaultLowercase: 'default',
  default: 'Default',
  colors: 'Colors',
  insertCustomColor: 'Insert Custom Color',
  recentColors: 'Recent Colors',
  colorPalette: 'Color Palette',
  addMoreData: 'Add More Data...',
  selectData: 'Select Data',
  searchForColumns: 'Type to search for columns',
  noResultsFound: 'No results found.',
  columnsToSelectFrom: 'Columns to select from:',
  reset: 'reset',
  add: 'Add',
  abbreviations: 'Abbreviations',
  decimals: 'Decimals',
  decimalPlaces: 'Decimal Places',
  automatic: 'Automatic',
  thousandsSeparator: 'Thousands Separator',
  symbol: 'Symbol',
  numbers: 'Numbers',
  numeric: 'Numeric',
  currency: 'Currency',
  percent: 'Percent',
  gauge: 'Gauge',
  placeholderTextFormatNumber: 'Placeholder Text > Format Number',
  yAxis: 'Y-Axis',
  y2Axis: 'Y2-Axis',
  gridLines: 'Grid Lines',
  logarithmic: 'Logarithmic',
  headers: 'Headers',
  labels: 'Labels',
  title: 'Title',
  auto: 'Auto',
  interval: 'Interval',
  x2Title: 'X2 Title',
  ticks: 'Ticks',
  skin: 'Skin',
  components: 'Components',
  indicatorType: 'Indicator Type',
  lineType: 'Line Type',
  straight: 'Straight',
  smooth: 'Smooth',
  simple: 'Simple',
  indicatorSubtype: 'Indicator Sub-Type',
  bar: 'Bar',
  pieType: 'Pie Type',
  alternatingRows: 'Alternating Rows',
  alternatingColumns: 'Alternating Columns',
};

export const useIntl = () => {
  return { formatMessage: (message: string) => message || 'unknown message' };
};
