import { ProjectReflection } from 'typedoc';
import { generateDiffs } from './generate-diffs';

/**
 * Generates the report header.
 * @returns The report header.
 */
function generateReportHeader(): string {
  const date = new Date().toISOString().split('T')[0];
  return `# Feature Parity Report across Packages\n\nGenerated by TypeDoc and \`@ethings-os/typdoc-plugin-diff-packages\`\n\nDate: ${date}\n\n\n`;
}

/**
 *
 * @param project
 * @returns
 */
export function generateReport(project: ProjectReflection): string {
  const output = `${generateReportHeader()}${generateDiffs(project)}`;

  return output;
}
