// @ts-check
/**
 * Report writers for the tag-usage-report plugin.
 *
 * Converts a filtered list of TaggedDecl objects into two output files:
 *   TAG_USAGE_REPORT.md        — collapsible markdown, grouped by tag → package → subgroup
 *   TAG_USAGE_REPORT_SIMPLE.txt — plain bullet list, grouped by tag → package, no formatting
 *
 * Main exports: writeReport(exportedDecls, outputPath, logger)
 *               writeSimpleReport(exportedDecls, outputPath, logger)
 */

'use strict';

const fs = require('fs');
const path = require('path');
const {
  REPO_ROOT, REPORT_DIR,
  TAGS_TO_REPORT, TAG_DESCRIPTIONS, TAG_ANCHOR,
} = require('./config.cjs');

// ── Path helpers ──────────────────────────────────────────────────────────────

/**
 * Extract the short package name (e.g. "sdk-ui") from an absolute file path.
 *
 * @param {string} absPath
 * @returns {string}
 */
function packageFromPath(absPath) {
  const rel = path.relative(REPO_ROOT, absPath).replace(/\\/g, '/');
  const m = rel.match(/^packages\/([^/]+)\//);
  return m ? m[1] : rel;
}

/**
 * Return the full directory path between src/ and the file, e.g.
 * "domains/dashboarding" for a file in packages/sdk-ui/src/domains/dashboarding/.
 * Files directly in src/ return an empty string (shown under the package heading
 * without an extra subgroup block).
 *
 * @param {string} absPath
 * @param {string} pkg  e.g. "sdk-ui"
 * @returns {string}
 */
function subgroupFromPath(absPath, pkg) {
  const rel = path.relative(REPO_ROOT, absPath).replace(/\\/g, '/');
  const prefix = `packages/${pkg}/src/`;
  if (!rel.startsWith(prefix)) return '';
  const after = rel.slice(prefix.length); // "domains/dashboarding/types.ts"
  const lastSlash = after.lastIndexOf('/');
  return lastSlash === -1 ? '' : after.slice(0, lastSlash);
}

/**
 * Build a markdown link for a source location.
 *
 * The href is relative from the repo root (for correct GitLab/GitHub navigation).
 * The display text strips the prefix already conveyed by the section headings
 * so only the filename remains visible.
 *
 * @param {string} absPath
 * @param {string} pkg      e.g. "sdk-ui"
 * @param {string} subgroup e.g. "domains/dashboarding"
 * @returns {{ text: string, href: string }}
 */
function makeLink(absPath, pkg, subgroup) {
  const relFromReportDir = path.relative(REPORT_DIR, absPath).replace(/\\/g, '/');
  const relFromRoot      = path.relative(REPO_ROOT,  absPath).replace(/\\/g, '/');
  const trimPrefix = subgroup
    ? `packages/${pkg}/src/${subgroup}/`
    : `packages/${pkg}/src/`;
  const displayPath = relFromRoot.startsWith(trimPrefix)
    ? relFromRoot.slice(trimPrefix.length)
    : relFromRoot;
  return { text: displayPath, href: relFromReportDir };
}

// ── Markdown helpers ──────────────────────────────────────────────────────────

/** @param {number} n */
const plural = (n) => `${n} item${n === 1 ? '' : 's'}`;

/**
 * Render a single collapsible <details> block containing a list of items.
 *
 * @param {string} summaryLabel  Text inside the <summary> element.
 * @param {Array<{kind:string, name:string, link:{text:string,href:string}|null}>} items
 * @returns {string[]}  Lines to append to the output.
 */
function detailsBlock(summaryLabel, items) {
  const lines = [];
  lines.push('<details>');
  lines.push(`<summary><strong>${summaryLabel}</strong> — ${plural(items.length)}</summary>`);
  lines.push('');
  for (const item of items) {
    const linkMd = item.link ? ` — [${item.link.text}](${item.link.href})` : '';
    lines.push(`- \`${item.kind}\` **${item.name}**${linkMd}`);
  }
  lines.push('');
  lines.push('</details>');
  lines.push('');
  return lines;
}

// ── Report generation ─────────────────────────────────────────────────────────

/**
 * @typedef {{ tag: string, name: string, kind: string, file: string, line: number }} TaggedDecl
 */

/**
 * Build and write TAG_USAGE_REPORT.md from the given exported declarations.
 *
 * @param {TaggedDecl[]} exportedDecls
 * @param {string} outputPath  Absolute path to write the report to.
 * @param {{ info: (msg: string) => void, error: (msg: string) => void }} logger
 */
function writeReport(exportedDecls, outputPath, logger) {
  const lines = buildReportLines(exportedDecls);

  try {
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, lines.join('\n'), 'utf-8');
    logger.info(`[tag-usage-report] Written to ${outputPath}`);
  } catch (/** @type {any} */ err) {
    logger.error(`[tag-usage-report] Failed to write report: ${err.message}`);
  }
}

/**
 * Build the full list of markdown lines for the report.
 *
 * @param {TaggedDecl[]} exportedDecls
 * @returns {string[]}
 */
function buildReportLines(exportedDecls) {
  const lines = [
    '# API Tag Usage Report',
    '',
    '> This file is auto-generated by `yarn docs:gen:md`. Do not edit by hand.',
    '',
    'All declarations carrying one of the four visibility / maturity modifier',
    'tags are listed below, grouped by tag and then by package.',
    '',
    '| Tag | Meaning |',
    '|-----|---------|',
    ...TAGS_TO_REPORT.map(
      (t) => `| [\`${t}\`](#${TAG_ANCHOR[t]}) | ${TAG_DESCRIPTIONS[t]} |`,
    ),
    '',
  ];

  for (const tag of TAGS_TO_REPORT) {
    lines.push(...buildTagSection(tag, exportedDecls.filter((d) => d.tag === tag)));
  }

  return lines;
}

/**
 * Build the lines for a single tag section (## @internal, @sisenseInternal, @alpha, @beta).
 *
 * @param {string} tag
 * @param {TaggedDecl[]} tagDecls
 * @returns {string[]}
 */
function buildTagSection(tag, tagDecls) {
  const lines = [];
  lines.push(`<a id="${TAG_ANCHOR[tag]}"></a>`, '');
  lines.push(`## \`${tag}\` (${tagDecls.length})`, '');
  lines.push(`_${TAG_DESCRIPTIONS[tag]}_`, '');

  if (tagDecls.length === 0) {
    lines.push('None.', '');
    return lines;
  }

  // Group: package → subgroup → items
  /** @type {Map<string, Map<string, Array<{name:string, kind:string, link:{text:string,href:string}|null}>>>} */
  const byPackage = new Map();
  for (const decl of tagDecls) {
    const pkg      = packageFromPath(decl.file);
    const subgroup = subgroupFromPath(decl.file, pkg);
    const link     = makeLink(decl.file, pkg, subgroup);

    if (!byPackage.has(pkg)) byPackage.set(pkg, new Map());
    const bySub = byPackage.get(pkg);
    if (!bySub.has(subgroup)) bySub.set(subgroup, []);
    bySub.get(subgroup).push({ name: decl.name, kind: decl.kind, link });
  }

  for (const pkg of [...byPackage.keys()].sort()) {
    lines.push(...buildPackageSection(pkg, byPackage.get(pkg)));
  }

  return lines;
}

/**
 * Build the lines for a single package within a tag section.
 *
 * Layout:
 *   ### pkg (N)                         ← always-visible heading + total count
 *   <details>pkg — M items</details>    ← root-level items only (if any)
 *   <details>pkg/sub — K items</details> ← one per subgroup, siblings not nested
 *
 * @param {string} pkg
 * @param {Map<string, Array<{name:string, kind:string, link:{text:string,href:string}|null}>} bySubgroup
 * @returns {string[]}
 */
function buildPackageSection(pkg, bySubgroup) {
  const lines = [];

  const sortedSubgroups = [...bySubgroup.keys()].sort((a, b) =>
    a === '' ? -1 : b === '' ? 1 : a.localeCompare(b),
  );

  const totalCount = sortedSubgroups.reduce((n, sg) => n + bySubgroup.get(sg).length, 0);

  // Package heading (outside any <details> so it's always visible and provides
  // a navigable anchor; total count at a glance).
  lines.push(`### ${pkg} (${totalCount})`, '');

  // Root-level items (files directly in src/) in their own block.
  const rootItems = sortByKindAndName(bySubgroup.get('') || []);
  if (rootItems.length > 0) {
    lines.push(...detailsBlock(pkg, rootItems));
  }

  // Subgroup blocks — siblings at the same visual level, all visible by default.
  for (const subgroup of sortedSubgroups.filter((sg) => sg !== '')) {
    const items = sortByKindAndName(bySubgroup.get(subgroup));
    lines.push(...detailsBlock(`${pkg}/${subgroup}`, items));
  }

  return lines;
}

/**
 * Sort items by kind first, then by name, both alphabetically.
 *
 * @template {{ kind: string, name: string }} T
 * @param {T[]} items
 * @returns {T[]}
 */
function sortByKindAndName(items) {
  return [...items].sort((a, b) =>
    a.kind.localeCompare(b.kind) || a.name.localeCompare(b.name),
  );
}

// ── Simple plain-text report ──────────────────────────────────────────────────

/**
 * Return the file path relative to packages/<pkg>/src/, e.g.
 * "dimensional-model/attributes.ts" for a file in packages/sdk-data/src/dimensional-model/.
 * Falls back to the repo-relative path if the prefix isn't matched.
 *
 * @param {string} absPath
 * @param {string} pkg  e.g. "sdk-data"
 * @returns {string}
 */
function simpleFilePath(absPath, pkg) {
  const rel = path.relative(REPO_ROOT, absPath).replace(/\\/g, '/');
  const prefix = `packages/${pkg}/src/`;
  return rel.startsWith(prefix) ? rel.slice(prefix.length) : rel;
}

/**
 * Build the lines for TAG_USAGE_REPORT_SIMPLE.txt.
 *
 * Format:
 *   @tag (N items)
 *
 *     sdk-ui (M items)
 *       - Kind: name - filepath.ts
 *       ...
 *
 * @param {TaggedDecl[]} exportedDecls
 * @returns {string[]}
 */
function buildSimpleReportLines(exportedDecls) {
  const lines = [];

  for (const tag of TAGS_TO_REPORT) {
    const tagDecls = exportedDecls.filter((d) => d.tag === tag);
    lines.push(`${tag} (${tagDecls.length} items)`, '');

    if (tagDecls.length === 0) {
      lines.push('  (none)', '');
      continue;
    }

    // Group by package only — filepath conveys subgroup location.
    /** @type {Map<string, TaggedDecl[]>} */
    const byPackage = new Map();
    for (const decl of tagDecls) {
      const pkg = packageFromPath(decl.file);
      if (!byPackage.has(pkg)) byPackage.set(pkg, []);
      byPackage.get(pkg).push(decl);
    }

    for (const pkg of [...byPackage.keys()].sort()) {
      const pkgDecls = sortByKindAndName(byPackage.get(pkg));
      lines.push(`  ${pkg} (${pkgDecls.length} items)`);
      for (const decl of pkgDecls) {
        lines.push(`    - ${decl.kind}: ${decl.name} - ${simpleFilePath(decl.file, pkg)}`);
      }
      lines.push('');
    }
  }

  return lines;
}

/**
 * Build and write TAG_USAGE_REPORT_SIMPLE.txt from the given exported declarations.
 *
 * @param {TaggedDecl[]} exportedDecls
 * @param {string} outputPath  Absolute path to write the report to.
 * @param {{ info: (msg: string) => void, error: (msg: string) => void }} logger
 */
function writeSimpleReport(exportedDecls, outputPath, logger) {
  const lines = buildSimpleReportLines(exportedDecls);

  try {
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, lines.join('\n'), 'utf-8');
    logger.info(`[tag-usage-report] Simple report written to ${outputPath}`);
  } catch (/** @type {any} */ err) {
    logger.error(`[tag-usage-report] Failed to write simple report: ${err.message}`);
  }
}

module.exports = { writeReport, writeSimpleReport };
