import { measures } from '@sisense/sdk-data';

import {
  Commerce,
  Brand,
  Country,
  Category,
  DataSource,
} from './sample-ecommerce-autogenerated';

export { Commerce, Brand, Category, Country, DataSource };

/** adding predefined set of measures */
export const Measures = {
  SumCost: measures.sum(Commerce.Cost).format('0,0$'),
  AvgCost: measures.average(Commerce.Cost).format('0,0$'),
  SumRevenue: measures.sum(Commerce.Revenue, 'Total Revenue').format('0,0$'),
  Quantity: measures.sum(Commerce.Quantity, 'Total Quantity').format('0,0'),
  CountBrands: measures.countDistinct(Commerce.BrandID).format('0,0'),
};
