import { mockUrl, mockToken, fetchMocks } from '../../../../__mocks__/fetch-mocks';

import { fireEvent, render, screen } from '@testing-library/react';
import { DateRangeFilterTile } from './date-range-filter-tile';
import * as DM from '../../../../__mocks__/data/sample-ecommerce-autogenerated';
import { filters } from '@sisense/sdk-data';
import { SisenseContextProvider } from '../../../../sisense-context/sisense-context-provider';

describe('DateRangeFilterTile', () => {
  beforeEach(() => {
    fetchMock.resetMocks();
  });

  it('should render DateRangeFilterTile', async () => {
    expect.assertions(2);

    // Rendering a DateRangeFilterTile requires 3 fetches
    fetchMock.mockResponses(fetchMocks.globals, fetchMocks.palettes, fetchMocks.jaqlDates);

    const dateRangeFilter = filters.dateRange(DM.Commerce.Date.Years);

    const { container } = render(
      <SisenseContextProvider url={mockUrl} token={mockToken} enableTracking={false}>
        <DateRangeFilterTile
          title="Date Range"
          dataSource={DM.DataSource}
          attribute={DM.Commerce.Date.Years}
          filter={dateRangeFilter}
          onChange={() => {}}
        />
      </SisenseContextProvider>,
    );

    expect(await screen.findByText('2009-01-01')).toBeInTheDocument();

    const dateButton = container.querySelector('.h-button') || container;
    fireEvent.click(dateButton);
    expect(dateButton).toMatchSnapshot();
  });
});
