/* eslint-disable max-lines-per-function */
import { MembersFilter, measures } from '@sisense/sdk-data';
import { CARTESIAN_CHART_TYPES } from '../../../chart-options-processor/translations/types';
import { ChartWidget } from '../../../widgets/chart-widget';
import { useCallback, useEffect, useState } from 'react';
import * as DM from '../../sample-ecommerce-autogenerated';
import { ChartType, DataPoint } from '../../../types';
import { Button, ButtonGroup } from '@mui/material';

export const CartesianSelectableChart = ({
  onPointsSelect,
  filters,
}: {
  onPointsSelect: (filters: MembersFilter[]) => void;
  filters: MembersFilter[];
}) => {
  const [cartesianChartType, setCartesianChartType] = useState('line');

  const [selectedDataPoints, setSelectedDataPoints] = useState<DataPoint[]>([]);

  const getSelectionFilters = useCallback(() => {
    return selectedDataPoints.length
      ? new MembersFilter(
          DM.Commerce.AgeRange,
          selectedDataPoints.map(({ categoryValue }) => categoryValue),
        )
      : undefined;
  }, [selectedDataPoints]);

  useEffect(() => {
    const filter = getSelectionFilters();
    if (filter) onPointsSelect([filter]);
  }, [selectedDataPoints, getSelectionFilters, onPointsSelect]);

  return (
    <>
      <div className="csdk-m-2">
        <h3>Cartesian Selectable Chart</h3>
        <ChartWidget
          styleOptions={{
            height: 400,
            width: 600,
          }}
          chartType={cartesianChartType as ChartType}
          filters={filters}
          topSlot={
            <div className="csdk-flex csdk-justify-center">
              <ButtonGroup variant="outlined" size="small" fullWidth color="info">
                {CARTESIAN_CHART_TYPES.map((chartType) => {
                  return (
                    <Button
                      key={chartType}
                      size={'small'}
                      onClick={() => setCartesianChartType(chartType)}
                    >
                      {chartType}
                    </Button>
                  );
                })}
              </ButtonGroup>
            </div>
          }
          highlightSelectionDisabled={true}
          dataOptions={{
            category: [DM.Commerce.AgeRange],
            value: [measures.sum(DM.Commerce.Revenue)],
          }}
          widgetStyleOptions={{
            border: true,
            borderColor: 'lightgrey',
            cornerRadius: 'Medium',
          }}
          onDataPointsSelected={setSelectedDataPoints}
          onDataPointClick={(dataPoint: DataPoint) => {
            setSelectedDataPoints([dataPoint]);
          }}
        />
      </div>
    </>
  );
};
