/* eslint-disable max-lines-per-function */
import { CartesianSelectableChart } from './cartesian-selectable-chart.js';
import { Filter, MembersFilter, filters, measures } from '@sisense/sdk-data';
import { ScatterSelectableChart } from './scatter-slectable-chart.js';
import { useCallback, useState } from 'react';
import { MemberFilterTile } from '../../../filters/index.js';
import { Button } from '@mui/material';
import * as DM from '../../sample-ecommerce-autogenerated.js';
import { Table } from '../../../table/index.js';

const limitCountries = filters.members(DM.Country.Country, [
  'Albania',
  'APO/FPO',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Republic',
]);

export const SelectionFilterDemo = () => {
  const defaultGenderFilter = new MembersFilter(DM.Commerce.Gender);
  const defaultAgeRangeFilter = new MembersFilter(DM.Commerce.AgeRange);
  const defaultDependentFilter = new MembersFilter(DM.Country.Country);

  const [genderFilter, setGenderFilter] = useState<MembersFilter>(defaultGenderFilter);
  const [ageRangeFilter, setAgeRangeFilter] = useState<MembersFilter>(defaultAgeRangeFilter);
  const [dependentFilter, setDependentFilter] = useState<MembersFilter>(defaultDependentFilter);

  const updateFilter = useCallback(
    (filter: Filter | null) => {
      if (!filter) return;
      if (filter.attribute === DM.Commerce.Gender) setGenderFilter(filter as MembersFilter);
      if (filter.attribute === DM.Commerce.AgeRange) setAgeRangeFilter(filter as MembersFilter);
    },
    [setGenderFilter, setAgeRangeFilter],
  );

  return (
    <>
      {`Filter Members: ${dependentFilter.members}`}
      <div className="csdk-flex csdk-flex-row">
        <div className="csdk-flex csdk-flex-row csdk-flex-grow">
          <ScatterSelectableChart
            filters={[ageRangeFilter, genderFilter, dependentFilter]}
            onPointsSelect={useCallback(
              (filters) => {
                filters.forEach((filter) => {
                  if (filter.attribute === DM.Commerce.Gender) setGenderFilter(filter);
                  if (filter.attribute === DM.Commerce.AgeRange) setAgeRangeFilter(filter);
                });
              },
              [setGenderFilter, setAgeRangeFilter],
            )}
          />
          <CartesianSelectableChart
            filters={[ageRangeFilter, genderFilter, dependentFilter]}
            onPointsSelect={useCallback(
              (filters) => {
                setAgeRangeFilter(filters[0]);
              },
              [setAgeRangeFilter],
            )}
          />
        </div>
        <div className="csdk-m-2">
          <h3>Shared filters</h3>
          <div className="csdk-flex csdk-justify-center csdk-mb-2">
            <Button
              variant={'outlined'}
              size={'small'}
              fullWidth
              onClick={() => {
                setAgeRangeFilter(defaultAgeRangeFilter);
                setGenderFilter(defaultGenderFilter);
              }}
            >
              Clear selections
            </Button>
          </div>
          {ageRangeFilter && (
            <MemberFilterTile
              title={ageRangeFilter.attribute.name}
              attribute={ageRangeFilter.attribute}
              filter={ageRangeFilter}
              onChange={updateFilter}
            />
          )}
          {genderFilter && (
            <>
              <MemberFilterTile
                title={genderFilter.attribute.name}
                attribute={genderFilter.attribute}
                filter={genderFilter}
                onChange={updateFilter}
              />
              <MemberFilterTile
                attribute={DM.Country.Country}
                title={'Country (dependent on Gender)'}
                filter={dependentFilter}
                parentFilters={[limitCountries, ageRangeFilter, genderFilter]}
                onChange={(filter) => setDependentFilter(filter as MembersFilter)}
              />
            </>
          )}
        </div>
      </div>
      <Table
        dataSet={DM.DataSource}
        dataOptions={{
          columns: [DM.Country.Country, measures.sum(DM.Commerce.Revenue, 'Total Revenue')],
        }}
        filters={[limitCountries, genderFilter, ageRangeFilter]}
      />
    </>
  );
};
