/* eslint-disable max-lines-per-function */
import { CartesianSelectableChart } from './cartesian-selectable-chart.js';
import { Filter, MembersFilter } from '@sisense/sdk-data';
import { ScatterSelectableChart } from './scatter-slectable-chart.js';
import { useCallback, useState } from 'react';
import { MemberFilterTile } from '../../../filters/index.js';
import { Button } from '@mui/material';
import * as DM from '../../sample-ecommerce-autogenerated.js';

export const SelectionFilterDemo = () => {
  const defaultGenderFilter = new MembersFilter(DM.Commerce.Gender);
  const defaultAgeRangeFilter = new MembersFilter(DM.Commerce.AgeRange);

  const [genderFilter, setGenderFilter] = useState<MembersFilter>(defaultGenderFilter);
  const [ageRangeFilter, setAgeRangeFilter] = useState<MembersFilter>(defaultAgeRangeFilter);

  const updateFilter = useCallback(
    (filter: Filter | null) => {
      if (!filter) return;
      if (filter.attribute === DM.Commerce.Gender) setGenderFilter(filter as MembersFilter);
      if (filter.attribute === DM.Commerce.AgeRange) setAgeRangeFilter(filter as MembersFilter);
    },
    [setGenderFilter, setAgeRangeFilter],
  );

  return (
    <>
      <div className="csdk-flex csdk-flex-row">
        <div className="csdk-flex csdk-flex-row csdk-flex-grow">
          <ScatterSelectableChart
            filters={[ageRangeFilter, genderFilter]}
            onPointsSelect={useCallback(
              (filters) => {
                filters.forEach((filter) => {
                  if (filter.attribute === DM.Commerce.Gender) setGenderFilter(filter);
                  if (filter.attribute === DM.Commerce.AgeRange) setAgeRangeFilter(filter);
                });
              },
              [setGenderFilter, setAgeRangeFilter],
            )}
          />
          <CartesianSelectableChart
            filters={[ageRangeFilter, genderFilter]}
            onPointsSelect={useCallback(
              (filters) => {
                setAgeRangeFilter(filters[0]);
              },
              [setAgeRangeFilter],
            )}
          />
        </div>
        <div className="csdk-m-2">
          <h3>Shared filters</h3>
          <div className="csdk-flex csdk-justify-center csdk-mb-2">
            <Button
              variant={'outlined'}
              size={'small'}
              fullWidth
              onClick={() => {
                setAgeRangeFilter(defaultAgeRangeFilter);
                setGenderFilter(defaultGenderFilter);
              }}
            >
              Clear selections
            </Button>
          </div>
          {ageRangeFilter && (
            <MemberFilterTile
              key={ageRangeFilter.id}
              title={ageRangeFilter.attribute.name}
              attribute={ageRangeFilter.attribute}
              filter={ageRangeFilter}
              onChange={updateFilter}
            />
          )}
          {genderFilter && (
            <MemberFilterTile
              key={genderFilter.id}
              title={genderFilter.attribute.name}
              attribute={genderFilter.attribute}
              filter={genderFilter}
              onChange={updateFilter}
            />
          )}
        </div>
      </div>
    </>
  );
};
