import { convertDataSource, Filter, FilterRelations } from '@sisense/sdk-data';

import { ChartProps } from '@/props.js';
import type { ChartStyleOptions } from '@/types.js';

import type { NlqTranslationError } from '../../types.js';
import { NlqTranslationResult } from '../../types.js';
import {
  translateFiltersFromJSON,
  translateHighlightsFromJSON,
} from '../constructs/filters/translate-filters-from-json.js';
import { createSchemaIndex } from '../shared/utils/schema-index.js';
import { collectTranslationErrors } from '../shared/utils/translation-helpers.js';
import type { ChartInput } from '../types.js';
import {
  isValidChartType,
  translateDataOptionsFromJSON,
  validateChartJSONStructure,
} from './helpers/index.js';

/** Maps NLQ styleOptions.subtype to BoxWhiskerType for boxplot charts */
function getBoxTypeFromSubtype(subtype: unknown): 'iqr' | 'extremums' | 'standardDeviation' {
  if (typeof subtype !== 'string') return 'iqr';
  const suffix = subtype.split('/')[1];
  if (suffix === 'iqr' || suffix === 'extremums' || suffix === 'standardDeviation') {
    return suffix;
  }
  return 'iqr';
}

/**
 * Translates NLQ ChartJSON format to CSDK chart props.
 * Direction: JSON → CSDK
 *
 * Translates chart JSON generated by the NLQ API to CSDK ChartProps object.
 *
 * @example
 * Input:
 * {
 *   chartType: 'column',
 *   dataOptions: {
 *     category: ['DM.Commerce.Date.Years'],
 *     value: [
 *       { function: 'measureFactory.sum', args: ['DM.Commerce.Revenue', 'Total Revenue'] }
 *     ],
 *     breakBy: [{ column: 'DM.Commerce.Gender', sortType: 'sortAsc' }]
 *   },
 *   filters: [
 *     { function: 'filterFactory.members', args: ['DM.Commerce.Date.Years', ['2024-01-01T00:00:00']] }
 *   ]
 * }
 *
 * Output:
 * {
 *   chartType: 'column',
 *   dataSet: { ... },
 *   dataOptions: {
 *     category: [Attribute(...), ...],
 *     value: [Measure(...), ...],
 *     breakBy: [Attribute(...), ...]
 *   },
 *   filters: [Filter(...), ...]
 * }
 *
 * @param input - ChartInput object containing chartJSON and data schema context
 * @returns NlqTranslationResult with ChartProps or errors
 * @internal
 */
export const translateChartFromJSON = (input: ChartInput): NlqTranslationResult<ChartProps> => {
  const { data: chartJSON, context } = input;
  const { dataSource, tables } = context;

  // Phase 1: Validate top-level structure (typos in prop names, invalid chartType value)
  const { normalized, errors: structureErrors } = validateChartJSONStructure(chartJSON);
  if (structureErrors.length > 0) {
    return { success: false, errors: structureErrors };
  }

  const chartType = normalized.chartType;

  // Create schema index once from tables for efficient lookups
  const schemaIndex = createSchemaIndex(tables);

  const translationErrors: NlqTranslationError[] = [];

  // Translate dataOptions using axis-specific translators (collects errors, never throws)
  let dataOptions = translateDataOptionsFromJSON(
    normalized.dataOptions,
    { dataSource, schemaIndex, chartType },
    translationErrors,
  );

  // Enrich boxplot dataOptions with boxType and outliersEnabled from styleOptions.subtype
  if (chartType === 'boxplot' && dataOptions) {
    const boxType = getBoxTypeFromSubtype(normalized.styleOptions?.subtype);
    const outliersEnabled = boxType === 'iqr' || boxType === 'standardDeviation';
    dataOptions = { ...dataOptions, boxType, outliersEnabled };
  }

  // Translate filters if present
  let filters = null;
  if (normalized.filters && normalized.filters.length > 0) {
    filters = collectTranslationErrors<Filter[] | FilterRelations>(
      () =>
        translateFiltersFromJSON({
          data: normalized.filters || [],
          context: { dataSource, schemaIndex },
        }),
      translationErrors,
    );
  }

  // Translate highlights if present
  let highlights = null;
  if (normalized.highlights && normalized.highlights.length > 0) {
    highlights = collectTranslationErrors<Filter[]>(
      () =>
        translateHighlightsFromJSON({
          data: normalized.highlights || [],
          context: { dataSource, schemaIndex },
        }),
      translationErrors,
    );
  }

  // If any errors were collected or dataOptions failed, return structured error response
  if (translationErrors.length > 0 || dataOptions === null) {
    return {
      success: false,
      errors: translationErrors,
    };
  }

  // Narrow chartType (validated in Phase 1) for typed result
  if (!isValidChartType(normalized.chartType)) {
    return {
      success: false,
      errors: [
        {
          category: 'chartType',
          index: -1,
          input: normalized.chartType,
          message: 'Invalid chartType',
        },
      ],
    };
  }
  const validatedChartType = normalized.chartType;

  const result: ChartProps = {
    dataSet: convertDataSource(dataSource),
    chartType: validatedChartType,
    dataOptions,
    ...(normalized.styleOptions && {
      // Pass-through NLQ JSON; shape matches ChartStyleOptions.
      styleOptions: normalized.styleOptions as ChartStyleOptions,
    }),
    ...(filters && { filters }),
    ...(highlights && { highlights }),
  };

  return {
    success: true,
    data: result,
  };
};
