import { WidgetDto } from '../types.js';

export const textWidgetDTO: WidgetDto = {
  _id: '66d9a146ab28a90032b5b495',
  title: 'RICHTEXT_MAIN.TITLE',
  type: 'richtexteditor',
  subtype: 'richtexteditor',
  oid: '66d9a146ab28a90032b5b494',
  desc: null,
  source: null,
  owner: '662ba7319f04e5001cbc7f58',
  userId: '662ba7319f04e5001cbc7f58',
  created: '2024-09-05T12:17:10.314Z',
  lastUpdated: '2024-09-10T12:19:14.010Z',
  instanceType: 'owner',
  datasource: {
    address: 'LocalHost',
    title: 'Sample ECommerce',
    id: 'localhost_aSampleIAAaECommerce',
    database: 'aSampleIAAaECommerce',
    fullname: 'localhost/Sample ECommerce',
    live: false,
  },
  selection: null,
  metadata: {
    ignore: {
      dimensions: [],
      ids: [],
      all: false,
    },
    panels: [],
    usedFormulasMapping: {},
  },
  tags: [],
  style: {
    content: {
      html: '<font color="#008c9c" size="5"><u style="">fancy text</u></font>',
      vAlign: 'valign-middle',
      bgColor: '#FFFFFF',
      textAlign: 'center',
    },
  },
  instanceid: '2E7CC-1178-BA',
  realTimeRefreshing: false,
  options: {
    triggersDomready: true,
    hideFromWidgetList: true,
    disableExportToCSV: true,
    disableExportToImage: true,
    toolbarButton: {
      css: 'add-rich-text',
      tooltip: 'RICHTEXT_MAIN.TOOLBAR_BUTTON',
    },
    selector: false,
    disallowSelector: true,
    disallowWidgetTitle: true,
    supportsHierarchies: false,
    dashboardFiltersMode: 'filter',
  },
  dashboardid: '66d998d1ab28a90032b5b490',
  _dataSourcePermission: 'owner',
  userAuth: {
    dashboards: {
      create: true,
      delete: true,
      move: true,
      rename: true,
      duplicate: true,
      change_owner: true,
      toggle_edit_mode: true,
      edit_layout: true,
      edit_script: true,
      export_dash: true,
      export_jpeg: true,
      export_image: true,
      export_pdf: true,
      share: true,
      restore: true,
      copy_to_server: true,
      import: true,
      select_palette: true,
      replace_datasource: true,
      undo_import_dash: true,
      toggleDataExploration: true,
      filters: {
        create: true,
        delete: true,
        save: true,
        on_off: true,
        toggle_expansion: true,
        modify: true,
        reorder: true,
        modify_type: true,
        toggle_auto_update: true,
        set_defaults: true,
        advanced: true,
        use_starred: true,
        modify_filter_relationship: true,
      },
    },
    widgets: {
      create: true,
      delete: true,
      rename: true,
      duplicate: true,
      copy_to_dashboard: true,
      edit: true,
      edit_script: true,
      change_type: true,
      export_csv: true,
      export_png: true,
      export_svg: true,
      export_pdf: true,
      modify_selection_attrs: true,
      modify_selection_mode: true,
      drill_to_anywhere: true,
      add_to_pulse: true,
      items: {
        create: true,
        delete: true,
        rename: true,
        modify: true,
        reorder: true,
        modify_type: true,
        modify_format: true,
        on_off: true,
        select_hierarchies: true,
      },
      filters: {
        create: true,
        delete: true,
        save: true,
        on_off: true,
        toggle_expansion: true,
        modify: true,
        modify_layout: true,
        modify_type: true,
        modify_dashboard_filters: true,
        use_starred: true,
      },
      widgetViewOnly: false,
    },
    base: {
      isConsumer: false,
      isContributor: false,
      isAdmin: false,
      isSuper: true,
    },
  },
  _toDisableOptionsList: {
    widgets: {
      duplicate: false,
    },
  },
};
